import {execFileSync} from "node:child_process";
import {createHash} from "node:crypto";
import type {Candidate} from "../core/types.js";
import {assertExactGitCandidate} from "../evidence/execution.js";
import {assertDirectGitParent} from "../evidence/git-lineage.js";
import {claimTddObligation,type TddObligation} from "../lifecycle/applicability.js";
import {claimNodeCoverageObservation,type NodeCoverageObservation} from "./tdd-observation.js";
import {createVerifiedNonTddAlternativeRecord,type VerifiedNonTddAlternativeRecord} from "./tdd-completion-record.js";

export interface NonTddDecisionPoint {readonly behaviorPath:string;readonly startOffset:number;readonly endOffset:number}
export interface NonTddDecisionPath {readonly caseId:string;readonly points:readonly NonTddDecisionPoint[]}
export interface NonTddAlternativePlan {readonly reason:"baseline-already-passes";readonly rationale:string;readonly decisionPaths:readonly NonTddDecisionPath[]}
export interface NonTddAlternativeResult {
 readonly alternativeId:string;readonly requirementId:string;readonly planId:string;
 readonly state:"verified-non-tdd-alternative";readonly method:"non-tdd-alternative";readonly reason:"baseline-already-passes";readonly rationale:string;
 readonly binding:Readonly<{candidateId:string;repository:string}>;readonly revisions:Readonly<{baseline:string;candidate:string}>;readonly caseIds:readonly string[];
}
export interface NonTddAlternativeController {readonly controllerId:string;readonly requirementId:string;readonly planId:string;readonly plan:NonTddAlternativePlan;record(baselineCoverage:NodeCoverageObservation,candidate:Candidate,candidateCoverage:NodeCoverageObservation):NonTddAlternativeResult}

export interface NonTddAlternativeResultFacts {readonly result:NonTddAlternativeResult;readonly record:VerifiedNonTddAlternativeRecord;readonly requirementId:string;readonly taskIdentity:string;readonly repositoryIdentity:string;readonly candidateId:string;readonly behaviorPaths:readonly string[];readonly testPaths:readonly string[];readonly caseIds:readonly string[];readonly baselineRevision:string;readonly finalRevision:string}
const candidateKeys=["id","repository","revision","createdAt"] as const;
const issuedResults=new WeakMap<object,NonTddAlternativeResultFacts>(),claimedResults=new WeakSet<object>();
/** Burns one genuine result and returns only its descriptive provenance. */
export function claimNonTddAlternativeResult(value:unknown):NonTddAlternativeResultFacts{if(typeof value!=="object"||value===null||!issuedResults.has(value))throw new Error("non-TDD alternative result was not issued here");if(claimedResults.has(value))throw new Error("non-TDD alternative result has already been claimed");claimedResults.add(value);return issuedResults.get(value)!;}
function exact(value:unknown,keys:readonly string[],noun:string):Record<string,unknown>{
 if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(`${noun} must be exact plain data`);
 const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key))||keys.some(key=>!Object.hasOwn(value,key)))throw new Error(`${noun} shape is invalid`);
 return Object.fromEntries(keys.map(key=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor?.enumerable||!("value" in descriptor))throw new Error(`${noun} shape is invalid`);return [key,descriptor.value];}));
}
function text(value:unknown,noun:string,normalized=false):string{if(typeof value!=="string"||!value||value.trim()!==value||value!==value.normalize("NFC")||/[\u0000-\u001f\u007f-\u009f]/u.test(value)||normalized&&value.replace(/\s+/gu," ")!==value)throw new Error(`${noun} is malformed`);return value;}
function path(value:unknown):string{const result=text(value,"behavior path");if(result.startsWith("/")||result.includes("\\")||result.includes(":")||result.split("/").some(part=>!part||part==="."||part===".."))throw new Error("behavior path is not canonical");return result;}
function array<T>(value:unknown,noun:string,parse:(item:unknown)=>T):T[]{
 if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||!value.length)throw new Error(`${noun} must be a nonempty exact array`);const indexes=Array.from({length:value.length},(_,index)=>String(index)),own=Reflect.ownKeys(value);if(own.some(key=>typeof key!=="string"||key!=="length"&&!indexes.includes(key))||indexes.some(index=>!Object.hasOwn(value,index)))throw new Error(`${noun} must be a nonempty exact array`);return indexes.map(index=>parse(Object.getOwnPropertyDescriptor(value,index)!.value));
}
function parsePlan(value:NonTddAlternativePlan,behaviorPaths:readonly string[]):NonTddAlternativePlan{
 const raw=exact(value,["reason","rationale","decisionPaths"],"non-TDD alternative plan");if(raw.reason!=="baseline-already-passes")throw new Error("non-TDD alternative reason is unsupported");const rationale=text(raw.rationale,"non-TDD rationale",true);
 const decisions=array(raw.decisionPaths,"decision paths",item=>{const entry=exact(item,["caseId","points"],"decision path"),caseId=text(entry.caseId,"case id"),points=array(entry.points,"decision points",point=>{const data=exact(point,["behaviorPath","startOffset","endOffset"],"decision point"),behaviorPath=path(data.behaviorPath),start=data.startOffset,end=data.endOffset;if(!behaviorPaths.includes(behaviorPath))throw new Error("decision point is not a genuine obligation behavior path");if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||(start as number)<0||(start as number)>=(end as number))throw new Error("decision point offsets are unsafe");return Object.freeze({behaviorPath,startOffset:start as number,endOffset:end as number});}),keys=points.map(point=>JSON.stringify([point.behaviorPath,point.startOffset,point.endOffset]));if(new Set(keys).size!==keys.length||points.some((point,index)=>index>0&&keys[index-1]!>=keys[index]!))throw new Error("decision points must be unique and canonical");return Object.freeze({caseId,points:Object.freeze(points)});});
 const caseIds=decisions.map(item=>item.caseId),vectors=decisions.map(item=>JSON.stringify(item.points));if(new Set(caseIds).size!==caseIds.length||caseIds.some((item,index)=>index>0&&caseIds[index-1]!>=item))throw new Error("decision paths must have unique canonical case ids");if(new Set(vectors).size!==vectors.length)throw new Error("decision path vectors must be unique");return Object.freeze({reason:"baseline-already-passes",rationale,decisionPaths:Object.freeze(decisions)});
}
function candidate(value:Candidate):Candidate{const data=exact(value,candidateKeys,"candidate");return {id:text(data.id,"candidate id"),repository:text(data.repository,"candidate repository"),revision:text(data.revision,"candidate revision"),createdAt:text(data.createdAt,"candidate creation time")};}
function same(a:readonly string[],b:readonly string[]):boolean{return a.length===b.length&&a.every((item,index)=>item===b[index]);}
function git(repository:string,args:string[],noun:string):string{try{return execFileSync("git",["--no-replace-objects","-C",repository,...args],{encoding:"utf8",stdio:["ignore","pipe","ignore"]});}catch{throw new Error(`${noun} could not be inspected`);}}
function changedPaths(repository:string,from:string,to:string):string[]{const lines=git(repository,["diff-tree","-r","--no-commit-id","--raw","--find-renames","--find-copies-harder",from,to,"--"],"Git diff").trim().split("\n").filter(Boolean),changed:string[]=[];for(const line of lines){const match=/^:\d+ \d+ [0-9a-f]+ [0-9a-f]+ ([A-Z]\d*)\t(.+)$/u.exec(line);if(!match)throw new Error("Git diff shape is invalid");if(/^[RCT]/u.test(match[1]!))throw new Error("candidate diff cannot rename, copy, or change type");changed.push(path(match[2]!));}return changed;}
function treeIdentity(repository:string,revision:string,file:string):string{const line=git(repository,["ls-tree",revision,"--",file],"test identity").trim(),match=/^(\d+) blob ([0-9a-f]+)\t(.+)$/u.exec(line);if(!match||match[3]!==file)throw new Error("every test path must remain an exact blob");return `${match[1]}:${match[2]}`;}
function covers(observation:NodeCoverageObservation,caseId:string,point:NonTddDecisionPoint):boolean{const behavior=observation.cases.find(item=>item.caseId===caseId)?.behavior.find(item=>item.path===point.behaviorPath);return Boolean(behavior?.ranges.some(range=>range.startOffset<point.endOffset&&point.startOffset<range.endOffset));}

/** Claims the genuine obligation before parsing any caller-controlled alternative plan. */
export function beginNonTddAlternative(obligation:TddObligation,value:NonTddAlternativePlan):NonTddAlternativeController{
 claimTddObligation(obligation);if(obligation.mode!=="required")throw new Error("non-TDD alternative requires an applicable obligation");const plan=parsePlan(value,obligation.behaviorPaths),binding=JSON.stringify({requirementId:obligation.requirementId,plan}),planId=createHash("sha256").update(`non-tdd-plan\0${binding}`).digest("hex"),controllerId=createHash("sha256").update(`non-tdd-controller\0${binding}`).digest("hex"),token={};let attempted=false,controller:NonTddAlternativeController;
 const record=function(this:unknown,baselineCoverage:NodeCoverageObservation,candidateValue:Candidate,candidateCoverage:NodeCoverageObservation):NonTddAlternativeResult{
  if(this!==controller)throw new Error("non-TDD alternative method requires the exact issued controller");if(attempted)throw new Error("non-TDD alternative was already attempted");attempted=true;let baselineProof:unknown,candidateProof:unknown,claimError:unknown;try{baselineProof=claimNodeCoverageObservation(baselineCoverage);}catch(error){claimError=error;}try{candidateProof=claimNodeCoverageObservation(candidateCoverage);}catch(error){claimError??=error;}if(claimError||!baselineProof||!candidateProof)throw claimError;
  const next=candidate(candidateValue),baseline=baselineCoverage.candidate;if(baseline.id!==obligation.candidate.id||baseline.repository!==obligation.candidate.repository||baseline.repository!==obligation.repositoryIdentity||baseline.revision!==obligation.candidate.revision)throw new Error("baseline coverage does not bind the obligation candidate");if(next.id!==baseline.id||next.repository!==baseline.repository)throw new Error("candidate identity mismatch");assertExactGitCandidate(next,next.repository);assertDirectGitParent(next.repository,baseline.revision,next.revision);if(candidateCoverage.candidate.id!==next.id||candidateCoverage.candidate.repository!==next.repository||candidateCoverage.candidate.revision!==next.revision)throw new Error("candidate coverage mismatch");
  const caseIds=plan.decisionPaths.map(item=>item.caseId);for(const observation of [baselineCoverage,candidateCoverage])if(observation.adapterId!=="node-test-v8"||!same(observation.testPaths,baselineCoverage.testPaths)||!same(observation.plannedCaseIds,caseIds)||!same(observation.cases.map(item=>item.caseId),caseIds))throw new Error("coverage must use the exact adapter, ordered tests, and planned cases");if(baselineCoverage.commandFingerprint!==candidateCoverage.commandFingerprint)throw new Error("coverage command identity changed");
  for(const testPath of baselineCoverage.testPaths)if(treeIdentity(next.repository,baseline.revision,testPath)!==treeIdentity(next.repository,next.revision,testPath))throw new Error("test blobs and modes must be unchanged");const changed=changedPaths(next.repository,baseline.revision,next.revision);if(!changed.length)throw new Error("candidate diff must be nonempty");if(changed.some(item=>baselineCoverage.testPaths.includes(item)||!obligation.behaviorPaths.includes(item)))throw new Error("candidate diff must contain only exact obligation behavior paths");
  for(const observation of [baselineCoverage,candidateCoverage])for(const decision of plan.decisionPaths){if(decision.points.some(point=>!covers(observation,decision.caseId,point)))throw new Error("every declared point must have positive coverage");if(plan.decisionPaths.length>1&&!decision.points.some(point=>plan.decisionPaths.filter(other=>other.caseId!==decision.caseId).some(other=>!covers(observation,other.caseId,point))))throw new Error("multi-path cases must be materially distinct");}
  const result=Object.freeze({alternativeId:controllerId,requirementId:obligation.requirementId,planId,state:"verified-non-tdd-alternative" as const,method:"non-tdd-alternative" as const,reason:plan.reason,rationale:plan.rationale,binding:Object.freeze({candidateId:next.id,repository:next.repository}),revisions:Object.freeze({baseline:baseline.revision,candidate:next.revision}),caseIds:Object.freeze(caseIds)});
  const record=createVerifiedNonTddAlternativeRecord({obligation,plan,planId,controllerId,alternativeId:result.alternativeId,commandFingerprint:candidateCoverage.commandFingerprint,testPaths:baselineCoverage.testPaths,caseIds,baseline:baseline.revision,final:next.revision});issuedResults.set(result,Object.freeze({result,record,requirementId:obligation.requirementId,taskIdentity:obligation.taskIdentity,repositoryIdentity:obligation.repositoryIdentity,candidateId:next.id,behaviorPaths:Object.freeze([...obligation.behaviorPaths]),testPaths:Object.freeze([...baselineCoverage.testPaths]),caseIds:Object.freeze([...caseIds]),baselineRevision:baseline.revision,finalRevision:next.revision}));return result;
 };
 controller=Object.freeze({controllerId,requirementId:obligation.requirementId,planId,plan,record});return controller;
}
