import {mkdir,readFile,rename,rm,writeFile} from "node:fs/promises";import path from "node:path";import {randomUUID} from "node:crypto";import type {HistoryEntry,HistoryPolicy} from "./history.js";import {trimHistory} from "./history.js";
interface HistoryFile{schema:"asen.history/v1";revision:number;entries:HistoryEntry[];tombstones:string[]}
const SCHEMA="asen.history/v1" as const;
export function parseHistoryStore(raw:string):HistoryFile{const v=JSON.parse(raw) as Partial<HistoryFile>;if(v.schema!==SCHEMA||!Number.isInteger(v.revision)||v.revision!<0||!Array.isArray(v.entries)||!Array.isArray(v.tombstones))throw new Error("Invalid history store");const ids=new Set<string>();for(const e of v.entries){if(!e||typeof e.id!=="string"||ids.has(e.id)||typeof e.text!=="string"||typeof e.projectId!=="string"||typeof e.sessionId!=="string"||typeof e.createdAt!=="string"||typeof e.redacted!=="boolean")throw new Error("Invalid history entry");ids.add(e.id);}return {schema:SCHEMA,revision:v.revision!,entries:v.entries,tombstones:[...new Set(v.tombstones)]};}
export async function readHistoryStore(file:string):Promise<HistoryFile>{try{return parseHistoryStore(await readFile(file,"utf8"));}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return {schema:SCHEMA,revision:0,entries:[],tombstones:[]};throw e;}}
async function write(file:string,v:HistoryFile){await mkdir(path.dirname(file),{recursive:true});const t=`${file}.${randomUUID()}.tmp`;try{await writeFile(t,JSON.stringify(v,null,2)+"\n",{flag:"wx",mode:0o600});await rename(t,file);}catch(e){await rm(t,{force:true});throw e;}}
export async function commitHistory(file:string,expectedRevision:number,change:(v:HistoryFile)=>HistoryFile):Promise<HistoryFile>{const current=await readHistoryStore(file);if(current.revision!==expectedRevision)throw new Error("History revision conflict");const next=change(structuredClone(current));if(next.revision!==expectedRevision+1)throw new Error("History revision must advance once");await write(file,next);return next;}
export function deleteHistoryEntry(v:HistoryFile,id:string):HistoryFile{return {...v,revision:v.revision+1,entries:v.entries.filter(e=>e.id!==id),tombstones:[...new Set([...v.tombstones,id])]};}
export function applyHistoryRetention(v:HistoryFile,policy:HistoryPolicy):HistoryFile{const entries=trimHistory(policy,v.entries),keep=new Set(entries.map(e=>e.id)),removed=v.entries.filter(e=>!keep.has(e.id)).map(e=>e.id);return {...v,revision:v.revision+1,entries,tombstones:[...new Set([...v.tombstones,...removed])]};}
