import assert from "node:assert/strict";
import test from "node:test";
import {evaluateDuplicateSearch,materializeIssue,type IssueForm} from "../src/issues/issue-preparation.js";
import {authorizeRepositoryOperation,type OperationAttempt,type RepositoryOperationAction,type RepositoryOperationBinding} from "../src/repository/operation-policy.js";
import {executeIssueLabelMutation,executeIssuePublication,prepareIssueLabelMutation,prepareIssuePublication,type IssuePublicationPort,type IssueSnapshot} from "../src/issues/issue-publication.js";

const form:IssueForm={id:"bug",titlePrefix:"[Bug] ",titleTemplate:"{{summary}}",labels:["TYPE:Bug","triage"],controls:[{type:"input",id:"summary",label:"Summary",required:true}]};
const issue=materializeIssue(form,{summary:"Crash"},{redactions:[]});
const decisionFor=(candidate=issue,repository="github.example/acme/app")=>evaluateDuplicateSearch({repository,query:"crash",candidateIdentity:candidate.candidateIdentity,current:true,coversOpen:true,coversClosed:true,complete:true,truncated:false,saturated:false,results:[]});
const duplicateDecision=decisionFor();
let serial=0;
const base=(action:RepositoryOperationAction,sessionId=`s-${++serial}`):RepositoryOperationBinding=>({host:"github.example",owner:"acme",repository:"app",sessionId,actor:"maintainer",action});
const prep=(overrides:Record<string,unknown>={})=>{const candidate=(overrides.issue??issue) as typeof issue,binding=(overrides.binding??base("issue_create")) as RepositoryOperationBinding,decision=overrides.duplicateDecision??decisionFor(candidate,`${binding.host.toLowerCase().replace(/\.$/u,"")}/${binding.owner}/${binding.repository}`);return prepareIssuePublication({issue:candidate,duplicateDecision:decision,binding,remoteLabels:["type:bug","TRIAGE","size:exception"],protectedLabels:["triage","size:exception"],actorPermission:"WRITE",...overrides} as never);};
const snap=(url="https://github.example/acme/app/issues/7",labels:readonly string[]=["type:bug","TRIAGE"]):IssueSnapshot=>({url,title:issue.title,body:issue.body,labels,candidateIdentity:issue.candidateIdentity});
const port=(attempt:OperationAttempt={status:"accepted"},observed:readonly IssueSnapshot[]= [snap()])=>{const calls:{kind:string;args:unknown[]}[]=[];const value:IssuePublicationPort={create(...args){calls.push({kind:"create",args});return attempt;},readCreated(...args){calls.push({kind:"readCreated",args});return observed;},readIssue(...args){calls.push({kind:"readIssue",args});return observed[0]??null;},mutateLabels(...args){calls.push({kind:"mutateLabels",args});return attempt;}};return {value,calls};};

const publish=async(attempt:OperationAttempt={status:"accepted"},observed:readonly IssueSnapshot[]=[snap()])=>{const plan=prep(),authority=authorizeRepositoryOperation(plan.binding),remote=port(attempt,observed);return {plan,remote,result:await executeIssuePublication(plan,authority,plan.binding,remote.value)};};

test("prepares an immutable canonical publication plan without mutating inputs",()=>{
 const labeled=materializeIssue({...form,labels:["TYPE:BUG","triage","size:exception"]},{summary:"Crash"},{redactions:[]}),input={issue:labeled,duplicateDecision:decisionFor(labeled),binding:{...base("issue_create"),host:"GITHUB.EXAMPLE."},remoteLabels:["type:bug","TRIAGE","Size:Exception"],protectedLabels:["triage","size:exception"],actorPermission:"WRITE",sizeExceptionRationale:"Required evidence"} as const,before=structuredClone(input);
 const plan=prepareIssuePublication(input);assert.deepEqual(plan.labels,["type:bug","TRIAGE","Size:Exception"]);assert.equal(plan.candidateIdentity,labeled.candidateIdentity);assert.deepEqual(plan.binding,{host:"github.example",owner:"acme",repository:"app",sessionId:input.binding.sessionId,actor:"maintainer",action:"issue_create"});assert.deepEqual(Reflect.ownKeys(plan.binding),["host","owner","repository","sessionId","actor","action"]);assert.equal(Object.getPrototypeOf(plan.binding),Object.prototype);assert.notEqual(plan.binding,input.binding);assert.equal(Object.isFrozen(plan)&&Object.isFrozen(plan.binding)&&Object.isFrozen(plan.labels)&&Object.isFrozen(plan.payload),true);assert.equal(JSON.stringify(plan).includes("credential"),false);assert.deepEqual(input,before);
});

test("fails closed on duplicate decisions, inventory ambiguity, undeclared labels, protection, and rationale",()=>{
 assert.throws(()=>prep({duplicateDecision:{status:"proceed",reason:"all_not_duplicate",duplicateIssue:null}}),/genuine/);
 assert.throws(()=>prep({issue:materializeIssue(form,{summary:"Other"},{redactions:[]}),duplicateDecision}),/candidate identity/);assert.throws(()=>prep({binding:{...base("issue_create"),repository:"other"},duplicateDecision}),/repository/);
 const blocked=evaluateDuplicateSearch({repository:"github.example/acme/app",query:"crash",candidateIdentity:issue.candidateIdentity,current:true,coversOpen:true,coversClosed:true,complete:true,truncated:false,saturated:false,results:[{issue:"https://github.example/acme/app/issues/1",repository:"github.example/acme/app",query:"crash",candidateIdentity:issue.candidateIdentity,classification:"duplicate"}]});assert.throws(()=>prep({duplicateDecision:blocked}),/duplicate decision/);
 assert.throws(()=>prep({remoteLabels:["type:bug","TYPE:BUG","triage"]}),/ambiguous/);assert.throws(()=>prep({remoteLabels:["other","triage"]}),/remote label/);
 assert.throws(()=>prep({actorPermission:"TRIAGE"}),/permission/);const exceptional=materializeIssue({...form,labels:["type:bug","size:exception"]},{summary:"Crash"},{redactions:[]});assert.throws(()=>prep({issue:exceptional}),/rationale/);
 assert.throws(()=>prep({issue:Object.freeze({...issue,labels:Object.freeze(["undeclared"])})}),/identity/);
});

test("requires a fresh exact plain publication binding without credentials, extras, accessors, or structured separators",()=>{
 const valid=base("issue_create"),before=structuredClone(valid),getter={...valid};let getterCalls=0;Object.defineProperty(getter,"host",{enumerable:true,get(){getterCalls++;return "github.example";}});
 const invalid=[{...valid,credential:"secret"},{...valid,[Symbol("extra")]:true},Object.assign(Object.create({credential:"secret"}),valid),getter,{...valid,host:"user@github.example"},{...valid,host:"https://github.example"},{...valid,owner:"acme/team"},{...valid,repository:"app\\fork"},{...valid,sessionId:"two words"}];
 for(const binding of invalid)assert.throws(()=>prep({binding,duplicateDecision}),/binding/);assert.equal(getterCalls,0);assert.deepEqual(valid,before);
});

test("publishes once, reads once, freezes exact callback arguments, and returns genuine confirmed provenance",async()=>{
 const {plan,remote,result}=await publish();assert.equal(result.classification,"confirmed");assert.equal(result.issueUrl,"https://github.example/acme/app/issues/7");assert.equal(remote.calls.length,2);assert.deepEqual(remote.calls.map(call=>call.kind),["create","readCreated"]);
 for(const call of remote.calls){assert.equal(Object.isFrozen(call.args[0]),true);assert.equal(Object.isFrozen(call.args[1]),true);}assert.deepEqual(remote.calls[0]!.args,[plan.binding,plan.payload]);
 const replay=port(),fresh=authorizeRepositoryOperation(plan.binding);await assert.rejects(()=>executeIssuePublication(plan,fresh,plan.binding,replay.value),/plan already consumed/);assert.equal(replay.calls.length,0);
 const mismatched=prep(),wrongAuthority=authorizeRepositoryOperation({...mismatched.binding,sessionId:`wrong-${serial}`}),wrongPort=port();await assert.rejects(()=>executeIssuePublication(mismatched,wrongAuthority,mismatched.binding,wrongPort.value),/binding/);assert.equal(wrongPort.calls.length,0);await assert.rejects(()=>executeIssuePublication(mismatched,wrongAuthority,mismatched.binding,wrongPort.value),/plan already consumed/);
 const wrongPlan=prep(),wrong={...wrongPlan.binding,action:"issue_update" as const},actionPort=port();await assert.rejects(()=>executeIssuePublication(wrongPlan,authorizeRepositoryOperation(wrong),wrong,actionPort.value),/binding/);assert.equal(actionPort.calls.length,0);
});

test("rejects forged/wrong authority and classifies observed publication evidence without trusting intended flags",async()=>{
 const plan=prep(),forged={...plan.binding} as never,zero=port();await assert.rejects(()=>executeIssuePublication(plan,forged,plan.binding,zero.value),/issued/);assert.equal(zero.calls.length,0);
 for(const [attempt,observed,classification] of [
  [{status:"rejected"},[],"no_write"],[{status:"accepted"},[],"unknown"],[{status:"ambiguous",reasonCode:"timeout"},[snap()],"confirmed"],[{status:"ambiguous",reasonCode:"http_5xx"},[snap("https://github.example/acme/app/issues/8",["other"])],"unknown"],[{status:"accepted"},[snap(),snap("https://github.example/acme/app/issues/8")],"unknown"],[{status:"accepted"},[{...snap(),url:"http://github.example/acme/app/issues/7",intended:true}],"unknown"],
 ] as const){const plan=prep(),remote=port(attempt,observed as readonly IssueSnapshot[]),result=await executeIssuePublication(plan,authorizeRepositoryOperation(plan.binding),plan.binding,remote.value);assert.equal(result.classification,classification);assert.equal(remote.calls.length,2);assert.equal("issueUrl" in result,classification==="confirmed");assert.equal(JSON.stringify(result).includes(issue.body),false);const count=remote.calls.length;await assert.rejects(()=>executeIssuePublication(plan,authorizeRepositoryOperation(plan.binding),plan.binding,remote.value),/plan already consumed/);assert.equal(remote.calls.length,count);}
});

test("rejects noncanonical URLs and inexact snapshot records without invoking accessors",async()=>{
 const canonical=snap(),accessor={...canonical},accessorLabels=[...canonical.labels];let getterCalls=0;Object.defineProperty(accessor,"url",{enumerable:true,get(){getterCalls++;return canonical.url;}});Object.defineProperty(accessorLabels,"0",{enumerable:true,get(){getterCalls++;return canonical.labels[0];}});const inherited=Object.assign(Object.create({extra:true}),canonical),symbol={...canonical,[Symbol("extra")]:true},extra={...canonical,extra:true},labelExtra={...canonical,labels:Object.assign([...canonical.labels],{extra:true})},labelAccessor={...canonical,labels:accessorLabels};
 for(const snapshot of [accessor,inherited,symbol,extra,labelExtra,labelAccessor]){const plan=prep(),remote=port({status:"accepted"},[snapshot] as readonly IssueSnapshot[]),result=await executeIssuePublication(plan,authorizeRepositoryOperation(plan.binding),plan.binding,remote.value);assert.equal(result.classification,"unknown");}const outer=Object.assign([canonical],{extra:true}),outerPlan=prep(),outerRemote=port({status:"accepted"},outer);assert.equal((await executeIssuePublication(outerPlan,authorizeRepositoryOperation(outerPlan.binding),outerPlan.binding,outerRemote.value)).classification,"unknown");assert.equal(getterCalls,0);
 for(const url of ["https://GITHUB.EXAMPLE/acme/app/issues/7","https://github.example/Acme/app/issues/7","https://github.example/acme/other/../app/issues/7","https://github.example:443/acme/app/issues/7","https://user@github.example/acme/app/issues/7","https://github.example/acme/app/issues/7?x=1","https://github.example/acme/app/issues/7#x","https://github.example/acme/app/issues/07"]){const plan=prep(),remote=port({status:"accepted"},[snap(url)]),result=await executeIssuePublication(plan,authorizeRepositoryOperation(plan.binding),plan.binding,remote.value);assert.equal(result.classification,"unknown");}
});

test("transport and readback throws are sanitized and never retried",async()=>{
 const plan=prep(),calls:string[]=[],remote:IssuePublicationPort={create(){calls.push("create");throw new Error(`SECRET ${issue.body}`);},readCreated(){calls.push("read");return [snap()];},readIssue(){throw new Error("unused");},mutateLabels(){throw new Error("unused");}};const result=await executeIssuePublication(plan,authorizeRepositoryOperation(plan.binding),plan.binding,remote);assert.equal(result.classification,"confirmed");assert.deepEqual(calls,["create","read"]);assert.equal(JSON.stringify(result).includes("SECRET"),false);
 const second=prep(),broken={...remote,readCreated(){calls.push("broken");throw new Error("SECRET body");}};const unknown=await executeIssuePublication(second,authorizeRepositoryOperation(second.binding),second.binding,broken);assert.equal(unknown.classification,"unknown");
});

test("only genuine confirmed publication results prepare atomic protected mutation preserving unrelated labels",async()=>{
 const {result}=await publish(),current=snap(undefined,["type:bug","TRIAGE","keep"]),input={add:["size:exception"],remove:["triage"],protectedLabels:["triage","size:exception"],actorPermission:"WRITE" as const,rationale:"Large evidence"},before=structuredClone([current,input]),mutation=prepareIssueLabelMutation(result,current,input);assert.deepEqual(mutation.expectedFinalLabels,["keep","size:exception","type:bug"]);assert.deepEqual(mutation.add,["size:exception"]);assert.deepEqual(mutation.remove,["triage"]);assert.match(mutation.baselineSnapshotHash,/^sha256:/);assert.equal(Object.isFrozen(mutation),true);assert.deepEqual([current,input],before);
 assert.throws(()=>prepareIssueLabelMutation({...result} as never,current,{add:[],remove:[],protectedLabels:[],actorPermission:"WRITE"}),/confirmed publication/);assert.throws(()=>prepareIssueLabelMutation(result,{...current,url:"https://github.example/acme/other/issues/7"},{add:[],remove:[],protectedLabels:[],actorPermission:"WRITE"}),/issue identity/);assert.throws(()=>prepareIssueLabelMutation(result,current,{add:["triage"],remove:[],protectedLabels:["triage"],actorPermission:"TRIAGE"}),/permission/);
});

async function mutationFixture(attempt:OperationAttempt={status:"accepted"},final:IssueSnapshot|null=snap(undefined,["keep","size:exception","type:bug"])){
 const {result}=await publish(),current=snap(undefined,["type:bug","TRIAGE","keep"]),plan=prepareIssueLabelMutation(result,current,{add:["size:exception"],remove:["triage"],protectedLabels:["triage","size:exception"],actorPermission:"WRITE",rationale:"Large evidence"}),readBinding=base("remote_read",plan.binding.sessionId),mutationBinding=base("label_mutate",plan.binding.sessionId),calls:{kind:string;args:unknown[]}[]=[];let reads=0;const remote:IssuePublicationPort={create(){throw new Error("unused");},readCreated(){throw new Error("unused");},readIssue(...args){calls.push({kind:"readIssue",args});return reads++===0?current:final;},mutateLabels(...args){calls.push({kind:"mutateLabels",args});return attempt;}};return {plan,readBinding,mutationBinding,calls,remote};
}

test("pre-read consumes exact authority and mismatch or forgery performs zero mutations",async()=>{
 const f=await mutationFixture();const drift={...f.remote,readIssue(...args:Parameters<IssuePublicationPort["readIssue"]>){f.calls.push({kind:"readIssue",args});return {...snap(),labels:["drift"]};}};const result=await executeIssueLabelMutation(f.plan,authorizeRepositoryOperation(f.readBinding),authorizeRepositoryOperation(f.mutationBinding),{read:f.readBinding,mutation:f.mutationBinding},drift);assert.equal(result.classification,"unknown");assert.equal(f.calls.filter(c=>c.kind==="mutateLabels").length,0);const count=f.calls.length;await assert.rejects(()=>executeIssueLabelMutation(f.plan,authorizeRepositoryOperation(f.readBinding),authorizeRepositoryOperation({...f.mutationBinding,sessionId:`fresh-${serial}`}),{read:f.readBinding,mutation:f.mutationBinding},drift),/plan already consumed/);assert.equal(f.calls.length,count);
 const other=await mutationFixture(),forged={...other.readBinding} as never;await assert.rejects(()=>executeIssueLabelMutation(other.plan,forged,authorizeRepositoryOperation(other.mutationBinding),{read:other.readBinding,mutation:other.mutationBinding},other.remote),/issued/);assert.equal(other.calls.length,0);
});

test("requires exact snapshots for mutation preparation, baseline, and readback",async()=>{
 const {result}=await publish(),current=snap(undefined,["type:bug","TRIAGE","keep"]),accessor={...current};let getterCalls=0;Object.defineProperty(accessor,"labels",{enumerable:true,get(){getterCalls++;return current.labels;}});assert.throws(()=>prepareIssueLabelMutation(result,accessor,{add:[],remove:[],protectedLabels:[],actorPermission:"WRITE"}),/issue identity/);assert.equal(getterCalls,0);
 const baseline=await mutationFixture(),badBaseline={...baseline.remote,readIssue(...args:Parameters<IssuePublicationPort["readIssue"]>){baseline.calls.push({kind:"readIssue",args});return {...current,extra:true} as never;}};assert.equal((await executeIssueLabelMutation(baseline.plan,authorizeRepositoryOperation(baseline.readBinding),authorizeRepositoryOperation(baseline.mutationBinding),{read:baseline.readBinding,mutation:baseline.mutationBinding},badBaseline)).classification,"unknown");assert.equal(baseline.calls.some(call=>call.kind==="mutateLabels"),false);
 const readback=await mutationFixture({status:"accepted"},{...snap(undefined,["keep","size:exception","type:bug"]),[Symbol("extra")]:true});assert.equal((await executeIssueLabelMutation(readback.plan,authorizeRepositoryOperation(readback.readBinding),authorizeRepositoryOperation(readback.mutationBinding),{read:readback.readBinding,mutation:readback.mutationBinding},readback.remote)).classification,"unknown");
});

test("executes one atomic add/remove and one readback with confirmed, no-write, and unknown outcomes",async()=>{
 for(const [attempt,final,expected] of [[{status:"accepted"},snap(undefined,["type:bug","keep","size:exception"]),"confirmed"],[{status:"rejected"},snap(undefined,["type:bug","TRIAGE","keep"]),"no_write"],[{status:"ambiguous",reasonCode:"timeout"},snap(undefined,["drift"]),"unknown"]] as const){const f=await mutationFixture(attempt,final),result=await executeIssueLabelMutation(f.plan,authorizeRepositoryOperation(f.readBinding),authorizeRepositoryOperation(f.mutationBinding),{read:f.readBinding,mutation:f.mutationBinding},f.remote);assert.equal(result.classification,expected);assert.deepEqual(f.calls.map(c=>c.kind),["readIssue","mutateLabels","readIssue"]);assert.deepEqual(f.calls[1]!.args,[f.mutationBinding,Object.freeze({issueUrl:f.plan.issueUrl,baselineSnapshotHash:f.plan.baselineSnapshotHash,add:f.plan.add,remove:f.plan.remove})]);const count=f.calls.length;await assert.rejects(()=>executeIssueLabelMutation(f.plan,authorizeRepositoryOperation(f.readBinding),authorizeRepositoryOperation(f.mutationBinding),{read:f.readBinding,mutation:f.mutationBinding},f.remote),/plan already consumed/);assert.equal(f.calls.length,count);}
 const f=await mutationFixture(),throwing={...f.remote,readIssue(...args:Parameters<IssuePublicationPort["readIssue"]>){f.calls.push({kind:"readIssue",args});if(f.calls.filter(c=>c.kind==="readIssue").length===2)throw new Error("SECRET");return snap(undefined,["type:bug","TRIAGE","keep"]);}};const result=await executeIssueLabelMutation(f.plan,authorizeRepositoryOperation(f.readBinding),authorizeRepositoryOperation(f.mutationBinding),{read:f.readBinding,mutation:f.mutationBinding},throwing);assert.equal(result.classification,"unknown");assert.equal(JSON.stringify(result).includes("SECRET"),false);
 const staleBaseline=snap(undefined,["type:bug","TRIAGE","keep"]),stale=await mutationFixture({status:"accepted"},staleBaseline),stalePort={...stale.remote,mutateLabels(...args:Parameters<IssuePublicationPort["mutateLabels"]>){stale.calls.push({kind:"mutateLabels",args});assert.equal(args[1].baselineSnapshotHash,stale.plan.baselineSnapshotHash);return {status:"rejected",reasonCode:"stale_baseline"} as const;}};const rejected=await executeIssueLabelMutation(stale.plan,authorizeRepositoryOperation(stale.readBinding),authorizeRepositoryOperation(stale.mutationBinding),{read:stale.readBinding,mutation:stale.mutationBinding},stalePort);assert.equal(rejected.classification,"no_write");assert.equal(rejected.operationReason,"stale_baseline");
});
