import assert from "node:assert/strict";
import {createHash,createHmac,randomBytes} from "node:crypto";
import {mkdtemp,readFile,rm,writeFile} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import test from "node:test";
import type {Candidate} from "../src/core/types.js";
import {decideLifecycleApplicability,tddObligationFor} from "../src/lifecycle/applicability.js";
import {lifecyclePhases,loadLifecycle,saveLifecycle,type LifecyclePhase,type LifecycleSnapshot} from "../src/lifecycle/skill-lifecycle.js";
import {Dispatcher} from "../src/agents/dispatcher.js";
import {EvidenceStore} from "../src/evidence/store.js";
import {buildOrchestrationPlan} from "../src/orchestration/orchestrator.js";
import {issueSkillContext} from "../src/skills/context.js";
import {selectSkills} from "../src/skills/registry.js";
import {createStrictTddCompletionRecord,createVerifiedNonTddAlternativeRecord,type TddCompletionRecord} from "../src/test/tdd-completion-record.js";
import {commitCandidateFiles,gitCandidate,passingEvidence,passingReview} from "./execution-evidence-helper.js";
import {fixtureArtifactRunner} from "./lifecycle-pi-fixture.js";
import {issueOddDecision} from "./helpers/odd-routing.js";
import {admitRouteEvidence} from "./helpers/route-evidence.js";
import {verifySkillEvidence} from "../src/verify/verifier.js";

const behaviorPath="src/x.mjs",kinds:Record<LifecyclePhase,string>={"context-init":"project-context",explore:"exploration",proposal:"proposal",specification:"specification",design:"design",tasks:"task-plan",apply:"apply-result",verify:"verification-report",archive:"archive-report"},roles:Record<LifecyclePhase,"explorer"|"worker"|"verifier">={"context-init":"worker",explore:"explorer",proposal:"worker",specification:"worker",design:"worker",tasks:"worker",apply:"worker",verify:"verifier",archive:"worker"};
const clone=<T>(value:T):T=>structuredClone(value),h=(domain:string,value:unknown)=>createHash("sha256").update(`${domain}\0${JSON.stringify(value)}`).digest("hex");
function obligationFor(baseline:Candidate,task:string){const decision=issueOddDecision({taskId:task,repository:baseline.repository,paths:[behaviorPath],writes:[{path:behaviorPath,changeKind:"behavior"}],testingRequired:true});buildOrchestrationPlan({taskId:task,repository:baseline.repository,prompt:"apply",candidate:baseline},decision);return tddObligationFor(decideLifecycleApplicability(decision,{taskIdentity:task,repositoryIdentity:baseline.repository,candidate:{id:baseline.id,repository:baseline.repository,revision:baseline.revision},explicitMode:"unspecified",affectedSubsystems:["tdd"],expectedPaths:[behaviorPath],requiredArtifacts:[]}));}
function snapshot(task:string,baseline:Candidate,final:Candidate,record:TddCompletionRecord,revisions:string[]):Extract<LifecycleSnapshot,{version:2}>{return {version:2,taskId:task,candidate:{...baseline,revision:final.revision},baselineRevision:baseline.revision,nextPhase:"verify",records:lifecyclePhases.slice(0,7).map(phase=>({phase,role:roles[phase],artifact:{kind:kinds[phase],content:phase,repository:baseline.repository,candidateId:baseline.id,revision:baseline.revision},skillPaths:[]})),revisions,tddPromotion:{method:record.promotionMethod,record}};}
function fixture(t:test.TestContext,options={triangulate:true,refactor:true}){const initial=gitCandidate("c5b"),baseline=commitCandidateFiles(initial,{[behaviorPath]:"export const x=0;\n"}),red=commitCandidateFiles(baseline,{"tests/x.test.mjs":"// red\n"}),green=commitCandidateFiles(red,{[behaviorPath]:"export const x=1;\n"}),terminal=options.triangulate?commitCandidateFiles(green,{"tests/x.test.mjs":"// triangulated\n"}):green,final=options.refactor?commitCandidateFiles(terminal,{[behaviorPath]:"export const x=2;\n"}):terminal; t.after(()=>rm(initial.repository,{recursive:true,force:true}));
 const task="GSP-05C5b",obligation=obligationFor(baseline,task),decisionPaths=options.triangulate?[{caseId:"first",points:[{behaviorPath,startOffset:0,endOffset:1}]},{caseId:"second",points:[{behaviorPath,startOffset:1,endOffset:2}]}]:[{caseId:"first",points:[{behaviorPath,startOffset:0,endOffset:1}]}],plan={expectedFailingCaseIds:["first"],decisionPaths,triangulationPolicy:options.triangulate?{mode:"required" as const}:{mode:"not-applicable" as const,reason:"structurally-single-decision-path" as const,rationale:"One structural path."}},binding={requirementId:obligation.requirementId,plan},record=createStrictTddCompletionRecord({obligation,plan,planHash:h("plan",binding),cycleId:h("cycle",binding),commandFingerprint:"a".repeat(64),testPaths:["tests/x.test.mjs"],caseIds:decisionPaths.map(item=>item.caseId),revisions:{baseline:baseline.revision,red:red.revision,green:green.revision,terminal:terminal.revision,final:final.revision},refactor:options.refactor?{mode:"performed"}:{mode:"not-needed",rationale:"Already minimal."}}),value=snapshot(task,baseline,final,record,[baseline.revision,red.revision,green.revision,...(options.triangulate?[terminal.revision]:[]),...(options.refactor?[final.revision]:[])]);return {task,candidate:value.candidate,snapshot:value};}
function alternativeFixture(t:test.TestContext){const initial=gitCandidate("c5b-alt"),baseline=commitCandidateFiles(initial,{[behaviorPath]:"export const x=1;\n","tests/x.test.mjs":"// passing\n"}),final=commitCandidateFiles(baseline,{[behaviorPath]:"export const x=2;\n"});t.after(()=>rm(initial.repository,{recursive:true,force:true}));const task="GSP-05C5b-alt",obligation=obligationFor(baseline,task),plan={reason:"baseline-already-passes" as const,rationale:"Baseline passes.",decisionPaths:[{caseId:"first",points:[{behaviorPath,startOffset:0,endOffset:1}]}]},binding={requirementId:obligation.requirementId,plan},id=h("non-tdd-controller",binding),record=createVerifiedNonTddAlternativeRecord({obligation,plan,planId:h("non-tdd-plan",binding),controllerId:id,alternativeId:id,commandFingerprint:"b".repeat(64),testPaths:["tests/x.test.mjs"],caseIds:["first"],baseline:baseline.revision,final:final.revision}),value=snapshot(task,baseline,final,record,[baseline.revision,final.revision]);return {task,candidate:value.candidate,snapshot:value};}
async function persisted(t:test.TestContext,value=fixture(t)){const dir=await mkdtemp(join(tmpdir(),"asen-c5b-"));t.after(()=>rm(dir,{recursive:true,force:true}));const path=join(dir,"flow.json"),key=randomBytes(32);await saveLifecycle(path,value.snapshot,key);return {...value,path,key};}
async function resign(path:string,key:Buffer,mutate:(raw:any)=>void){const raw=JSON.parse(await readFile(path,"utf8"));mutate(raw);const {mac:_,...payload}=raw;raw.mac=createHmac("sha256",key).update("asen.lifecycle.v2\0").update(JSON.stringify(payload)).digest("hex");await writeFile(path,JSON.stringify(raw));}

test("strict variants and alternative exact completion round trip",async t=>{for(const triangulate of [true,false])for(const refactor of [true,false]){const v=await persisted(t,fixture(t,{triangulate,refactor}));assert.deepEqual((await loadLifecycle(v.path,v.task,v.candidate,v.key)).state,v.snapshot);}const alternative=await persisted(t,alternativeFixture(t));assert.deepEqual((await loadLifecycle(alternative.path,alternative.task,alternative.candidate,alternative.key)).state,alternative.snapshot);});

test("v2 exact completion binds key and caller identities",async t=>{const v=await persisted(t),flow=await loadLifecycle(v.path,v.task,v.candidate,v.key);assert.deepEqual(flow.state,v.snapshot);await assert.rejects(()=>loadLifecycle(v.path,v.task,v.candidate,randomBytes(32)),/integrity/);for(const [task,candidate] of [["wrong",v.candidate],[v.task,{...v.candidate,repository:"wrong"}],[v.task,{...v.candidate,id:"wrong"}],[v.task,{...v.candidate,revision:v.snapshot.baselineRevision}] ] as const)await assert.rejects(()=>loadLifecycle(v.path,task,candidate,v.key),/identity|integrity/);assert.throws(()=>flow.promoteCandidateRevision(v.snapshot.baselineRevision),/recovery-unknown/);});

test("re-signed semantic and exact-shape tampering fails closed",async t=>{const mutations:Array<(raw:any)=>void>=[r=>r.snapshot.candidate.revision=r.snapshot.baselineRevision,r=>r.snapshot.tddPromotion.method="verified-non-tdd-alternative",r=>r.snapshot.tddPromotion.record.revisions.final=r.snapshot.baselineRevision,r=>r.snapshot.tddPromotion.record.plan.expectedFailingCaseIds[0]="second",r=>r.snapshot.tddPromotion.record.execution.testPaths[0]="../other.mjs",r=>r.snapshot.tddPromotion.record.execution.caseIds[0]="changed",r=>r.snapshot.tddPromotion.record.plan.decisionPaths[0].caseId="changed",r=>r.snapshot.tddPromotion.record.obligation.behaviorPaths[0]="src/other.mjs",r=>r.extra=true,r=>r.snapshot.extra=true];for(const [index,mutate] of mutations.entries()){const v=await persisted(t);await resign(v.path,v.key,mutate);await assert.rejects(()=>loadLifecycle(v.path,v.task,v.candidate,v.key),/invalid|mismatch|shape|lineage|binding|canonical|malformed|do not match/,`mutation ${index}`);}});

test("recovered promoted lifecycle continues only through verify and archive",async t=>{const v=await persisted(t),flow=await loadLifecycle(v.path,v.task,v.candidate,v.key),evidence=new EvidenceStore();admitRouteEvidence(evidence,v.candidate);for(const [id,kind] of [["unit","work-unit"],["scope","scope"],["rollback","rollback"]] as const)evidence.add(v.candidate,{id,kind,status:"pass",summary:id,createdAt:"now"});await passingEvidence(evidence,v.candidate,"test");await passingReview(evidence,v.candidate,"review");assert.throws(()=>flow.promoteCandidateFromTdd({} as never),/not issued|exact live required obligation/);assert.throws(()=>flow.reissuePendingAuthority(),/no signed pending phase authority/);const applyContext=issueSkillContext(`${v.task}:worker`,v.candidate.repository,v.candidate,{phase:"apply"}),applyPaths=selectSkills(applyContext).map(skill=>skill.path);await assert.rejects(()=>flow.runPhase(new Dispatcher(fixtureArtifactRunner(()=>({kind:kinds.apply,content:"apply",repository:v.candidate.repository,candidateId:v.candidate.id,revision:v.candidate.revision})),evidence),{phase:"apply",context:applyContext,skillPaths:applyPaths,prompt:"apply",evidence,risk:"low",writeSurfaces:["src/"]}),/out of order/);for(const phase of ["verify","archive"] as const){const role=roles[phase],context=issueSkillContext(`${v.task}:${role}`,v.candidate.repository,v.candidate,{phase}),skillPaths=selectSkills(context).map(skill=>skill.path),runner=fixtureArtifactRunner(()=>({kind:kinds[phase],content:phase,repository:v.candidate.repository,candidateId:v.candidate.id,revision:v.candidate.revision}));await flow.runPhase(new Dispatcher(runner,evidence),{phase,context,skillPaths,prompt:phase,evidence,risk:"low"});}assert.equal(flow.state.nextPhase,null);assert.equal(evidence.hasPassing(v.candidate,"lifecycle-completion"),true);assert.equal(verifySkillEvidence(v.candidate,["asen-tdd"],evidence,"verification").ok,true);assert.equal(evidence.forCandidate(v.candidate).find(item=>item.kind==="lifecycle-completion")?.completion?.promotionMethod,"strict-completion");});

test("save rejects nested accessors and non-plain prototypes without invoking them",async t=>{const v=fixture(t);let invoked=false;const accessor=clone(v.snapshot) as any;Object.defineProperty(accessor,"taskId",{enumerable:true,get:()=>{invoked=true;return v.task;}});await assert.rejects(()=>saveLifecycle("unused",accessor,randomBytes(32)),/shape/);assert.equal(invoked,false);const proto=Object.assign(Object.create({}),clone(v.snapshot));await assert.rejects(()=>saveLifecycle("unused",proto,randomBytes(32)),/plain data/);});
