import assert from "node:assert/strict";
import test from "node:test";
import {executeDeliveryInspection,prepareBranchDelivery,prepareDeliveryInspection,SUPPORTED_BRANCH_PATTERN,SUPPORTED_COMMIT_PATTERN,type BranchDeliveryPlan} from "../src/delivery/branch-preparation.js";
import {executeLocalBranch,executeNextLocalCommit,prepareLocalDelivery,type LocalDeliveryPort} from "../src/delivery/local-delivery.js";
import {authorizeRepositoryOperation,REPOSITORY_OPERATION_ACTIONS,type RepositoryOperationBinding} from "../src/repository/operation-policy.js";

let serial=0;const id=(character:string)=>`sha256:${character.repeat(64)}`;const tree1=id("b"),tree2=id("c"),base=id("a"),commit1=id("d"),commit2=id("e");
const binding=(action:RepositoryOperationBinding["action"],sessionId=`local-${++serial}`,overrides:Partial<RepositoryOperationBinding>={}):RepositoryOperationBinding=>({host:"github.example",owner:"acme",repository:"app",sessionId,actor:"maintainer",action,...overrides});
async function c1(overrides:Record<string,unknown>={}):Promise<BranchDeliveryPlan>{const read=binding("remote_read"),inspection=prepareDeliveryInspection({binding:read,baseBranch:"main",approvedIssueUrl:"https://github.example/acme/app/issues/42",expectedPolicySourceIdentity:"sha256:policy-v1",policyUrl:"https://github.example/acme/app/blob/abc/POLICY.md"}),observed=await executeDeliveryInspection(inspection,authorizeRepositoryOperation(read),read,{read(){return {...inspection.request,host:"github.example",owner:"acme",repository:"app",issueNumber:42,issueState:"open",issueTitle:"Approved",issueLabels:["status:approved"],branchPattern:SUPPORTED_BRANCH_PATTERN,commitPattern:SUPPORTED_COMMIT_PATTERN,permittedTypeLabels:["type:feature"],protectedLabels:["status:approved"],templateRequired:false,templateWaived:true,requiredTemplateMarkers:[],requiredChecks:["test"]};}});return prepareBranchDelivery(observed,{repositoryUrl:"https://github.example/acme/app",issueUrl:"https://github.example/acme/app/issues/42",policySourceIdentity:"sha256:policy-v1",baseBranch:"main",branch:"feat/local-delivery",commits:["feat(delivery): first","test(delivery): second"],prTitle:"Local delivery",prBody:"Closes https://github.example/acme/app/issues/42",labels:["type:feature"],protectedLabelMutations:[],...overrides});}
const fullPort=(overrides:Partial<LocalDeliveryPort>={}):LocalDeliveryPort=>({createBranch(){return {status:"accepted"};},readBranch(_binding,payload){return {repositoryIdentity:payload.repositoryIdentity,worktreeIdentity:payload.worktreeIdentity,branch:payload.branch,headCommitIdentity:payload.baseCommitIdentity};},commit(){return {status:"accepted"};},readCommit(_binding,payload){return {repositoryIdentity:payload.repositoryIdentity,worktreeIdentity:payload.worktreeIdentity,branch:payload.branch,commitIdentity:payload.treeIdentity===tree1?commit1:commit2,message:payload.message,parentCommitIdentity:payload.parentCommitIdentity,treeIdentity:payload.treeIdentity};},...overrides});
async function branch(port=fullPort(),bindingOverride?:RepositoryOperationBinding){const source={baseCommitIdentity:base,candidateTrees:[tree1,tree2]},before=structuredClone(source),plan=prepareLocalDelivery(await c1(),source),b=bindingOverride??binding("branch_create");const outcome=await executeLocalBranch(plan,authorizeRepositoryOperation(b),b,port);assert.deepEqual(source,before);return {outcome,b,plan};}

test("progresses through one branch and two separately authorized ordered commits",async()=>{const transcript:unknown[][]=[],port=fullPort({createBranch(...args){transcript.push(["branch",...args]);return {status:"accepted"};},readBranch(...args){transcript.push(["branch-read",...args]);const p=args[1];return {repositoryIdentity:p.repositoryIdentity,worktreeIdentity:p.worktreeIdentity,branch:p.branch,headCommitIdentity:p.baseCommitIdentity};},commit(...args){transcript.push(["commit",...args]);return {status:"accepted"};},readCommit(...args){transcript.push(["commit-read",...args]);const p=args[1];return {repositoryIdentity:p.repositoryIdentity,worktreeIdentity:p.worktreeIdentity,branch:p.branch,commitIdentity:p.treeIdentity===tree1?commit1:commit2,message:p.message,parentCommitIdentity:p.parentCommitIdentity,treeIdentity:p.treeIdentity};}}),{outcome}=await branch(port);assert.equal(outcome.classification,"confirmed");assert.equal(Object.isFrozen(outcome),true);const firstBinding=binding("commit"),first=await executeNextLocalCommit(outcome as never,authorizeRepositoryOperation(firstBinding),firstBinding,port);assert.deepEqual(first,{classification:"confirmed",stage:"commit",branch:"feat/local-delivery",headCommitIdentity:commit1,completedCommits:1,totalCommits:2});const secondBinding=binding("commit"),final=await executeNextLocalCommit(first as never,authorizeRepositoryOperation(secondBinding),secondBinding,port);assert.deepEqual(final,{classification:"confirmed",branch:"feat/local-delivery",headCommitIdentity:commit2,commitIdentities:[commit1,commit2]});assert.equal(Object.isFrozen(final)&&Object.isFrozen(final.commitIdentities),true);assert.deepEqual(transcript.map(x=>x[0]),["branch","branch-read","commit","commit-read","commit","commit-read"]);for(const row of transcript){assert.equal(Object.isFrozen(row[1]),true);assert.equal(Object.isFrozen(row[2]),true);}assert.deepEqual(transcript[2]![2],{repositoryIdentity:"https://github.example/acme/app",worktreeIdentity:(transcript[2]![1] as RepositoryOperationBinding).sessionId,branch:"feat/local-delivery",message:"feat(delivery): first",parentCommitIdentity:base,treeIdentity:tree1});});

test("classifies branch rejection with absence as no_write and every uncertain readback as unknown",async()=>{for(const [attempt,read,classification] of [[{status:"rejected"},null,"no_write"],[{status:"accepted"},null,"unknown"],[{status:"accepted"},new Error("timeout SECRET"),"unknown"],[{status:"accepted"},{bad:true},"unknown"],[{status:"accepted"},{repositoryIdentity:"https://github.example/acme/app",worktreeIdentity:"wrong",branch:"feat/local-delivery",headCommitIdentity:base},"unknown"]] as const){const events:string[]=[],port=fullPort({createBranch(){events.push("create");return attempt;},readBranch(){events.push("read");if(read instanceof Error)throw read;return read as never;}}),{outcome}=await branch(port);assert.equal(outcome.classification,classification);assert.deepEqual(events,["create","read"]);assert.equal(JSON.stringify(outcome).includes("SECRET"),false);}});

test("requires genuine single-use C1 plans, exact SHA input, and exact local target before callbacks",async()=>{const genuine=await c1(),forged={...await c1()},invalid=await c1(),input={baseCommitIdentity:base,candidateTrees:[tree1,tree2]},plan=prepareLocalDelivery(genuine,input);assert.equal(Object.isFrozen(plan)&&Object.isFrozen(plan.commits)&&Object.isFrozen(plan.candidateTrees),true);assert.throws(()=>prepareLocalDelivery(genuine,input),/claimed/);assert.throws(()=>prepareLocalDelivery(forged as never,input),/genuine/);assert.throws(()=>prepareLocalDelivery(invalid,{...input,candidateTrees:[tree1]}),/one exact/);let calls=0;const wrong=binding("branch_create",undefined,{repository:"other"});await assert.rejects(()=>executeLocalBranch(plan,authorizeRepositoryOperation(wrong),wrong,fullPort({createBranch(){calls++;return {status:"accepted"};}})),/target/);assert.equal(calls,0);});

test("consumes plans/progress before authority, rejects wrong actions and reuse with zero callbacks",async()=>{const prepared=prepareLocalDelivery(await c1(),{baseCommitIdentity:base,candidateTrees:[tree1,tree2]}),wrong=binding("commit"),events:string[]=[];await assert.rejects(()=>executeLocalBranch(prepared,authorizeRepositoryOperation(wrong),wrong,fullPort({createBranch(){events.push("branch");return {status:"accepted"};}})),/target/);const fresh=binding("branch_create");await assert.rejects(()=>executeLocalBranch(prepared,authorizeRepositoryOperation(fresh),fresh,fullPort()),/consumed/);const {outcome}=await branch(),commitBinding=binding("commit"),first=await executeNextLocalCommit(outcome as never,authorizeRepositoryOperation(commitBinding),commitBinding,fullPort());const reuse=binding("commit");await assert.rejects(()=>executeNextLocalCommit(outcome as never,authorizeRepositoryOperation(reuse),reuse,fullPort({commit(){events.push("commit");return {status:"accepted"};}})),/consumed/);await assert.rejects(()=>executeNextLocalCommit({...first} as never,authorizeRepositoryOperation(binding("commit")),binding("commit"),fullPort()),/genuine/);await assert.rejects(()=>executeNextLocalCommit({classification:"confirmed"} as never,authorizeRepositoryOperation(binding("commit")),binding("commit"),fullPort()),/genuine/);assert.deepEqual(events,[]);});

test("commit rejection unchanged is no_write; timeout exact readback confirms; mismatch and throw block later steps",async()=>{for(const [attempt,read,classification] of [[{status:"rejected"},"unchanged","no_write"],[new Error("timeout SECRET"),"exact","confirmed"],[{status:"accepted"},"mismatch","unknown"],[{status:"accepted"},"malformed","unknown"],[{status:"accepted"},"throw","unknown"]] as const){const {outcome}=await branch(),b=binding("commit"),port=fullPort({commit(){if(attempt instanceof Error)throw attempt;return attempt;},readCommit(_binding,payload){if(read==="throw")throw new Error("read SECRET");if(read==="unchanged")return {repositoryIdentity:payload.repositoryIdentity,worktreeIdentity:payload.worktreeIdentity,branch:payload.branch,headCommitIdentity:payload.parentCommitIdentity};if(read==="exact")return {repositoryIdentity:payload.repositoryIdentity,worktreeIdentity:payload.worktreeIdentity,branch:payload.branch,commitIdentity:commit1,message:payload.message,parentCommitIdentity:payload.parentCommitIdentity,treeIdentity:payload.treeIdentity};if(read==="mismatch")return {repositoryIdentity:payload.repositoryIdentity,worktreeIdentity:payload.worktreeIdentity,branch:payload.branch,commitIdentity:commit1,message:"fix: wrong",parentCommitIdentity:payload.parentCommitIdentity,treeIdentity:payload.treeIdentity};return {extra:true} as never;}}),next=await executeNextLocalCommit(outcome as never,authorizeRepositoryOperation(b),b,port);assert.equal(next.classification,classification);assert.equal(JSON.stringify(next).includes("SECRET"),false);const later=binding("commit");await assert.rejects(()=>executeNextLocalCommit(outcome as never,authorizeRepositoryOperation(later),later,port),/consumed/);}});

test("rejects inexact callback surfaces without invoking getters and exposes no remote delivery callback",async()=>{const plan=prepareLocalDelivery(await c1(),{baseCommitIdentity:base,candidateTrees:[tree1,tree2]}),b=binding("branch_create"),port=fullPort() as LocalDeliveryPort&{push?:()=>void};let gets=0;Object.defineProperty(port,"createBranch",{enumerable:true,get(){gets++;return ()=>({status:"accepted"});}});await assert.rejects(()=>executeLocalBranch(plan,authorizeRepositoryOperation(b),b,port),/exact callbacks/);assert.equal(gets,0);assert.deepEqual(Object.keys(fullPort()).sort(),["commit","createBranch","readBranch","readCommit"]);assert.equal(REPOSITORY_OPERATION_ACTIONS.includes("commit"),true);assert.equal((REPOSITORY_OPERATION_ACTIONS as readonly string[]).includes("checkout"),false);});
