import assert from "node:assert/strict";
import test from "node:test";
import {executeDeliveryInspection,prepareBranchDelivery,prepareDeliveryInspection,SUPPORTED_BRANCH_PATTERN,SUPPORTED_COMMIT_PATTERN} from "../src/delivery/branch-preparation.js";
import {executeLocalBranch,executeNextLocalCommit,prepareLocalDelivery,type ConfirmedLocalDelivery,type LocalDeliveryPort} from "../src/delivery/local-delivery.js";
import {executePrOpen,executePush,prepareRemoteDelivery,type ConfirmedPrPublication} from "../src/delivery/remote-delivery.js";
import {executePrLabelPublication,preparePrLabelPublication,type PrLabelPublicationPort,type PrLabelSnapshot} from "../src/delivery/pr-label-publication.js";
import {authorizeRepositoryOperation,type OperationAttempt,type RepositoryOperationAction,type RepositoryOperationBinding} from "../src/repository/operation-policy.js";

let serial=0;const sha=(c:string)=>`sha256:${c.repeat(64)}`,base=sha("a"),tree=sha("b"),head=sha("c");
const bind=(action:RepositoryOperationAction,sessionId=`labels-${++serial}`,overrides:Partial<RepositoryOperationBinding>={}):RepositoryOperationBinding=>({host:"github.example",owner:"acme",repository:"app",sessionId,actor:"maintainer",action,...overrides});
async function local(labels:readonly string[]=["type:feature"]):Promise<ConfirmedLocalDelivery>{const read=bind("remote_read"),inspection=prepareDeliveryInspection({binding:read,baseBranch:"main",approvedIssueUrl:"https://github.example/acme/app/issues/42",expectedPolicySourceIdentity:"sha256:policy-v1",policyUrl:"https://github.example/acme/app/blob/abc/POLICY.md"}),observed=await executeDeliveryInspection(inspection,authorizeRepositoryOperation(read),read,{read(){return {...inspection.request,host:"github.example",owner:"acme",repository:"app",issueNumber:42,issueState:"open",issueTitle:"Approved",issueLabels:["status:approved"],branchPattern:SUPPORTED_BRANCH_PATTERN,commitPattern:SUPPORTED_COMMIT_PATTERN,permittedTypeLabels:["type:feature"],protectedLabels:["status:review"],templateRequired:false,templateWaived:true,requiredTemplateMarkers:[],requiredChecks:["test","lint"]};}}),branchPlan=prepareBranchDelivery(observed,{repositoryUrl:inspection.request.repositoryUrl,issueUrl:inspection.request.issueUrl,policySourceIdentity:inspection.request.policySourceIdentity,baseBranch:"main",branch:"feat/pr-labels",commits:["feat(delivery): labels"],prTitle:"PR labels",prBody:`Closes ${inspection.request.issueUrl}`,labels,protectedLabelMutations:[]}),plan=prepareLocalDelivery(branchPlan,{baseCommitIdentity:base,candidateTrees:[tree]}),branch=bind("branch_create"),port:LocalDeliveryPort={createBranch(){return {status:"accepted"};},readBranch(_b,p){return {repositoryIdentity:p.repositoryIdentity,worktreeIdentity:p.worktreeIdentity,branch:p.branch,headCommitIdentity:p.baseCommitIdentity};},commit(){return {status:"accepted"};},readCommit(_b,p){return {...p,commitIdentity:head};}},progress=await executeLocalBranch(plan,authorizeRepositoryOperation(branch),branch,port),commit=bind("commit"),final=await executeNextLocalCommit(progress as never,authorizeRepositoryOperation(commit),commit,port);return final as ConfirmedLocalDelivery;}
async function publication(labels:readonly string[]=["type:feature"]){const plan=prepareRemoteDelivery(await local(labels)),push=bind("push"),pushed=await executePush(plan,authorizeRepositoryOperation(push),push,{push(){return {status:"accepted"};},readPush(_b,p){return {...p};}}),opened=bind("pr_open",`pr-${++serial}`),pr=await executePrOpen(pushed as never,authorizeRepositoryOperation(opened),opened,{openPr(){return {status:"accepted"};},readPr(_b,p){return {repositoryUrl:p.repositoryUrl,prUrl:`${p.repositoryUrl}/pull/7`,number:7,state:"open",baseBranch:p.baseBranch,headBranch:p.headBranch,title:p.title,body:p.body,headCommitIdentity:p.expectedHeadCommitIdentity,issueUrl:p.issueUrl,policySourceIdentity:p.policySourceIdentity,labels:[]};}});return {pr:pr as ConfirmedPrPublication,opened};}
const prepare=async(input:Record<string,unknown>={})=>{const {pr,opened}=await publication();return {pr,opened,plan:preparePrLabelPublication(pr,{protectedLabels:["status:review","size:exception"],actorPermission:"MAINTAIN",...input} as never)};};
const snap=(plan:Awaited<ReturnType<typeof prepare>>["plan"],overrides:Partial<PrLabelSnapshot>={}):PrLabelSnapshot=>({repositoryUrl:plan.repositoryUrl,prUrl:plan.prUrl,number:plan.number,state:"open",baseBranch:plan.baseBranch,headBranch:plan.headBranch,title:plan.title,body:plan.body,headCommitIdentity:plan.headCommitIdentity,issueUrl:plan.issueUrl,policySourceIdentity:plan.policySourceIdentity,labels:["type:bug","status:review","keep"],requiredChecks:["lint","test"],successfulChecks:["test"],...overrides});
function fixture(plan:Awaited<ReturnType<typeof prepare>>["plan"],attempt:OperationAttempt={status:"accepted"},final?:PrLabelSnapshot){const read=bind("remote_read",plan.sessionId,{host:plan.host,owner:plan.owner,repository:plan.repository,actor:plan.actor}),label=bind("label_mutate",plan.sessionId,{host:plan.host,owner:plan.owner,repository:plan.repository,actor:plan.actor}),calls:{kind:string;args:unknown[]}[]=[],baseline=snap(plan);let reads=0;const port:PrLabelPublicationPort={read(...args){calls.push({kind:"read",args});return reads++===0?baseline:final??snap(plan,{labels:["keep","type:feature"],successfulChecks:["test"]});},label(...args){calls.push({kind:"label",args});return attempt;}};return {read,label,calls,port,baseline};}
const run=async(f:ReturnType<typeof fixture>,plan:Awaited<ReturnType<typeof prepare>>["plan"])=>executePrLabelPublication(plan,authorizeRepositoryOperation(f.read),authorizeRepositoryOperation(f.label),{read:f.read,label:f.label},f.port);

test("prepares immutable exact C3b evidence and rejects forged or reused C3a publication",async()=>{const {pr,plan}=await prepare(),before=structuredClone(pr);assert.equal(Object.isFrozen(plan)&&Object.isFrozen(plan.pendingLabels)&&Object.isFrozen(plan.protectedLabels)&&Object.isFrozen(plan.requiredChecks),true);assert.deepEqual(plan.pendingLabels,["type:feature"]);assert.deepEqual(plan.requiredChecks,["test","lint"]);assert.equal("credential" in plan||"mergeReady" in plan,false);assert.deepEqual(pr,before);assert.throws(()=>preparePrLabelPublication(pr,{protectedLabels:[],actorPermission:"WRITE"}),/already claimed/);assert.throws(()=>preparePrLabelPublication({...pr} as never,{protectedLabels:[],actorPermission:"WRITE"}),/genuine/);});

test("requires exact plain policy input and protected permission plus size rationale",async()=>{for(const input of [{protectedLabels:[],actorPermission:"WRITE",extra:true},{protectedLabels:["e\u0301"],actorPermission:"WRITE"},{protectedLabels:["X","x"],actorPermission:"WRITE"},{protectedLabels:[],actorPermission:"OWNER"}]){const {pr}=await publication();assert.throws(()=>preparePrLabelPublication(pr,input as never),/exact plain/);}const denied=await publication();assert.throws(()=>preparePrLabelPublication(denied.pr,{protectedLabels:["type:feature"],actorPermission:"WRITE"}),/permission/);const missing=await publication(["type:feature","size:exception"]);assert.throws(()=>preparePrLabelPublication(missing.pr,{protectedLabels:["size:exception"],actorPermission:"MAINTAIN"}),/rationale/);const allowed=await publication(["type:feature","size:exception"]),plan=preparePrLabelPublication(allowed.pr,{protectedLabels:["size:exception"],actorPermission:"MAINTAIN",sizeExceptionRationale:"Reviewable split is not possible"});assert.deepEqual(plan.pendingLabels,["type:feature","size:exception"]);});

test("performs one conditional combined mutation and readback while preserving unrelated labels",async()=>{const {plan}=await prepare(),f=fixture(plan),result=await run(f,plan);assert.equal(result.classification,"confirmed");assert.deepEqual(f.calls.map(x=>x.kind),["read","label","read"]);const payload=f.calls[1]!.args[1] as Record<string,unknown>;assert.deepEqual(payload.add,["type:feature"]);assert.deepEqual(payload.remove,["status:review","type:bug"]);assert.match(payload.baselineSnapshotHash as string,/^sha256:[a-f0-9]{64}$/u);assert.equal(Object.isFrozen(payload)&&Object.isFrozen(payload.add)&&Object.isFrozen(payload.remove),true);assert.deepEqual(result.classification==="confirmed"&&result.labels,["keep","type:feature"]);assert.deepEqual(result.classification==="confirmed"&&result.missingChecks,["lint"]);assert.equal(result.mergeAuthority,"pending");assert.equal("mergeReady" in result||"deliveryAuthorized" in result,false);});

test("consumes plan before binding, authority, or callbacks and binds exact session/repository/actor/actions",async()=>{for(const overrides of [{read:{action:"push"}},{label:{action:"merge"}},{read:{sessionId:"other"}},{label:{repository:"other"}},{label:{actor:"other"}}]){const {plan}=await prepare(),f=fixture(plan),read={...f.read,...overrides.read} as RepositoryOperationBinding,label={...f.label,...overrides.label} as RepositoryOperationBinding;await assert.rejects(()=>executePrLabelPublication(plan,authorizeRepositoryOperation(read),authorizeRepositoryOperation(label),{read,label},f.port),/binding/);assert.deepEqual(f.calls,[]);await assert.rejects(()=>executePrLabelPublication(plan,{} as never,{} as never,{read,label},f.port),/consumed/);} });

test("pre-read failure, mismatch, malformed shape, URL, checks, or subset performs zero mutations",async()=>{for(const change of ["throw","target","extra","url","duplicate","checkDuplicate","nfc","required","requiredCase","subset","successfulCase"]){const {plan}=await prepare(),f=fixture(plan),bad={...f.port,read(...args:Parameters<PrLabelPublicationPort["read"]>){f.calls.push({kind:"read",args});if(change==="throw")throw new Error("SECRET");const value=snap(plan,change==="target"?{number:8}:change==="url"?{prUrl:`https://user:pass@github.example/acme/app/pull/7?x=1#h`}:change==="duplicate"?{labels:["X","x"]}:change==="checkDuplicate"?{requiredChecks:["test","TEST"]}:change==="nfc"?{labels:["e\u0301"]}:change==="required"?{requiredChecks:["test"]}:change==="requiredCase"?{requiredChecks:["TEST","lint"]}:change==="subset"?{successfulChecks:["other"]}:change==="successfulCase"?{successfulChecks:["TEST"]}:{});return change==="extra"?{...value,extra:true} as never:value;}};const result=await executePrLabelPublication(plan,authorizeRepositoryOperation(f.read),authorizeRepositoryOperation(f.label),{read:f.read,label:f.label},bad);assert.equal(result.classification,"unknown");assert.equal(f.calls.some(x=>x.kind==="label"),false);assert.equal(JSON.stringify(result).includes("SECRET"),false);} });

test("rejects every noncanonical PR URL and inherited, symbol, or accessor snapshots",async()=>{for(const prUrl of ["http://github.example/acme/app/pull/7","https://github.example:443/acme/app/pull/7","https://github.example/acme/app/a/../pull/7","https://github.example/acme/app/pull/7?x=1","https://github.example/acme/app/pull/7#x"]){const {plan}=await prepare(),f=fixture(plan),port={...f.port,read(){return snap(plan,{prUrl});}},result=await executePrLabelPublication(plan,authorizeRepositoryOperation(f.read),authorizeRepositoryOperation(f.label),{read:f.read,label:f.label},port);assert.equal(result.classification,"unknown");}let gets=0;for(const kind of ["inherited","symbol","accessor"]){const {plan}=await prepare(),f=fixture(plan),base=snap(plan),raw=kind==="inherited"?Object.assign(Object.create({extra:true}),base):kind==="symbol"?{...base,[Symbol("extra")]:true}:{...base};if(kind==="accessor")Object.defineProperty(raw,"title",{enumerable:true,get(){gets++;return plan.title;}});const port={...f.port,read(){return raw as PrLabelSnapshot;}},result=await executePrLabelPublication(plan,authorizeRepositoryOperation(f.read),authorizeRepositoryOperation(f.label),{read:f.read,label:f.label},port);assert.equal(result.classification,"unknown");assert.equal(f.calls.some(x=>x.kind==="label"),false);}assert.equal(gets,0);});

test("classifies rejection unchanged as no_write and every ambiguity without exact final state as unknown",async()=>{for(const [attempt,final,expected] of [[{status:"rejected"},"baseline","no_write"],[{status:"accepted"},"baseline","unknown"],[{status:"rejected",reasonCode:"stale_baseline"},"baseline","unknown"],[{status:"accepted"},"drift","unknown"],[{status:"accepted"},"malformed","unknown"],[{status:"ambiguous",reasonCode:"http_5xx"},"drift","unknown"]] as const){const {plan}=await prepare(),baseSnap=snap(plan),observed=final==="baseline"?baseSnap:final==="drift"?snap(plan,{labels:["drift"]}):{...snap(plan,{labels:["keep","type:feature"]}),extra:true} as never,f=fixture(plan,attempt,observed),result=await run(f,plan);assert.equal(result.classification,expected);assert.deepEqual(f.calls.map(x=>x.kind),["read","label","read"]);assert.equal(result.mergeAuthority,"stopped");}});

test("case-only required or successful check drift cannot confirm",async()=>{for(const kind of ["required","successful"]){const {plan}=await prepare(),observed=snap(plan,{labels:["keep","type:feature"],...(kind==="required"?{requiredChecks:["TEST","lint"],successfulChecks:[]}:{successfulChecks:["TEST"]})}),f=fixture(plan,{status:"accepted"},observed),result=await run(f,plan);assert.equal(result.classification,"unknown");assert.deepEqual(f.calls.map(x=>x.kind),["read","label","read"]);}});

test("transport throw or timeout confirms only from exact post-read and reports exact check evidence",async()=>{for(const throwing of [true,false]){const {plan}=await prepare(),f=fixture(plan,throwing?{status:"ambiguous"}:{status:"ambiguous",reasonCode:"timeout"},snap(plan,{labels:["type:feature","keep"],successfulChecks:["lint","test"]}));if(throwing)f.port={...f.port,label(...args){f.calls.push({kind:"label",args});throw new Error("SECRET");}};const result=await run(f,plan);assert.equal(result.classification,"confirmed");assert.deepEqual(result.classification==="confirmed"&&result.requiredChecks,["test","lint"]);assert.deepEqual(result.classification==="confirmed"&&result.successfulChecks,["lint","test"]);assert.deepEqual(result.classification==="confirmed"&&result.missingChecks,[]);assert.equal(JSON.stringify(result).includes("SECRET"),false);}const {plan}=await prepare(),f=fixture(plan);let reads=0;f.port={...f.port,read(...args){f.calls.push({kind:"read",args});if(reads++)throw new Error("SECRET readback");return f.baseline;}};const unknown=await run(f,plan);assert.equal(unknown.classification,"unknown");assert.deepEqual(f.calls.map(x=>x.kind),["read","label","read"]);assert.equal(JSON.stringify(unknown).includes("SECRET"),false);});

test("ports expose no merge callback and caller snapshots and input remain unchanged",async()=>{const {pr}=await publication(),input={protectedLabels:["status:review"],actorPermission:"MAINTAIN" as const},before=structuredClone(input),plan=preparePrLabelPublication(pr,input),f=fixture(plan),baseline=structuredClone(f.baseline);await run(f,plan);assert.deepEqual(input,before);assert.deepEqual(f.baseline,baseline);assert.deepEqual(Object.keys(f.port).sort(),["label","read"]);const fresh=await prepare(),extra={...fixture(fresh.plan).port,merge(){return {status:"accepted"};}};const fx=fixture(fresh.plan);await assert.rejects(()=>executePrLabelPublication(fresh.plan,authorizeRepositoryOperation(fx.read),authorizeRepositoryOperation(fx.label),{read:fx.read,label:fx.label},extra),/exact callbacks/);});
