import assert from "node:assert/strict";
import test from "node:test";
import {executeDeliveryInspection,prepareBranchDelivery,prepareDeliveryInspection,SUPPORTED_BRANCH_PATTERN,SUPPORTED_COMMIT_PATTERN} from "../src/delivery/branch-preparation.js";
import {executeLocalBranch,executeNextLocalCommit,prepareLocalDelivery,type ConfirmedLocalDelivery,type LocalDeliveryPort} from "../src/delivery/local-delivery.js";
import {executePrOpen,executePush,prepareRemoteDelivery,type PrOpenPayload,type PrOpenPort,type PrSnapshot,type PushPort} from "../src/delivery/remote-delivery.js";
import {authorizeRepositoryOperation,type RepositoryOperationBinding} from "../src/repository/operation-policy.js";

let serial=0;const sha=(c:string)=>`sha256:${c.repeat(64)}`,base=sha("a"),tree=sha("b"),head=sha("c");
const bind=(action:RepositoryOperationBinding["action"],overrides:Partial<RepositoryOperationBinding>={}):RepositoryOperationBinding=>({host:"github.example",owner:"acme",repository:"app",sessionId:`remote-${++serial}`,actor:"maintainer",action,...overrides});
async function local():Promise<ConfirmedLocalDelivery>{const read=bind("remote_read"),inspection=prepareDeliveryInspection({binding:read,baseBranch:"main",approvedIssueUrl:"https://github.example/acme/app/issues/42",expectedPolicySourceIdentity:"sha256:policy-v1",policyUrl:"https://github.example/acme/app/blob/abc/POLICY.md"}),observed=await executeDeliveryInspection(inspection,authorizeRepositoryOperation(read),read,{read(){return {...inspection.request,host:"github.example",owner:"acme",repository:"app",issueNumber:42,issueState:"open",issueTitle:"Approved",issueLabels:["status:approved"],branchPattern:SUPPORTED_BRANCH_PATTERN,commitPattern:SUPPORTED_COMMIT_PATTERN,permittedTypeLabels:["type:feature"],protectedLabels:["status:approved"],templateRequired:false,templateWaived:true,requiredTemplateMarkers:[],requiredChecks:["test"]};}}),branchPlan=prepareBranchDelivery(observed,{repositoryUrl:inspection.request.repositoryUrl,issueUrl:inspection.request.issueUrl,policySourceIdentity:inspection.request.policySourceIdentity,baseBranch:"main",branch:"feat/remote-delivery",commits:["feat(delivery): remote"],prTitle:"Remote delivery",prBody:`Closes ${inspection.request.issueUrl}`,labels:["type:feature"],protectedLabelMutations:[]}),plan=prepareLocalDelivery(branchPlan,{baseCommitIdentity:base,candidateTrees:[tree]}),branch=bind("branch_create"),port:LocalDeliveryPort={createBranch(){return {status:"accepted"};},readBranch(_b,p){return {repositoryIdentity:p.repositoryIdentity,worktreeIdentity:p.worktreeIdentity,branch:p.branch,headCommitIdentity:p.baseCommitIdentity};},commit(){return {status:"accepted"};},readCommit(_b,p){return {repositoryIdentity:p.repositoryIdentity,worktreeIdentity:p.worktreeIdentity,branch:p.branch,commitIdentity:head,message:p.message,parentCommitIdentity:p.parentCommitIdentity,treeIdentity:p.treeIdentity};}},progress=await executeLocalBranch(plan,authorizeRepositoryOperation(branch),branch,port),commit=bind("commit"),final=await executeNextLocalCommit(progress as never,authorizeRepositoryOperation(commit),commit,port);assert.equal(final.classification,"confirmed");return final as ConfirmedLocalDelivery;}
const pushPort=(overrides:Partial<PushPort>={}):PushPort=>({push(){return {status:"accepted"};},readPush(_b,p){return {...p};},...overrides});
const snapshot=(p:PrOpenPayload,overrides:Partial<PrSnapshot>={}):PrSnapshot=>({repositoryUrl:p.repositoryUrl,prUrl:`${p.repositoryUrl}/pull/7`,number:7,state:"open",baseBranch:p.baseBranch,headBranch:p.headBranch,title:p.title,body:p.body,headCommitIdentity:p.expectedHeadCommitIdentity,issueUrl:p.issueUrl,policySourceIdentity:p.policySourceIdentity,labels:[...p.initialLabels],...overrides});
const prPort=(overrides:Partial<PrOpenPort>={}):PrOpenPort=>({openPr(){return {status:"accepted"};},readPr(_b,p){return snapshot(p);},...overrides});
async function pushed(port=pushPort()){const plan=prepareRemoteDelivery(await local()),binding=bind("push"),outcome=await executePush(plan,authorizeRepositoryOperation(binding),binding,port);return {plan,binding,outcome};}

test("publishes one exact immutable push then one exact immutable PR",async()=>{const transcript:unknown[][]=[],{outcome}=await pushed(pushPort({push(...args){transcript.push(["push",...args]);return {status:"accepted"};},readPush(...args){transcript.push(["push-read",...args]);return {...args[1]};}}));assert.equal(outcome.classification,"confirmed");const b=bind("pr_open"),pr=await executePrOpen(outcome as never,authorizeRepositoryOperation(b),b,prPort({openPr(...args){transcript.push(["pr",...args]);return {status:"accepted"};},readPr(...args){transcript.push(["pr-read",...args]);return snapshot(args[1]);}}));assert.deepEqual(pr,{classification:"confirmed",repositoryUrl:"https://github.example/acme/app",prUrl:"https://github.example/acme/app/pull/7",number:7,state:"open",baseBranch:"main",headBranch:"feat/remote-delivery",headCommitIdentity:head,labels:[]});assert.deepEqual(transcript.map(x=>x[0]),["push","push-read","pr","pr-read"]);for(const row of transcript){assert.equal(Object.isFrozen(row[1]),true);assert.equal(Object.isFrozen(row[2]),true);}assert.deepEqual(transcript[0]![2],{repositoryUrl:"https://github.example/acme/app",localBranch:"feat/remote-delivery",remoteRef:"refs/heads/feat/remote-delivery",headCommitIdentity:head});assert.deepEqual(transcript[2]![2],{repositoryUrl:"https://github.example/acme/app",baseBranch:"main",headBranch:"feat/remote-delivery",title:"Remote delivery",body:"Closes https://github.example/acme/app/issues/42",issueUrl:"https://github.example/acme/app/issues/42",policySourceIdentity:"sha256:policy-v1",expectedHeadCommitIdentity:head,initialLabels:[]});assert.equal(Object.isFrozen((transcript[2]![2] as PrOpenPayload).initialLabels),true);assert.equal(Object.isFrozen(pr)&&Object.isFrozen(pr.labels),true);});

test("requires genuine single-use C2 provenance and consumes plans before target or authority",async()=>{const final=await local(),plan=prepareRemoteDelivery(final),forged={...await local()};assert.equal(Object.isFrozen(plan)&&Object.isFrozen(plan.pendingLabels)&&Object.isFrozen(plan.template)&&Object.isFrozen(plan.template.markers)&&Object.isFrozen(plan.requiredChecks),true);assert.deepEqual(plan.pendingLabels,["type:feature"]);assert.throws(()=>prepareRemoteDelivery(final),/claimed/);assert.throws(()=>prepareRemoteDelivery(forged as never),/genuine/);let calls=0;const wrong=bind("push",{repository:"other"});await assert.rejects(()=>executePush(plan,authorizeRepositoryOperation(wrong),wrong,pushPort({push(){calls++;return {status:"accepted"};}})),/target/);const fresh=bind("push");await assert.rejects(()=>executePush(plan,authorizeRepositoryOperation(fresh),fresh,pushPort({push(){calls++;return {status:"accepted"};}})),/consumed/);assert.equal(calls,0);});

test("rejects wrong actions and session/repository/actor authority mismatches before callbacks",async()=>{for(const kind of ["action","session","repository","actor"]){const plan=prepareRemoteDelivery(await local()),expected=bind(kind==="action"?"pr_open":"push",kind==="repository"?{repository:"other"}:{});let actual=expected;if(kind==="session")actual={...expected,sessionId:"different"};if(kind==="actor")actual={...expected,actor:"different"};const calls:string[]=[];await assert.rejects(()=>executePush(plan,authorizeRepositoryOperation(actual),expected,pushPort({push(){calls.push("push");return {status:"accepted"};},readPush(){calls.push("read");return null;}})));assert.deepEqual(calls,[]);}const {outcome}=await pushed(),expected=bind("push"),calls:string[]=[];await assert.rejects(()=>executePrOpen(outcome as never,authorizeRepositoryOperation(expected),expected,prPort({openPr(){calls.push("open");return {status:"accepted"};},readPr(){calls.push("read");return null;}})),/target/);assert.deepEqual(calls,[]);});

test("classifies push absence, timeout, drift, malformed, and readback failure without leaking reasons",async()=>{for(const [attempt,read,classification] of [[{status:"rejected",reasonCode:"denied"},null,"no_write"],[{status:"accepted"},null,"unknown"],[new Error("timeout SECRET"),"exact","confirmed"],[{status:"accepted"},"drift","unknown"],[{status:"accepted"},"malformed","unknown"],[{status:"rejected"},"malformed","unknown"],[{status:"accepted"},new Error("read SECRET"),"unknown"]] as const){const events:string[]=[],{outcome}=await pushed(pushPort({push(){events.push("push");if(attempt instanceof Error)throw attempt;return attempt;},readPush(_b,p){events.push("read");if(read instanceof Error)throw read;if(read==="exact")return {...p};if(read==="drift")return {...p,headCommitIdentity:base};if(read==="malformed")return {extra:true} as never;return read;}}));assert.equal(outcome.classification,classification);assert.deepEqual(events,["push","read"]);assert.equal(JSON.stringify(outcome).includes("SECRET"),false);if(classification!=="confirmed")await assert.rejects(()=>executePrOpen(outcome as never,authorizeRepositoryOperation(bind("pr_open")),bind("pr_open"),prPort()),/genuine/);}});

test("classifies PR absence, multiplicity, malformed, drift, timeout and readback failure",async()=>{for(const [attempt,read,classification] of [[{status:"rejected"},null,"no_write"],[{status:"accepted"},null,"unknown"],[{status:"accepted"},"multiple","unknown"],[{status:"accepted"},"malformed","unknown"],[{status:"rejected"},"malformed","unknown"],[{status:"accepted"},"drift","unknown"],[new Error("timeout SECRET"),"exact","confirmed"],[{status:"accepted"},new Error("read SECRET"),"unknown"]] as const){const {outcome}=await pushed(),b=bind("pr_open"),result=await executePrOpen(outcome as never,authorizeRepositoryOperation(b),b,prPort({openPr(){if(attempt instanceof Error)throw attempt;return attempt;},readPr(_binding,p){if(read instanceof Error)throw read;if(read==="multiple")return [snapshot(p),snapshot(p,{number:8,prUrl:`${p.repositoryUrl}/pull/8`})];if(read==="malformed")return {extra:true} as never;if(read==="drift")return snapshot(p,{title:"wrong",body:"wrong",issueUrl:`${p.repositoryUrl}/issues/99`,policySourceIdentity:"wrong",headCommitIdentity:base});if(read==="exact")return snapshot(p);return read;}}));assert.equal(result.classification,classification);assert.equal(JSON.stringify(result).includes("SECRET"),false);const fresh=bind("pr_open");let calls=0;await assert.rejects(()=>executePrOpen(outcome as never,authorizeRepositoryOperation(fresh),fresh,prPort({openPr(){calls++;return {status:"accepted"};}})),/consumed/);assert.equal(calls,0);}});

test("treats candidate labels already present during PR open as drift",async()=>{const {outcome}=await pushed(),binding=bind("pr_open"),result=await executePrOpen(outcome as never,authorizeRepositoryOperation(binding),binding,prPort({readPr(_b,p){return snapshot(p,{labels:["type:feature"]});}}));assert.equal(result.classification,"unknown");});

test("rejects noncanonical PR URLs and exact-shape violations as unknown without invoking getters",async()=>{for(const url of ["http://github.example/acme/app/pull/7","https://u:p@github.example/acme/app/pull/7","https://github.example:443/acme/app/pull/7","https://GITHUB.example/acme/app/pull/7","https://github.example/acme/app/a/../pull/7","https://github.example/acme/app/pull/7?q=1","https://github.example/acme/app/pull/7#x","https://github.example/ACME/app/pull/7"]){const {outcome}=await pushed(),b=bind("pr_open"),result=await executePrOpen(outcome as never,authorizeRepositoryOperation(b),b,prPort({readPr(_binding,p){return snapshot(p,{prUrl:url});}}));assert.equal(result.classification,"unknown",url);}const {outcome}=await pushed(),b=bind("pr_open");let gets=0;const raw=snapshot({repositoryUrl:"https://github.example/acme/app",baseBranch:"main",headBranch:"feat/remote-delivery",title:"Remote delivery",body:"Closes https://github.example/acme/app/issues/42",issueUrl:"https://github.example/acme/app/issues/42",policySourceIdentity:"sha256:policy-v1",expectedHeadCommitIdentity:head,initialLabels:[]});Object.defineProperty(raw,"title",{enumerable:true,get(){gets++;return "Remote delivery";}});assert.equal((await executePrOpen(outcome as never,authorizeRepositoryOperation(b),b,prPort({readPr(){return raw as never;}}))).classification,"unknown");assert.equal(gets,0);});

test("callback surfaces exclude label and merge operations and preserve caller inputs",async()=>{const final=await local(),before=structuredClone(final),plan=prepareRemoteDelivery(final);assert.deepEqual(final,before);assert.deepEqual(Object.keys(pushPort()).sort(),["push","readPush"].sort());assert.deepEqual(Object.keys(prPort()).sort(),["openPr","readPr"].sort());const b=bind("push"),extra={...pushPort(),merge(){return {status:"accepted"};}};await assert.rejects(()=>executePush(plan,authorizeRepositoryOperation(b),b,extra),/exact callbacks/);});
