import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {rmSync} from "node:fs";
import test from "node:test";
import type {Candidate} from "../src/core/types.js";
import {decideLifecycleApplicability,tddObligationFor} from "../src/lifecycle/applicability.js";
import {buildOrchestrationPlan} from "../src/orchestration/orchestrator.js";
import {beginNonTddAlternative,type NonTddAlternativePlan} from "../src/test/non-tdd-alternative.js";
import * as alternativeModule from "../src/test/non-tdd-alternative.js";
import {beginStrictTddCycle} from "../src/test/strict-tdd-cycle.js";
import {claimNodeCoverageObservation,executeNodeCoverageObservation} from "../src/test/tdd-observation.js";
import {commitCandidateFiles,gitCandidate} from "./execution-evidence-helper.js";
import {issueOddDecision} from "./helpers/odd-routing.js";

const behaviorPath="src/choice.mjs",testPath="tests/choice.test.mjs",first="accepts yes",second="rejects other",behavior="export function choose(value){if(value==='yes'){return 1;}return 2;}\n",candidateBehavior=`${behavior}// candidate behavior revision\n`,tests=`import test from 'node:test';import assert from 'node:assert/strict';import {choose} from '../src/choice.mjs';test('${first}',()=>assert.equal(choose('yes'),1));test('${second}',()=>assert.equal(choose('no'),2));\n`;
const point=(source:string)=>({behaviorPath,startOffset:behavior.indexOf(source),endOffset:behavior.indexOf(source)+source.length}),plan={reason:"baseline-already-passes",rationale:"The committed baseline already passes every planned behavior case.",decisionPaths:[{caseId:first,points:[point("return 1;")]},{caseId:second,points:[point("return 2;")]}]} as const;
function obligation(base:Candidate){const task="GSP-05C3c",paths=[behaviorPath],decision=issueOddDecision({taskId:task,repository:base.repository,paths,writes:[{path:behaviorPath,changeKind:"behavior"}],testingRequired:true});buildOrchestrationPlan({taskId:task,repository:base.repository,prompt:"apply",candidate:base},decision);return tddObligationFor(decideLifecycleApplicability(decision,{taskIdentity:task,repositoryIdentity:base.repository,candidate:{id:base.id,repository:base.repository,revision:base.revision},explicitMode:"unspecified",affectedSubsystems:["tdd"],expectedPaths:paths,requiredArtifacts:[]}));}
async function setup(candidateFiles:Readonly<Record<string,string>>={[behaviorPath]:candidateBehavior}){const initial=gitCandidate("non-tdd"),baseline=commitCandidateFiles(initial,{[behaviorPath]:behavior,[testPath]:tests}),required=obligation(baseline),controller=beginNonTddAlternative(required,plan),baselineCoverage=await executeNodeCoverageObservation(baseline,[testPath],[first,second],[behaviorPath]),candidate=commitCandidateFiles(baseline,candidateFiles),candidateCoverage=await executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]);return {initial,baseline,required,controller,baselineCoverage,candidate,candidateCoverage};}
const cleanup=(t:test.TestContext,value:{initial:Candidate})=>t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));

 test("verifies baseline and direct-child coverage with exact distinct decision points",async t=>{const value=await setup();cleanup(t,value);const result=value.controller.record(value.baselineCoverage,value.candidate,value.candidateCoverage);assert.equal(result.state,"verified-non-tdd-alternative");assert.equal(result.method,"non-tdd-alternative");assert.deepEqual(result.caseIds,[first,second]);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.binding)&&Object.isFrozen(value.controller)&&Object.isFrozen(value.controller.plan.decisionPaths[0]!.points));assert.equal(value.controller.controllerId,beginId(value.baseline));const encoded=JSON.stringify(result);assert.equal(encoded.match(/\bred\b|strict|tdd completion|evidence admission|lifecycle|phase|mutation|review|release|delivery|authority|callback|stdout|coverage/giu),null);assert.equal("NonTddAlternativeResult" in alternativeModule,false);});
function beginId(base:Candidate){const fresh=obligation(base);const id=beginNonTddAlternative(fresh,plan).controllerId;return id;}

test("baseline failure makes the alternative observation unavailable",async t=>{const initial=gitCandidate("non-tdd-fail"),baseline=commitCandidateFiles(initial,{[behaviorPath]:behavior,[testPath]:tests.replace("1));","0));")});cleanup(t,{initial});await assert.rejects(()=>executeNodeCoverageObservation(baseline,[testPath],[first,second],[behaviorPath]),/clean full test run/);});

test("rejects changed and renamed tests, empty, unrelated, skipped, and merge diffs",async t=>{for(const kind of ["test","rename","empty","unrelated","skipped","merge"] as const){let value=await setup();cleanup(t,value);if(kind!=="test"&&kind!=="unrelated")execFileSync("git",["-C",value.initial.repository,"reset","--hard",value.baseline.revision],{stdio:"ignore"});let candidate:Candidate,paths=[testPath];if(kind==="test")value=await setup({[behaviorPath]:candidateBehavior,[testPath]:`${tests}// changed\n`});else if(kind==="unrelated")value=await setup({[behaviorPath]:candidateBehavior,"src/other.mjs":"export {};\n"});else if(kind==="rename"){execFileSync("git",["-C",value.initial.repository,"mv",testPath,"tests/renamed.test.mjs"]);candidate=commitCandidateFiles(value.baseline,{[behaviorPath]:candidateBehavior});paths=["tests/renamed.test.mjs"];}else if(kind==="empty"){execFileSync("git",["-C",value.initial.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","commit","-q","--allow-empty","-m","empty"]);candidate={...value.baseline,revision:execFileSync("git",["-C",value.initial.repository,"rev-parse","HEAD"],{encoding:"utf8"}).trim()};}else if(kind==="skipped")candidate=commitCandidateFiles(commitCandidateFiles(value.baseline,{"src/middle.mjs":"export {};\n"}),{[behaviorPath]:candidateBehavior});else{const side=commitCandidateFiles(value.baseline,{"src/side.mjs":"export {};\n"});execFileSync("git",["-C",value.initial.repository,"checkout","-q","-b","candidate",value.baseline.revision]);commitCandidateFiles(value.baseline,{[behaviorPath]:candidateBehavior});execFileSync("git",["-C",value.initial.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","merge","-q","--no-ff",side.revision,"-m","merge"]);candidate={...value.baseline,revision:execFileSync("git",["-C",value.initial.repository,"rev-parse","HEAD"],{encoding:"utf8"}).trim()};}if(kind==="test"||kind==="unrelated"){cleanup(t,value);assert.throws(()=>value.controller.record(value.baselineCoverage,value.candidate,value.candidateCoverage),/test blobs|behavior paths/);continue;}const coverage=await executeNodeCoverageObservation(candidate!,paths,[first,second],[behaviorPath]);assert.throws(()=>value.controller.record(value.baselineCoverage,candidate!,coverage),/direct Git parent|nonempty|behavior paths|adapter, ordered tests|rename, copy/);}});

test("deleted tests cannot produce candidate coverage",async t=>{const value=await setup();cleanup(t,value);execFileSync("git",["-C",value.initial.repository,"reset","--hard",value.baseline.revision],{stdio:"ignore"});execFileSync("git",["-C",value.initial.repository,"rm","-q",testPath]);const candidate=commitCandidateFiles(value.baseline,{[behaviorPath]:candidateBehavior});await assert.rejects(()=>executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]),/executed command did not match|clean full test run|coverage output|inspect/i);});

test("rejects wrong bindings, skipped revisions, and unavailable coverage cases",async t=>{for(const kind of ["baseline","candidate","revision"] as const){const value=await setup();cleanup(t,value);if(kind==="baseline")assert.throws(()=>value.controller.record(value.candidateCoverage,value.candidate,value.baselineCoverage),/baseline coverage/);else {const candidate={...value.candidate,...(kind==="candidate"?{id:"wrong"}:{revision:value.baseline.revision})};assert.throws(()=>value.controller.record(value.baselineCoverage,candidate,value.candidateCoverage),/identity mismatch|revision mismatch|direct Git parent|coverage mismatch/);}}const initial=gitCandidate("skip-case"),baseline=commitCandidateFiles(initial,{[behaviorPath]:behavior,[testPath]:tests.replace(`test('${second}'`,`test.skip('${second}'`)});cleanup(t,{initial});await assert.rejects(()=>executeNodeCoverageObservation(baseline,[testPath],[first,second],[behaviorPath]),/clean full test run|skipped or todo/);});

test("rejects uncovered, common-only, identical, and outside vectors",async t=>{const malformed:NonTddAlternativePlan[]=[{...plan,decisionPaths:[{caseId:first,points:[point("return 2;")]},{caseId:second,points:[point("return 1;")]}]},{...plan,decisionPaths:[{caseId:first,points:[point("function choose")]},{caseId:second,points:[point("if(value")]}]},{...plan,decisionPaths:[plan.decisionPaths[0],{caseId:second,points:plan.decisionPaths[0]!.points}]},{...plan,decisionPaths:[{caseId:first,points:[{...point("return 1;"),behaviorPath:"src/outside.mjs"}]},{caseId:second,points:[point("return 2;")]}]}];for(const item of malformed){const initial=gitCandidate("vector");cleanup(t,{initial});const baseline=commitCandidateFiles(initial,{[behaviorPath]:behavior,[testPath]:tests}),required=obligation(baseline);try{const controller=beginNonTddAlternative(required,item),baseCoverage=await executeNodeCoverageObservation(baseline,[testPath],[first,second],[behaviorPath]),candidate=commitCandidateFiles(baseline,{[behaviorPath]:candidateBehavior}),coverage=await executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]);assert.throws(()=>controller.record(baseCoverage,candidate,coverage),/positive coverage|materially distinct/);}catch(error){assert.match(String(error),/vectors must be unique|genuine obligation|offsets are unsafe/);}}});

test("rejects unsupported reason, rationale, malformed and noncanonical plans after burning obligations",()=>{const malformed=[{...plan,reason:"meaningful-red-impossible"},{...plan,rationale:"not  normalized"},{...plan,extra:true},{...plan,decisionPaths:[]},{...plan,decisionPaths:[plan.decisionPaths[1],plan.decisionPaths[0]]},{...plan,decisionPaths:[{caseId:first,points:[{behaviorPath,startOffset:2,endOffset:2}]},plan.decisionPaths[1]]}];for(const item of malformed){const initial=gitCandidate("plan");try{const required=obligation(initial);assert.throws(()=>beginNonTddAlternative(required,item as never),/unsupported|malformed|shape|nonempty|canonical|unsafe/);assert.throws(()=>beginStrictTddCycle(required,{expectedFailingCaseIds:[first],decisionPaths:[plan.decisionPaths[0]],triangulationPolicy:{mode:"not-applicable",reason:"structurally-single-decision-path",rationale:"One path."}}),/already been claimed/);}finally{rmSync(initial.repository,{recursive:true,force:true});}}});

test("obligations are unforgeable, one-use, and mutually exclusive with strict cycles",()=>{const strictPlan={expectedFailingCaseIds:[first],decisionPaths:[plan.decisionPaths[0]],triangulationPolicy:{mode:"not-applicable",reason:"structurally-single-decision-path",rationale:"One path."}} as const;for(const order of ["alternative","strict"]){const initial=gitCandidate(order);try{const required=obligation(initial);assert.throws(()=>beginNonTddAlternative({...required},plan),/not issued/);if(order==="alternative"){beginNonTddAlternative(required,plan);assert.throws(()=>beginStrictTddCycle(required,strictPlan),/already been claimed/);}else{beginStrictTddCycle(required,strictPlan);assert.throws(()=>beginNonTddAlternative(required,plan),/already been claimed/);}}finally{rmSync(initial.repository,{recursive:true,force:true});}}});

test("first record attempt burns controller and both observations; clones, replay, and cross-controller fail",async t=>{const firstValue=await setup(),secondValue=await setup();cleanup(t,firstValue);cleanup(t,secondValue);assert.throws(()=>({...firstValue.controller}).record(firstValue.baselineCoverage,firstValue.candidate,firstValue.candidateCoverage),/exact issued controller/);assert.throws(()=>firstValue.controller.record({...firstValue.baselineCoverage},firstValue.candidate,firstValue.candidateCoverage),/not issued/);assert.throws(()=>claimNodeCoverageObservation(firstValue.candidateCoverage),/already been claimed/);assert.throws(()=>firstValue.controller.record(firstValue.baselineCoverage,firstValue.candidate,firstValue.candidateCoverage),/already attempted/);assert.throws(()=>secondValue.controller.record(firstValue.baselineCoverage,secondValue.candidate,secondValue.candidateCoverage),/already been claimed|baseline coverage/);assert.throws(()=>claimNodeCoverageObservation(secondValue.candidateCoverage),/already been claimed/);});
