import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {rmSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import test from "node:test";
import type {Candidate} from "../src/core/types.js";
import {decideLifecycleApplicability,tddObligationFor} from "../src/lifecycle/applicability.js";
import {buildOrchestrationPlan} from "../src/orchestration/orchestrator.js";
import {beginStrictTddCycle,type StrictTddPlan} from "../src/test/strict-tdd-cycle.js";
import * as strictModule from "../src/test/strict-tdd-cycle.js";
import {claimNodeCoverageObservation,executeNodeCoverageObservation,executeNodePassingObservation,executeNodeTestObservation} from "../src/test/tdd-observation.js";
import {commitCandidateFiles,gitCandidate} from "./execution-evidence-helper.js";
import {issueOddDecision} from "./helpers/odd-routing.js";

const behaviorPath="src/branch.mjs",testPath="tests/branch.test.mjs",behavior="export function classify(value){if(value==='yes'){return 1;}return 2;}\n";
const first="accepts yes",second="rejects other",redTest=`import test from 'node:test';import assert from 'node:assert/strict';import {classify} from '../src/branch.mjs';test('${first}',()=>assert.equal(classify('yes'),1));\n`,triTest=`${redTest}test('${second}',()=>assert.equal(classify('no'),2));\n`;
const point=(text:string)=>({behaviorPath,startOffset:behavior.indexOf(text),endOffset:behavior.indexOf(text)+text.length});
const requiredPlan={expectedFailingCaseIds:[first],decisionPaths:[{caseId:first,points:[point("return 1;")]},{caseId:second,points:[point("return 2;")]}],triangulationPolicy:{mode:"required"}} as const;
function obligation(base:Candidate){const task="GSP-05C3b",paths=[behaviorPath],decision=issueOddDecision({taskId:task,repository:base.repository,paths,writes:[{path:behaviorPath,changeKind:"behavior"}],testingRequired:true});buildOrchestrationPlan({taskId:task,repository:base.repository,prompt:"apply",candidate:base},decision);return tddObligationFor(decideLifecycleApplicability(decision,{taskIdentity:task,repositoryIdentity:base.repository,candidate:{id:base.id,repository:base.repository,revision:base.revision},explicitMode:"unspecified",affectedSubsystems:["tdd"],expectedPaths:paths,requiredArtifacts:[]}));}
async function setup(plan:StrictTddPlan=requiredPlan){const initial=gitCandidate("triangulation"),base=commitCandidateFiles(initial,{[behaviorPath]:"export function classify(){return 0;}\n"}),red=commitCandidateFiles(base,{[testPath]:redTest},"RED"),cycle=beginStrictTddCycle(obligation(base),plan),redResult=cycle.recordRed(red,await executeNodeTestObservation(red,[testPath]),await executeNodeTestObservation(red,[testPath])),green=commitCandidateFiles(red,{[behaviorPath]:behavior},"GREEN"),greenResult=cycle.recordGreen(redResult,green,await executeNodePassingObservation(green,[testPath]));return {initial,base,red,green,cycle,redResult,greenResult};}
const cleanup=(t:test.TestContext,value:{initial:Candidate})=>t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));
async function triangulated(){const value=await setup(),candidate=commitCandidateFiles(value.green,{[testPath]:triTest},"TRIANGULATE"),coverage=await executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]);return {...value,candidate,coverage};}

test("records real runner-derived, materially distinct branch coverage",async t=>{const value=await triangulated();cleanup(t,value);const result=value.cycle.recordTriangulation(value.greenResult,value.candidate,value.coverage);assert.equal(result.state,"triangulation-recorded");assert.deepEqual(result.plannedCaseIds,[first,second]);assert.ok(Object.isFrozen(result)&&Object.isFrozen(value.coverage.cases[0]!.behavior[0]!.ranges));assert.equal(JSON.stringify(value.coverage).match(/stdout|stderr|file:|proof|command\W|coverage-/giu),null);assert.equal(JSON.stringify(result).match(/authority|completion|lifecycle|phase|review|delivery/giu),null);});

test("rejects a sparse coverage file before allocating its declared size",async t=>{const base=gitCandidate("coverage-limit");cleanup(t,{initial:base});const fixture=`import test from 'node:test';import {closeSync,ftruncateSync,openSync} from 'node:fs';import {join} from 'node:path';import {classify} from '../src/branch.mjs';const directory=process.env.NODE_V8_COVERAGE;if(!directory)throw new Error('coverage missing');const descriptor=openSync(join(directory,'coverage-000-000-000.json'),'w');ftruncateSync(descriptor,9*1024*1024);closeSync(descriptor);test('${first}',()=>classify('yes'));test('${second}',()=>classify('no'));\n`,candidate=commitCandidateFiles(base,{[behaviorPath]:behavior,[testPath]:fixture});await assert.rejects(()=>executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]),/exceeded its limit/);});

test("coverage admission rejects duplicate, unexpected, absent, failing, skipped, todo, and zero targets",async t=>{const fixtures:Record<string,string>={duplicate:`${triTest}test('${second}',()=>{});\n`,unexpected:`${triTest}test('extra',()=>{});\n`,absent:`${redTest}// absent\n`,failing:`${redTest}test('${second}',()=>assert.fail());\n`,skipped:`${redTest}test('${second}',{skip:true},()=>{});\n`,todo:`${redTest}test.todo('${second}');\n`,zero:"// no tests\n"};for(const [name,content] of Object.entries(fixtures)){const value=await setup();cleanup(t,value);const candidate=commitCandidateFiles(value.green,{[testPath]:content},name);await assert.rejects(()=>executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]),/clean|exactly match|unique|skip|todo|target|tests/i,name);}});

test("coverage admission rejects malformed arrays and missing or outside behavior scripts",async t=>{const value=await setup();cleanup(t,value);const candidate=commitCandidateFiles(value.green,{[testPath]:triTest,"src/unused.mjs":"export const unused=1;\n"});for(const [cases,paths] of [[[first,first],[behaviorPath]],[[first,second],[]],[[first,second],["../outside.mjs"]],[[first,second],["src/unused.mjs"]]] as const)await assert.rejects(()=>executeNodeCoverageObservation(candidate,[testPath],cases,paths),/unique|nonempty|canonical|missing positive/);});

test("rejects identical/common-only vectors and invalid per-case coverage",async t=>{for(const plan of [{...requiredPlan,decisionPaths:[{caseId:first,points:[point("return 1;")]},{caseId:second,points:[point("return 1;")]}]},{...requiredPlan,decisionPaths:[{caseId:first,points:[point("function classify")]},{caseId:second,points:[point("if(value")] }]}] as StrictTddPlan[]){let value:Awaited<ReturnType<typeof setup>>;try{value=await setup(plan);}catch(error){assert.match(String(error),/vectors must be unique/);continue;}cleanup(t,value);const candidate=commitCandidateFiles(value.green,{[testPath]:triTest}),coverage=await executeNodeCoverageObservation(candidate,[testPath],[first,second],[behaviorPath]);assert.throws(()=>value.cycle.recordTriangulation(value.greenResult,candidate,coverage),/decision point|not covered/);}});

test("rejects changed behavior, unrelated, rename, skipped, and merge lineage",async t=>{for(const kind of ["behavior","unrelated","rename","skipped","merge"] as const){const value=await setup();cleanup(t,value);let candidate:Candidate;if(kind==="behavior")candidate=commitCandidateFiles(value.green,{[testPath]:triTest,[behaviorPath]:`${behavior}// changed\n`});else if(kind==="unrelated")candidate=commitCandidateFiles(value.green,{[testPath]:triTest,"src/other.mjs":"export {};\n"});else if(kind==="rename"){execFileSync("git",["-C",value.green.repository,"mv",testPath,"tests/renamed.test.mjs"]);writeFileSync(join(value.green.repository,"tests/renamed.test.mjs"),triTest);candidate=commitCandidateFiles(value.green,{});}else if(kind==="skipped")candidate=commitCandidateFiles(commitCandidateFiles(value.green,{"tests/middle.test.mjs":"// middle\n"}),{[testPath]:triTest});else{const side=commitCandidateFiles(value.green,{"tests/side.test.mjs":"// side\n"});execFileSync("git",["-C",value.green.repository,"checkout","-q","-b","tri",value.green.revision]);commitCandidateFiles(value.green,{[testPath]:triTest});execFileSync("git",["-C",value.green.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","merge","-q","--no-ff",side.revision,"-m","merge"]);candidate={...value.green,revision:execFileSync("git",["-C",value.green.repository,"rev-parse","HEAD"],{encoding:"utf8"}).trim()};}const paths=kind==="rename"?["tests/renamed.test.mjs"]:[testPath];let coverage:Awaited<ReturnType<typeof executeNodeCoverageObservation>>;try{coverage=await executeNodeCoverageObservation(candidate,paths,[first,second],[behaviorPath]);}catch(error){throw new Error(`${kind}: ${String(error)}`);}assert.throws(()=>value.cycle.recordTriangulation(value.greenResult,candidate,coverage),/direct Git parent|only exact GREEN test paths|preserve behavior|rename, copy, or change type/);}});

test("forgery, replay, cross-cycle, and failed attempts burn provenance",async t=>{const firstValue=await triangulated(),secondValue=await triangulated();cleanup(t,firstValue);cleanup(t,secondValue);assert.throws(()=>firstValue.cycle.recordTriangulation({...firstValue.greenResult},firstValue.candidate,firstValue.coverage),/not issued/);assert.throws(()=>claimNodeCoverageObservation(firstValue.coverage),/already been claimed/);assert.throws(()=>firstValue.cycle.recordTriangulation(firstValue.greenResult,firstValue.candidate,firstValue.coverage),/already attempted/);assert.throws(()=>secondValue.cycle.recordTriangulation(firstValue.greenResult,secondValue.candidate,secondValue.coverage),/another strict TDD cycle/);assert.throws(()=>claimNodeCoverageObservation(secondValue.coverage),/already been claimed/);assert.throws(()=>({...secondValue.cycle}).recordTriangulation(secondValue.greenResult,secondValue.candidate,{} as never),/exact issued cycle/);});

test("records exact single-path N/A and excludes multi-path N/A and authority",async t=>{const plan={expectedFailingCaseIds:[first],decisionPaths:[{caseId:first,points:[point("return 1;")]}],triangulationPolicy:{mode:"not-applicable",reason:"structurally-single-decision-path",rationale:"Only one structural path exists."}} as const,value=await setup(plan);cleanup(t,value);const result=value.cycle.recordSinglePathNotApplicable(value.greenResult);assert.equal(result.state,"triangulation-not-applicable");assert.ok(Object.isFrozen(result));assert.equal(JSON.stringify(result).match(/authority|completion|candidate|revision|callback/giu),null);const multi=await setup();cleanup(t,multi);assert.throws(()=>multi.cycle.recordSinglePathNotApplicable(multi.greenResult),/not allowed/);assert.throws(()=>multi.cycle.recordSinglePathNotApplicable(multi.greenResult),/already attempted/);assert.equal("StrictTriangulationResult" in strictModule,false);});
