import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {renameSync,rmSync,writeFileSync} from "node:fs";
import {join} from "node:path";
import test from "node:test";
import type {Candidate} from "../src/core/types.js";
import {decideLifecycleApplicability,tddObligationFor} from "../src/lifecycle/applicability.js";
import {buildOrchestrationPlan} from "../src/orchestration/orchestrator.js";
import {beginStrictTddCycle,claimStrictTddCompletion,type StrictTddPlan} from "../src/test/strict-tdd-cycle.js";
import {claimNodeCoverageObservation,executeNodeCoverageObservation,executeNodePassingObservation,executeNodeTestObservation} from "../src/test/tdd-observation.js";
import {commitCandidateFiles,gitCandidate} from "./execution-evidence-helper.js";
import {issueOddDecision} from "./helpers/odd-routing.js";

const behaviorPath="src/classify.mjs",testPath="tests/classify.test.mjs",first="accepts yes",second="rejects other";
const behavior="export function classify(value){if(value==='yes'){return 1;}return 2;}\n",baseBehavior="export function classify(){return 0;}\n";
const oneTest=`import test from 'node:test';import assert from 'node:assert/strict';import {classify} from '../src/classify.mjs';test('${first}',()=>assert.equal(classify('yes'),1));\n`;
const twoTests=`${oneTest}test('${second}',()=>assert.equal(classify('no'),2));\n`;
const point=(text:string)=>({behaviorPath,startOffset:behavior.indexOf(text),endOffset:behavior.indexOf(text)+text.length});
const required={expectedFailingCaseIds:[first],decisionPaths:[{caseId:first,points:[point("return 1;")]},{caseId:second,points:[point("return 2;")]}],triangulationPolicy:{mode:"required"}} as const;
const single={expectedFailingCaseIds:[first],decisionPaths:[{caseId:first,points:[point("return 1;")]}],triangulationPolicy:{mode:"not-applicable",reason:"structurally-single-decision-path",rationale:"Only one structural path exists."}} as const;
function obligation(base:Candidate){const task="GSP-05C4a",decision=issueOddDecision({taskId:task,repository:base.repository,paths:[behaviorPath],writes:[{path:behaviorPath,changeKind:"behavior"}],testingRequired:true});buildOrchestrationPlan({taskId:task,repository:base.repository,prompt:"apply",candidate:base},decision);return tddObligationFor(decideLifecycleApplicability(decision,{taskIdentity:task,repositoryIdentity:base.repository,candidate:{id:base.id,repository:base.repository,revision:base.revision},explicitMode:"unspecified",affectedSubsystems:["tdd"],expectedPaths:[behaviorPath],requiredArtifacts:[]}));}
async function setup(plan:StrictTddPlan=required){const initial=gitCandidate("completion"),base=commitCandidateFiles(initial,{[behaviorPath]:baseBehavior,"src/other.mjs":"export const other=1;\n"}),red=commitCandidateFiles(base,{[testPath]:oneTest},"RED"),cycle=beginStrictTddCycle(obligation(base),plan),redResult=cycle.recordRed(red,await executeNodeTestObservation(red,[testPath]),await executeNodeTestObservation(red,[testPath])),green=commitCandidateFiles(red,{[behaviorPath]:behavior},"GREEN"),greenResult=cycle.recordGreen(redResult,green,await executeNodePassingObservation(green,[testPath]));if(plan.triangulationPolicy.mode==="not-applicable")return {initial,base,red,green,cycle,terminal:cycle.recordSinglePathNotApplicable(greenResult),cases:[first]};const terminalCandidate=commitCandidateFiles(green,{[testPath]:twoTests},"TRIANGULATE"),coverage=await executeNodeCoverageObservation(terminalCandidate,[testPath],[first,second],[behaviorPath]),terminal=cycle.recordTriangulation(greenResult,terminalCandidate,coverage);return {initial,base,red,green,cycle,terminal,terminalCandidate,triangulationCoverage:coverage,cases:[first,second]};}
const cleanup=(t:test.TestContext,value:{initial:Candidate})=>t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));
const revision=(candidate:Candidate)=>execFileSync("git",["-C",candidate.repository,"rev-parse","HEAD"],{encoding:"utf8"}).trim();
function emptyChild(candidate:Candidate){execFileSync("git",["-C",candidate.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","commit","-q","--allow-empty","-m","empty"]);return {...candidate,revision:revision(candidate)};}
async function freshCoverage(value:Awaited<ReturnType<typeof setup>>,candidate:Candidate){return executeNodeCoverageObservation(candidate,[testPath],value.cases,[behaviorPath]);}

for(const mode of ["required","single"] as const)test(`records performed refactoring after ${mode} terminal`,async t=>{const value=await setup(mode==="required"?required:single);cleanup(t,value);const terminalCandidate="terminalCandidate" in value?value.terminalCandidate:value.green,final=commitCandidateFiles(terminalCandidate,{[behaviorPath]:`${behavior}// clearer without changing behavior\n`},"REFACTOR"),completion=value.cycle.recordRefactorPerformed(value.terminal,final,await freshCoverage(value,final));assert.deepEqual(completion,{state:"strict-completion",refactor:"performed",requirementId:value.cycle.requirementId,planHash:value.cycle.planHash,cycleId:value.cycle.cycleId,baselineRevision:value.base.revision,redRevision:value.red.revision,greenRevision:value.green.revision,terminalRevision:terminalCandidate.revision,finalRevision:final.revision,candidate:{id:final.id,repository:final.repository},cases:value.cases});assert.ok(Object.isFrozen(completion)&&Object.isFrozen(completion.candidate)&&Object.isFrozen(completion.cases));const facts=claimStrictTddCompletion(completion);assert.equal(facts.finalRevision,final.revision);assert.deepEqual(facts.plannedCaseIds,value.cases);assert.throws(()=>claimStrictTddCompletion(completion),/already been claimed/);assert.throws(()=>claimStrictTddCompletion({...completion}),/not issued/);assert.equal(JSON.stringify(completion).match(/evidence|lifecycle|phase|mutation|review|release|delivery|authority|callback|stdout|stderr|coverage/giu),null);});

for(const mode of ["required","single"] as const)test(`records explicitly unnecessary refactoring after ${mode} terminal`,async t=>{const value=await setup(mode==="required"?required:single);cleanup(t,value);const candidate="terminalCandidate" in value?value.terminalCandidate:value.green,completion=value.cycle.recordRefactorNotNeeded(value.terminal,await freshCoverage(value,candidate),"Structure is already minimal.");assert.equal(completion.refactor,"not-needed");assert.equal(completion.finalRevision,candidate.revision);assert.equal(completion.terminalRevision,candidate.revision);assert.equal(completion.rationale,"Structure is already minimal.");assert.equal(revision(candidate),candidate.revision);});

test("rejects missing or forged terminals and burns genuine coverage before validation",async t=>{const value=await setup(single);cleanup(t,value);const coverage=await freshCoverage(value,value.green);assert.throws(()=>value.cycle.recordRefactorNotNeeded({...value.terminal},coverage,"Needed."),/not issued/);assert.throws(()=>claimNodeCoverageObservation(coverage),/already been claimed/);const fresh=await freshCoverage(value,value.green);assert.throws(()=>value.cycle.recordRefactorNotNeeded(value.terminal,fresh,"Needed."),/already attempted/);});

test("rejects changed tests, empty, test-only, unrelated, and rename refactor diffs",async t=>{for(const kind of ["tests","empty","test-only","unrelated","rename"] as const){const value=await setup(required);cleanup(t,value);const terminal=value.terminalCandidate!;let candidate:Candidate;if(kind==="tests")candidate=commitCandidateFiles(terminal,{[testPath]:`${twoTests}// changed\n`,[behaviorPath]:`${behavior}// refactor\n`});else if(kind==="empty")candidate=emptyChild(terminal);else if(kind==="test-only")candidate=commitCandidateFiles(terminal,{[testPath]:`${twoTests}// changed\n`});else if(kind==="unrelated")candidate=commitCandidateFiles(terminal,{"src/unrelated.mjs":"export {};\n"});else{renameSync(join(terminal.repository,"src/other.mjs"),join(terminal.repository,"src/renamed.mjs"));execFileSync("git",["-C",terminal.repository,"add","."]);execFileSync("git",["-C",terminal.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","commit","-q","-m","rename"]);candidate={...terminal,revision:revision(terminal)};}const coverage=await freshCoverage(value,candidate);assert.throws(()=>value.cycle.recordRefactorPerformed(value.terminal,candidate,coverage),/nonempty|behavior paths|test blobs|rename, copy, or change type/);}});

test("rejects skipped, merge, wrong identity, and mismatched final coverage",async t=>{for(const kind of ["skipped","merge","identity","coverage"] as const){const value=await setup(required);cleanup(t,value);const terminal=value.terminalCandidate!,terminalCoverage=kind==="coverage"?await freshCoverage(value,terminal):undefined,direct=commitCandidateFiles(terminal,{[behaviorPath]:`${behavior}// direct\n`}),directCoverage=await freshCoverage(value,direct);let candidate=direct,coverage=directCoverage;if(kind==="skipped")candidate=commitCandidateFiles(direct,{[behaviorPath]:`${behavior}// skipped\n`});else if(kind==="merge"){execFileSync("git",["-C",terminal.repository,"checkout","-q","-b","side",terminal.revision]);const side=commitCandidateFiles(terminal,{"src/side.mjs":"export {};\n"});execFileSync("git",["-C",terminal.repository,"checkout","-q","-b","merge-refactor",terminal.revision]);commitCandidateFiles(terminal,{[behaviorPath]:`${behavior}// merged\n`});execFileSync("git",["-C",terminal.repository,"-c","user.name=ASEN Test","-c","user.email=test@example.invalid","merge","-q","--no-ff",side.revision,"-m","merge"]);candidate={...terminal,revision:revision(terminal)};coverage=await freshCoverage(value,candidate);}else if(kind==="identity")candidate={...direct,id:"wrong"};else coverage=terminalCoverage!;assert.throws(()=>value.cycle.recordRefactorPerformed(value.terminal,candidate,coverage),/direct Git parent|identity mismatch|coverage observation candidate mismatch/);}});

test("rejects failing, missing-case, and reused coverage observations",async t=>{const c3=await setup(required);cleanup(t,c3);assert.throws(()=>c3.cycle.recordRefactorNotNeeded(c3.terminal,c3.triangulationCoverage!,"Already minimal."),/already been claimed/);const value=await setup(required);cleanup(t,value);await assert.rejects(()=>executeNodeCoverageObservation(value.terminalCandidate!,[testPath],[first],[behaviorPath]),/exactly match/);writeFileSync(join(value.terminalCandidate!.repository,testPath),twoTests.replace("2));","3));"));const dirty={...value.terminalCandidate!,revision:value.terminalCandidate!.revision};await assert.rejects(()=>executeNodeCoverageObservation(dirty,[testPath],[first,second],[behaviorPath]),/exact Git candidate|unchanged tracked files|clean test run/);execFileSync("git",["-C",dirty.repository,"reset","--hard",dirty.revision],{stdio:"ignore"});const coverage=await freshCoverage(value,value.terminalCandidate!);claimNodeCoverageObservation(coverage);assert.throws(()=>value.cycle.recordRefactorNotNeeded(value.terminal,coverage,"Already minimal."),/already been claimed/);});

test("rejects bad rationale, cross-cycle terminals, method copying, and burns first attempts",async t=>{for(const rationale of [""," not trimmed","two  spaces","decomposed e\u0301","bad\nline"]){const value=await setup(single);cleanup(t,value);const coverage=await freshCoverage(value,value.green);assert.throws(()=>value.cycle.recordRefactorNotNeeded(value.terminal,coverage,rationale),/malformed|normalized/);}const one=await setup(single),two=await setup(single),three=await setup(single);cleanup(t,one);cleanup(t,two);cleanup(t,three);const crossCoverage=await freshCoverage(two,two.green);assert.throws(()=>two.cycle.recordRefactorNotNeeded(one.terminal,crossCoverage,"Already minimal."),/another strict TDD cycle/);const copied=three.cycle.recordRefactorNotNeeded,coverage=await freshCoverage(three,three.green);assert.throws(()=>copied(three.terminal,coverage,"Already minimal."),/exact issued cycle/);assert.throws(()=>claimNodeCoverageObservation(coverage),/already been claimed/);});
