import assert from "node:assert/strict";
import {rmSync} from "node:fs";
import test from "node:test";
import type {Candidate} from "../src/core/types.js";
import {decideLifecycleApplicability,tddObligationFor} from "../src/lifecycle/applicability.js";
import {buildOrchestrationPlan} from "../src/orchestration/orchestrator.js";
import {beginStrictTddCycle,claimStrictTddCompletion} from "../src/test/strict-tdd-cycle.js";
import {validateTddCompletionRecord} from "../src/test/tdd-completion-record.js";
import {executeNodeCoverageObservation,executeNodePassingObservation,executeNodeTestObservation} from "../src/test/tdd-observation.js";
import {commitCandidateFiles,gitCandidate} from "./execution-evidence-helper.js";
import {issueOddDecision} from "./helpers/odd-routing.js";

const behaviorPath="src/value.mjs",testPath="tests/value.test.mjs",first="accepts yes",second="rejects other";
const behavior="export function value(input){if(input==='yes'){return 1;}return 2;}\n",baseBehavior="export function value(){return 0;}\n";
const one=`import test from 'node:test';import assert from 'node:assert/strict';import {value} from '../src/value.mjs';test('${first}',()=>assert.equal(value('yes'),1));\n`,two=`${one}test('${second}',()=>assert.equal(value('no'),2));\n`;
const point=(source:string)=>({behaviorPath,startOffset:behavior.indexOf(source),endOffset:behavior.indexOf(source)+source.length});
const required={expectedFailingCaseIds:[first],decisionPaths:[{caseId:first,points:[point("return 1;")]},{caseId:second,points:[point("return 2;")]}],triangulationPolicy:{mode:"required"}} as const;
function obligation(base:Candidate){const task="GSP-05C5a",decision=issueOddDecision({taskId:task,repository:base.repository,paths:[behaviorPath],writes:[{path:behaviorPath,changeKind:"behavior"}],testingRequired:true});buildOrchestrationPlan({taskId:task,repository:base.repository,prompt:"apply",candidate:base},decision);return tddObligationFor(decideLifecycleApplicability(decision,{taskIdentity:task,repositoryIdentity:base.repository,candidate:{id:base.id,repository:base.repository,revision:base.revision},explicitMode:"unspecified",affectedSubsystems:["tdd"],expectedPaths:[behaviorPath],requiredArtifacts:[]}));}
async function strictRecord(){const initial=gitCandidate("completion-record"),baseline=commitCandidateFiles(initial,{[behaviorPath]:baseBehavior}),red=commitCandidateFiles(baseline,{[testPath]:one}),cycle=beginStrictTddCycle(obligation(baseline),required),redResult=cycle.recordRed(red,await executeNodeTestObservation(red,[testPath]),await executeNodeTestObservation(red,[testPath])),green=commitCandidateFiles(red,{[behaviorPath]:behavior}),greenResult=cycle.recordGreen(redResult,green,await executeNodePassingObservation(green,[testPath])),terminal=commitCandidateFiles(green,{[testPath]:two}),terminalResult=cycle.recordTriangulation(greenResult,terminal,await executeNodeCoverageObservation(terminal,[testPath],[first,second],[behaviorPath])),completion=cycle.recordRefactorNotNeeded(terminalResult,await executeNodeCoverageObservation(terminal,[testPath],[first,second],[behaviorPath]),"Structure is already minimal.");return {initial,record:claimStrictTddCompletion(completion).record};}
const clone=<T>(value:T):T=>structuredClone(value);
const set=(record:any,path:string,value:unknown)=>{const parts=path.split("."),copy=clone(record);let target=copy;for(const part of parts.slice(0,-1))target=target[part];target[parts.at(-1)!]=value;return copy;};

test("parses a deeply immutable genuine strict record without minting authority",async t=>{const value=await strictRecord();t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));const parsed=validateTddCompletionRecord(clone(value.record));assert.deepEqual(parsed,value.record);assert.ok(Object.isFrozen(parsed)&&Object.isFrozen(parsed.obligation.candidate)&&Object.isFrozen(parsed.plan.decisionPaths[0]!.points));assert.throws(()=>claimStrictTddCompletion(parsed),/not issued/);assert.equal(JSON.stringify(parsed).match(/authority|callback|stdout|stderr|coverage/giu),null);});

test("rejects strict binding, plan, execution, revision, refactor, and exact-data tampering",async t=>{const value=await strictRecord();t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));const r=value.record,bad:Array<[string,unknown]>=[["obligation.requirementId","0".repeat(64)],["obligation.applicabilityId","0".repeat(64)],["obligation.taskIdentity","bad\nvalue"],["obligation.repositoryIdentity","../escape"],["obligation.candidate.id","changed"],["obligation.candidate.revision",r.revisions.red],["obligation.behaviorPaths.0","../escape"],["plan.planHash","0".repeat(64)],["plan.expectedFailingCaseIds.0",second],["plan.decisionPaths.0.caseId","changed"],["plan.decisionPaths.0.points.0.behaviorPath","../escape"],["plan.decisionPaths.0.points.0.startOffset",-1],["plan.decisionPaths.0.points.0.endOffset",Number.MAX_SAFE_INTEGER+1],["plan.triangulationPolicy.mode","not-applicable"],["execution.cycleId","0".repeat(64)],["execution.adapter","node-test"],["execution.commandFingerprint","not-a-fingerprint"],["execution.testPaths.0","../escape"],["execution.caseIds.0",second],["revisions.baseline",r.revisions.red],["revisions.red",r.revisions.green],["revisions.green",r.revisions.terminal],["revisions.terminal",r.revisions.green],["revisions.final",r.revisions.red],["refactor.mode","performed"],["refactor.rationale",""]];for(const [path,value] of bad)assert.throws(()=>validateTddCompletionRecord(set(r,path,value)),path);const extra={...clone(r),authority:true};assert.throws(()=>validateTddCompletionRecord(extra));const proto=Object.assign(Object.create({}),clone(r));assert.throws(()=>validateTddCompletionRecord(proto));const accessor=clone(r);Object.defineProperty(accessor,"schemaVersion",{enumerable:true,get:()=>1});assert.throws(()=>validateTddCompletionRecord(accessor));});

test("dispatches every record, policy, and refactor union to one exact shape",async t=>{const value=await strictRecord();t.after(()=>rmSync(value.initial.repository,{recursive:true,force:true}));const record=clone(value.record),cases=[{...record,promotionMethod:"verified-non-tdd-alternative",refactor:{mode:"not-needed",rationale:"Extra."}},{...record,plan:{...record.plan,triangulationPolicy:{mode:"required",reason:"structurally-single-decision-path",rationale:"Extra."}}},{...record,refactor:{mode:"performed",rationale:"Extra."}},{...record,plan:{...record.plan,triangulationPolicy:{mode:"not-applicable",reason:"structurally-single-decision-path",rationale:"One path.",extra:true}}},{...record,refactor:{mode:"not-needed",rationale:"Minimal.",extra:true}}];for(const candidate of cases)assert.throws(()=>validateTddCompletionRecord(candidate),/shape is invalid/);let invoked=false;const accessor=clone(record);Object.defineProperty(accessor,"promotionMethod",{enumerable:true,get:()=>{invoked=true;return "strict-completion";}});assert.throws(()=>validateTddCompletionRecord(accessor),/discriminator is invalid/);assert.equal(invoked,false);});
