import test from "node:test";import assert from "node:assert/strict";import path from "node:path";import {groupChanges,recordWorkspaceChange,visibleWorkspaceRows} from "../src/runtime/workspace-attribution.js";
import {mkdtemp,mkdir,realpath,rm} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {PersistentWorkspaceStore,parseWorkspaceFile} from "../src/runtime/workspace-store.js";import authorityExtension,{recordSuccessfulWorkspaceWrite} from "../extensions/authority.js";
const base={path:"src/a.ts",actor:{kind:"agent" as const,id:"worker-1"},sessionId:"s1",projectId:"p1",worktree:path.resolve("repo"),operation:"modify" as const,at:"2026-10-06T00:00:00Z"};
test("workspace attribution binds actor session project and worktree",()=>{const c=recordWorkspaceChange(base);assert.equal(c.actor.id,"worker-1");assert.equal(groupChanges([c]).get("agent:worker-1")?.length,1);});
test("workspace attribution rejects escape/control and renders bounded rows",()=>{assert.throws(()=>recordWorkspaceChange({...base,path:"../x"}),/escapes/);assert.throws(()=>recordWorkspaceChange({...base,actor:{kind:"agent",id:"bad\nactor"}}),/Invalid/);const row=visibleWorkspaceRows([{...base,path:"very/long/path/to/a/file.ts"}],30)[0]!;assert.ok(row.length<=30);});
test("workspace attribution rejects forged actor kinds and incomplete operations",()=>{assert.throws(()=>recordWorkspaceChange({...base,actor:{kind:"admin" as never,id:"u"}}),/actor kind/i);assert.throws(()=>recordWorkspaceChange({...base,operation:"review" as never}),/operation/i);assert.throws(()=>recordWorkspaceChange({...base,path:""}),/path/i);});
test("workspace change paths use portable separators and reject Windows absolute paths",()=>{assert.equal(recordWorkspaceChange({...base,path:"src\\nested\\file.ts"}).path,"src/nested/file.ts");assert.throws(()=>recordWorkspaceChange({...base,path:"C:\\secrets\\token"}),/escapes/);});
test("successful child writes persist exact actor, session, project and worktree attribution",async t=>{
 const root=await mkdtemp(join(tmpdir(),"asen-workspace-attribution-"));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,"src"));const canonicalRoot=await realpath(root),file=join(root,".asen","workspace.json"),authority={repository:root,role:"worker" as const,writeSurfaces:["src"],agentId:"agent-1",sessionId:"session-1"};
 await recordSuccessfulWorkspaceWrite(authority,"write",{path:"src/new.ts"},false,file);await recordSuccessfulWorkspaceWrite(authority,"edit",{path:"src/old.ts"},true,file);
 const store=await PersistentWorkspaceStore.open(file),identity={sessionId:"session-1",projectId:canonicalRoot,worktree:canonicalRoot},changes=await store.list(identity);assert.deepEqual(changes.map(x=>[x.change.path,x.change.operation,x.change.actor.id]),[["src/new.ts","create","agent-1"],["src/old.ts","modify","agent-1"]]);if(process.platform==="win32")assert.equal((await store.list({sessionId:identity.sessionId,projectId:canonicalRoot.toUpperCase(),worktree:canonicalRoot.replace(/\\/g,"/")})).length,2);
 assert.deepEqual(await store.list({sessionId:"session-2",projectId:canonicalRoot,worktree:canonicalRoot}),[]);assert.throws(()=>parseWorkspaceFile('{"schema":"asen.workspace/v1","revision":2,"changes":[]}'),/revision/);
 await assert.rejects(()=>recordSuccessfulWorkspaceWrite(authority,"write",{path:"secrets/token"},false,file),/scope is invalid/);
});

test("Pi authority records only successful writes from the exact authorized tool call",async t=>{
 const root=await mkdtemp(join(tmpdir(),"asen-authority-hook-"));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,"src"));const canonicalRoot=await realpath(root),storeFile=join(root,".asen","workspace.json"),handlers=new Map<string,(event:any)=>unknown>();
 const original=process.env.ASEN_PI_AUTHORITY;process.env.ASEN_PI_AUTHORITY=JSON.stringify({repository:root,role:"worker",writeSurfaces:["src"],agentId:"agent-2",sessionId:"session-2",attributionFile:storeFile});t.after(()=>{if(original===undefined)delete process.env.ASEN_PI_AUTHORITY;else process.env.ASEN_PI_AUTHORITY=original;});
 authorityExtension({on:(name:string,handler:(event:any)=>unknown)=>handlers.set(name,handler),registerCommand:()=>{}} as any);
 const call=handlers.get("tool_call")!,result=handlers.get("tool_result")!;assert.equal(call({toolCallId:"write-1",toolName:"write",input:{path:"src/output.ts"}}),undefined);
 await result({toolCallId:"write-1",toolName:"write",input:{path:"src/output.ts"},isError:false});
 assert.deepEqual((await (await PersistentWorkspaceStore.open(storeFile)).list({sessionId:"session-2",projectId:canonicalRoot,worktree:canonicalRoot})).map(row=>row.change.path),["src/output.ts"]);
 assert.deepEqual(call({toolCallId:"write-2",toolName:"write",input:{path:"secrets/token"}}),{block:true,reason:"ASEN tool authority denied"});
 assert.equal(call({toolCallId:"write-3",toolName:"edit",input:{path:"src/other.ts"}}),undefined);await result({toolCallId:"write-3",toolName:"edit",input:{path:"src/forged.ts"},isError:false});
 assert.deepEqual((await (await PersistentWorkspaceStore.open(storeFile)).list({sessionId:"session-2",projectId:canonicalRoot,worktree:canonicalRoot})).map(row=>row.change.path),["src/output.ts"]);
});
