import {parseRddPolicyBytes} from "./rdd-policy-source.js";
import {RDD_POLICY_LOCATOR,MAX_RDD_POLICY_BYTES,type ParsedRddPolicy,type RddPolicyV1} from "./rdd-policy.js";
import {executeAuthorizedRead,type RepositoryOperationAuthority,type RepositoryOperationBinding} from "../repository/operation-policy.js";

export interface RddRepositoryInspectionInput{readonly binding:RepositoryOperationBinding;readonly repositoryUrl:string;readonly branch:"main";readonly observedMainCommitIdentity:string;readonly expectedMainCommitIdentity:string;readonly issueUrl:string;readonly policyLocator:typeof RDD_POLICY_LOCATOR;}
export interface RddRepositoryInspectionRequest{readonly repositoryUrl:string;readonly branch:"main";readonly observedMainCommitIdentity:string;readonly expectedMainCommitIdentity:string;readonly issueUrl:string;readonly policyLocator:typeof RDD_POLICY_LOCATOR;readonly expectedPolicyContentIdentity:string;}
export interface RddPullRequestAuditRow{readonly number:number;readonly url:string;readonly state:"open"|"closed"|"merged";readonly baseBranch:"main";readonly headBranch:string;readonly headCommitIdentity:string;readonly issueUrl:string;}
export interface RddPullRequestAudit{readonly complete:true;readonly truncated:false;readonly saturated:false;readonly totalCount:number;readonly rows:readonly RddPullRequestAuditRow[];}
export interface RddRepositoryInspectionSnapshot{readonly repositoryUrl:string;readonly branch:"main";readonly observedMainCommitIdentity:string;readonly issueUrl:string;readonly issueNumber:number;readonly issueState:"open";readonly issueLabels:readonly string[];readonly policyLocator:typeof RDD_POLICY_LOCATOR;readonly policyBytes:readonly number[];readonly policyContentIdentity:string;readonly pullRequestAudit:RddPullRequestAudit;}
export interface RddRepositoryInspectionPort{read(binding:RepositoryOperationBinding,request:RddRepositoryInspectionRequest):unknown|Promise<unknown>;}
export interface RddRepositoryInspectionClaim{readonly binding:RepositoryOperationBinding;readonly request:RddRepositoryInspectionRequest;}

interface ClaimState{readonly binding:RepositoryOperationBinding;readonly request:RddRepositoryInspectionRequest;readonly policy:RddPolicyV1;}
const claims=new WeakMap<object,ClaimState>(),consumed=new WeakSet<object>();
const inputKeys=["binding","repositoryUrl","branch","observedMainCommitIdentity","expectedMainCommitIdentity","issueUrl","policyLocator"] as const;
const snapshotKeys=["repositoryUrl","branch","observedMainCommitIdentity","issueUrl","issueNumber","issueState","issueLabels","policyLocator","policyBytes","policyContentIdentity","pullRequestAudit"] as const;
const auditKeys=["complete","truncated","saturated","totalCount","rows"] as const;
const rowKeys=["number","url","state","baseBranch","headBranch","headCommitIdentity","issueUrl"] as const;

function record(value:unknown,keys:readonly string[],noun:string):Record<string,unknown>{
 if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(`${noun} must be exact plain data`);
 const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key))||keys.some(key=>!Object.hasOwn(value,key)))throw new Error(`${noun} shape is invalid`);
 const out:Record<string,unknown>={};for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor?.enumerable||!("value" in descriptor))throw new Error(`${noun} shape is invalid`);out[key]=descriptor.value;}return out;
}
function array(value:unknown,noun:string,limit:number):unknown[]{
 if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype||value.length>limit)throw new Error(`${noun} must be an exact bounded array`);
 const indexes=Array.from({length:value.length},(_,index)=>String(index)),keys=Reflect.ownKeys(value);if(keys.length!==indexes.length+1||keys.some(key=>typeof key!=="string"||(key!=="length"&&!indexes.includes(key)))||indexes.some(key=>!Object.hasOwn(value,key)))throw new Error(`${noun} must be an undecorated dense array`);
 return indexes.map(key=>{const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor?.enumerable||!("value" in descriptor))throw new Error(`${noun} must contain plain data`);return descriptor.value;});
}
function text(value:unknown,noun:string):string{if(typeof value!=="string"||!value||value.trim()!==value||value.normalize("NFC")!==value||/[\p{Cc}\p{Cf}\p{Cs}\p{Zl}\p{Zp}]/u.test(value))throw new Error(`${noun} is malformed`);return value;}
const fold=(value:string)=>value.normalize("NFKC").toLowerCase();
function strings(value:unknown,noun:string,limit=100):string[]{const values=array(value,noun,limit).map(item=>text(item,noun));if(new Set(values.map(fold)).size!==values.length)throw new Error(`${noun} contains duplicate or ambiguous values`);return values;}
function gitIdentity(value:unknown,noun:string):string{const identity=text(value,noun);if(!/^(?:[0-9a-f]{40}|[0-9a-f]{64})$/u.test(identity))throw new Error(`${noun} is not a valid Git identity`);return identity;}
function safeInteger(value:unknown,noun:string,allowZero=false):number{if(typeof value!=="number"||!Number.isSafeInteger(value)||(allowZero?value<0:value<1))throw new Error(`${noun} must be an exact safe integer`);return value;}
function binding(value:unknown):RepositoryOperationBinding{
 const item=record(value,["host","owner","repository","sessionId","actor","action"],"inspection binding");if(item.action!=="remote_read")throw new Error("Inspection binding requires remote_read");
 const structured=(candidate:unknown,noun:string)=>{const result=text(candidate,noun);if(/[\s/\\:@]/u.test(result)||result==="."||result==="..")throw new Error(`inspection binding ${noun} is malformed`);return result;},raw=structured(item.host,"host").toLowerCase(),host=raw.endsWith(".")?raw.slice(0,-1):raw;
 if(!host||raw.endsWith("..")||!host.split(".").every(part=>/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/u.test(part)))throw new Error("inspection binding host is malformed");
 return Object.freeze({host,owner:structured(item.owner,"owner"),repository:structured(item.repository,"repository"),sessionId:structured(item.sessionId,"sessionId"),actor:structured(item.actor,"actor"),action:"remote_read"});
}
function sameBinding(left:RepositoryOperationBinding,right:RepositoryOperationBinding):boolean{return left.host===right.host&&left.owner===right.owner&&left.repository===right.repository&&left.sessionId===right.sessionId&&left.actor===right.actor&&right.action==="remote_read";}
function canonical(value:unknown,state:ClaimState,kind:"repository"|"issue"|"pull",number?:number):string{
 const source=text(value,`${kind} URL`);let url:URL;try{url=new URL(source);}catch{throw new Error(`${kind} URL is not canonical`);}const root=`https://${state.binding.host}/${state.binding.owner}/${state.binding.repository}`,expected=kind==="repository"?root:kind==="issue"?`${root}/issues/${number}`:`${root}/pull/${number}`;
 if(source!==expected||url.href!==source||url.protocol!=="https:"||url.username||url.password||url.port||url.search||url.hash)throw new Error(`${kind} URL does not match the repository target`);return source;
}
function policySource(value:unknown):Readonly<{policy:RddPolicyV1;contentIdentity:string}>{
 const parsed=record(value,["policy","contentIdentity"],"parsed policy source"),policy=record(parsed.policy,["schemaVersion","reviewMode","issueApproval"],"parsed policy"),approval=record(policy.issueApproval,["requiredLabels"],"parsed policy approval"),labels=strings(approval.requiredLabels,"parsed policy required labels",32),identity=text(parsed.contentIdentity,"policy content identity");
 if(policy.schemaVersion!==1||policy.reviewMode!=="enabled"||!/^[0-9a-f]{64}$/u.test(identity))throw new Error("parsed policy source is invalid or disabled");return Object.freeze({contentIdentity:identity,policy:Object.freeze({schemaVersion:1,reviewMode:"enabled",issueApproval:Object.freeze({requiredLabels:Object.freeze(labels)})})});
}
function exactPort(value:unknown):RddRepositoryInspectionPort{const item=record(value,["read"],"inspection port");if(typeof item.read!=="function")throw new Error("inspection port read callback is malformed");return {read:item.read as RddRepositoryInspectionPort["read"]};}
function exactSnapshot(value:unknown,state:ClaimState):RddRepositoryInspectionSnapshot{
 const item=record(value,snapshotKeys,"inspection snapshot"),issueNumber=safeInteger(item.issueNumber,"inspection snapshot issue number");canonical(item.repositoryUrl,state,"repository");canonical(item.issueUrl,state,"issue",issueNumber);
 if(item.repositoryUrl!==state.request.repositoryUrl||item.issueUrl!==state.request.issueUrl||item.branch!=="main"||item.observedMainCommitIdentity!==state.request.observedMainCommitIdentity||item.observedMainCommitIdentity!==state.request.expectedMainCommitIdentity)throw new Error("inspection snapshot target or main drift mismatch");
 if(item.issueState!=="open")throw new Error("inspection issue must be open");const labels=strings(item.issueLabels,"inspection issue labels"),approved=labels.filter(label=>fold(label)==="status:approved");if(approved.length!==1)throw new Error("inspection issue approval is duplicate or missing");for(const required of state.policy.issueApproval.requiredLabels)if(!labels.some(label=>fold(label)===fold(required)))throw new Error("inspection issue is missing a required label");
 if(item.policyLocator!==RDD_POLICY_LOCATOR||item.policyContentIdentity!==state.request.expectedPolicyContentIdentity)throw new Error("inspection policy identity mismatch");const bytes=array(item.policyBytes,"inspection policy bytes",MAX_RDD_POLICY_BYTES).map(byte=>{if(typeof byte!=="number"||!Number.isInteger(byte)||byte<0||byte>255)throw new Error("inspection policy bytes are malformed");return byte;});const parsed=parseRddPolicyBytes(Uint8Array.from(bytes),state.request.expectedPolicyContentIdentity);if(parsed.contentIdentity!==state.request.expectedPolicyContentIdentity||JSON.stringify(parsed.policy)!==JSON.stringify(state.policy))throw new Error("inspection policy source mismatch");
 const audit=record(item.pullRequestAudit,auditKeys,"inspection PR audit"),total=safeInteger(audit.totalCount,"inspection PR audit total",true);if(audit.complete!==true||audit.truncated!==false||audit.saturated!==false)throw new Error("inspection PR audit is incomplete");const rawRows=array(audit.rows,"inspection PR audit rows",1000);if(rawRows.length!==total)throw new Error("inspection PR audit coverage is incomplete");const seenNumbers=new Set<number>(),seenUrls=new Set<string>();const rows=rawRows.map(raw=>{const row=record(raw,rowKeys,"inspection PR audit row"),number=safeInteger(row.number,"inspection PR audit row number");if(seenNumbers.has(number))throw new Error("inspection PR audit row is duplicate or malformed");const url=canonical(row.url,state,"pull",number);if(seenUrls.has(url))throw new Error("inspection PR audit row is duplicate or ambiguous");seenNumbers.add(number);seenUrls.add(url);if(!["open","closed","merged"].includes(row.state as string)||row.baseBranch!=="main"||row.issueUrl!==state.request.issueUrl)throw new Error("inspection PR audit row is malformed");return Object.freeze({number,url,state:row.state as RddPullRequestAuditRow["state"],baseBranch:"main" as const,headBranch:text(row.headBranch,"PR head branch"),headCommitIdentity:gitIdentity(row.headCommitIdentity,"PR head commit identity"),issueUrl:state.request.issueUrl});});
 return Object.freeze({repositoryUrl:state.request.repositoryUrl,branch:"main",observedMainCommitIdentity:state.request.observedMainCommitIdentity,issueUrl:state.request.issueUrl,issueNumber,issueState:"open",issueLabels:Object.freeze(labels),policyLocator:RDD_POLICY_LOCATOR,policyBytes:Object.freeze(bytes),policyContentIdentity:state.request.expectedPolicyContentIdentity,pullRequestAudit:Object.freeze({complete:true,truncated:false,saturated:false,totalCount:total,rows:Object.freeze(rows)})});
}

export function prepareRddRepositoryInspection(input:RddRepositoryInspectionInput,parsedPolicySource:ParsedRddPolicy):RddRepositoryInspectionClaim{
 const item=record(input,inputKeys,"inspection claim"),readBinding=binding(item.binding),source=policySource(parsedPolicySource),state={} as ClaimState,repositoryUrl=`https://${readBinding.host}/${readBinding.owner}/${readBinding.repository}`,observed=gitIdentity(item.observedMainCommitIdentity,"observed main commit identity"),expected=gitIdentity(item.expectedMainCommitIdentity,"expected main commit identity");
 const issueSource=text(item.issueUrl,"issue URL"),issueMatch=new RegExp(`^${repositoryUrl.replace(/[.*+?^${}()|[\]\\]/gu,"\\$&")}/issues/([1-9][0-9]*)$`,"u").exec(issueSource),issueNumber=issueMatch?safeInteger(Number.parseInt(issueMatch[1]!,10),"issue locator number"):undefined;if(issueNumber===undefined)throw new Error("issue URL is not canonical");
 Object.assign(state,{binding:readBinding,policy:source.policy,request:Object.freeze({repositoryUrl,branch:"main",observedMainCommitIdentity:observed,expectedMainCommitIdentity:expected,issueUrl:issueSource,policyLocator:RDD_POLICY_LOCATOR,expectedPolicyContentIdentity:source.contentIdentity})});if(item.repositoryUrl!==repositoryUrl||item.branch!=="main"||item.policyLocator!==RDD_POLICY_LOCATOR||observed!==expected)throw new Error("inspection claim main, policy, repository, or identity is invalid");canonical(issueSource,state,"issue",issueNumber);const claim=Object.freeze({binding:readBinding,request:state.request});claims.set(claim,state);return claim;
}
export async function executeRddRepositoryInspection(claim:RddRepositoryInspectionClaim,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,port:RddRepositoryInspectionPort):Promise<RddRepositoryInspectionSnapshot>{
 const state=typeof claim==="object"&&claim!==null?claims.get(claim):undefined;if(!state)throw new Error("Inspection requires a genuine opaque claim");if(consumed.has(claim))throw new Error("Inspection claim already consumed");consumed.add(claim);const expected=binding(expectedBinding);if(!sameBinding(state.binding,expected))throw new Error("Inspection authority binding mismatch");const reader=exactPort(port),raw=await executeAuthorizedRead(authority,expected,current=>reader.read(current,state.request));return exactSnapshot(raw,state);
}
