import {executeAuthorizedRead,type RepositoryOperationAuthority,type RepositoryOperationBinding} from "../repository/operation-policy.js";

export const SUPPORTED_BRANCH_PATTERN="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)/[a-z0-9]+(?:-[a-z0-9]+)*$";
export const SUPPORTED_COMMIT_PATTERN="^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(?:\\([a-z0-9][a-z0-9-]*\\))?!?: [^\\r\\n]+$";
export interface DeliveryInspectionInput{readonly binding:RepositoryOperationBinding;readonly baseBranch:string;readonly approvedIssueUrl:string;readonly expectedPolicySourceIdentity:string;readonly policyUrl:string;}
export interface DeliveryInspectionRequest{readonly repositoryUrl:string;readonly issueUrl:string;readonly policyUrl:string;readonly baseBranch:string;readonly policySourceIdentity:string;}
export interface DeliveryPolicySnapshot extends DeliveryInspectionRequest{readonly host:string;readonly owner:string;readonly repository:string;readonly issueNumber:number;readonly issueState:"open"|"closed";readonly issueTitle:string;readonly issueLabels:readonly string[];readonly branchPattern:string;readonly commitPattern:string;readonly permittedTypeLabels:readonly string[];readonly protectedLabels:readonly string[];readonly templateRequired:boolean;readonly templateWaived:boolean;readonly requiredTemplateMarkers:readonly string[];readonly requiredChecks:readonly string[];}
export interface DeliveryInspectionPort{read(binding:RepositoryOperationBinding,input:DeliveryInspectionRequest):DeliveryPolicySnapshot|Promise<DeliveryPolicySnapshot>;}
export interface DeliveryInspectionPlan{readonly binding:RepositoryOperationBinding;readonly request:DeliveryInspectionRequest;}
export interface DeliveryInspectionResult extends DeliveryPolicySnapshot{}
export interface BranchDeliveryCandidate{readonly repositoryUrl:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly baseBranch:string;readonly branch:string;readonly commits:readonly string[];readonly prTitle:string;readonly prBody:string;readonly labels:readonly string[];readonly protectedLabelMutations:readonly string[];}
export interface BranchDeliveryPlan{readonly repositoryUrl:string;readonly issueUrl:string;readonly policyUrl:string;readonly policySourceIdentity:string;readonly baseBranch:string;readonly approvedIssue:Readonly<{number:number;title:string;labels:readonly string[]}>;readonly branch:string;readonly commits:readonly string[];readonly prTitle:string;readonly prBody:string;readonly finalLabels:readonly string[];readonly template:Readonly<{required:boolean;waived:boolean;markers:readonly string[]}>;readonly requiredChecks:readonly string[];}

const plans=new WeakSet<object>(),usedPlans=new WeakSet<object>(),results=new WeakMap<object,DeliveryPolicySnapshot>(),usedResults=new WeakSet<object>(),branchPlans=new WeakSet<object>(),claimedBranchPlans=new WeakSet<object>();
const plain=(v:unknown)=>typeof v==="object"&&v!==null&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
function record(value:unknown,keys:readonly string[],noun:string):Record<string,unknown>{
 if(!plain(value))throw new Error(`${noun} must be exact plain data`);const own=Reflect.ownKeys(value as object);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k))||keys.some(k=>!Object.hasOwn(value as object,k)))throw new Error(`${noun} shape is invalid`);
 const out:Record<string,unknown>={};for(const key of keys){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))throw new Error(`${noun} shape is invalid`);out[key]=d.value;}return out;
}
function text(v:unknown,noun:string):string{if(typeof v!=="string"||!v||v.trim()!==v||/[\u0000-\u001f\u007f-\u009f]/u.test(v))throw new Error(`${noun} is malformed`);return v;}
const fold=(v:string)=>v.normalize("NFC").toLocaleLowerCase("en-US");
function strings(v:unknown,noun:string,nonempty=false):string[]{
 if(!Array.isArray(v)||Object.getPrototypeOf(v)!==Array.prototype)throw new Error(`${noun} is malformed`);const own=Reflect.ownKeys(v),indexes=Array.from({length:v.length},(_,i)=>String(i));if(own.some(k=>typeof k!=="string"||(k!=="length"&&!indexes.includes(k)))||indexes.some(k=>!Object.hasOwn(v,k)))throw new Error(`${noun} is malformed`);
 const out=indexes.map(k=>{const d=Object.getOwnPropertyDescriptor(v,k);if(!d?.enumerable||!("value" in d))throw new Error(`${noun} is malformed`);return text(d.value,noun).normalize("NFC");});if(nonempty&&!out.length)throw new Error(`${noun} must not be empty`);if(new Set(out.map(fold)).size!==out.length)throw new Error(`${noun} is duplicate or ambiguous`);return out;
}
function binding(v:unknown):RepositoryOperationBinding{
 const r=record(v,["host","owner","repository","sessionId","actor","action"],"read binding");if(r.action!=="remote_read")throw new Error("Inspection requires remote_read binding");
 const structured=(x:unknown,n:string)=>{const s=text(x,n);if(/[\s/\\:@]/u.test(s)||s==="."||s==="..")throw new Error(`${n} is malformed`);return s;};const raw=structured(r.host,"host").toLowerCase(),host=raw.endsWith(".")?raw.slice(0,-1):raw;if(!host||raw.endsWith("..")||!host.split(".").every(p=>/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/u.test(p)))throw new Error("host is malformed");return Object.freeze({host,owner:structured(r.owner,"owner"),repository:structured(r.repository,"repository"),sessionId:structured(r.sessionId,"sessionId"),actor:structured(r.actor,"actor"),action:"remote_read"});
}
function canonical(value:unknown,b:RepositoryOperationBinding,kind:"repository"|"issue"|"policy"):string{
 const s=text(value,`${kind} URL`);let u:URL;try{u=new URL(s);}catch{throw new Error(`${kind} URL is not canonical`);}if(u.protocol!=="https:"||u.username||u.password||u.port||u.search||u.hash||u.hostname!==b.host)throw new Error(`${kind} URL is not canonical`);
 const root=`/${b.owner}/${b.repository}`,issuePath=u.pathname.slice(root.length),ok=kind==="repository"?u.pathname===root:kind==="issue"?u.pathname.startsWith(root)&&/^\/issues\/[1-9][0-9]*$/u.test(issuePath):u.pathname.startsWith(`${root}/`)&&!u.pathname.includes("//");if(!ok||s!==`https://${b.host}${u.pathname}`)throw new Error(`${kind} URL is not canonical`);return s;
}
function sameBinding(a:RepositoryOperationBinding,b:RepositoryOperationBinding){return a.host===b.host&&a.owner===b.owner&&a.repository===b.repository&&a.sessionId===b.sessionId&&a.actor===b.actor&&b.action==="remote_read";}
const requestKeys=["repositoryUrl","issueUrl","policyUrl","baseBranch","policySourceIdentity"] as const;
const snapshotKeys=[...requestKeys,"host","owner","repository","issueNumber","issueState","issueTitle","issueLabels","branchPattern","commitPattern","permittedTypeLabels","protectedLabels","templateRequired","templateWaived","requiredTemplateMarkers","requiredChecks"] as const;
function exactSnapshot(value:unknown,plan:DeliveryInspectionPlan):DeliveryPolicySnapshot{
 const r=record(value,snapshotKeys,"inspection snapshot"),b=plan.binding,issueUrl=canonical(r.issueUrl,b,"issue"),number=Number(r.issueNumber);canonical(r.repositoryUrl,b,"repository");canonical(r.policyUrl,b,"policy");
 for(const key of requestKeys)if(r[key]!==plan.request[key])throw new Error("Inspection snapshot target mismatch");if(r.host!==b.host||r.owner!==b.owner||r.repository!==b.repository||!Number.isSafeInteger(number)||number<1||!issueUrl.endsWith(`/issues/${number}`)||!(r.issueState==="open"||r.issueState==="closed")||typeof r.templateRequired!=="boolean"||typeof r.templateWaived!=="boolean")throw new Error("Inspection snapshot facts are malformed");
 if(r.branchPattern!==SUPPORTED_BRANCH_PATTERN||r.commitPattern!==SUPPORTED_COMMIT_PATTERN)throw new Error("Unsupported pattern contract");const issueLabels=strings(r.issueLabels,"issue labels"),types=strings(r.permittedTypeLabels,"permitted type labels",true),protectedLabels=strings(r.protectedLabels,"protected labels"),markers=strings(r.requiredTemplateMarkers,"template markers"),checks=strings(r.requiredChecks,"required checks",true);if(types.some(x=>!fold(x).startsWith("type:")))throw new Error("Permitted type labels are malformed");if(r.templateRequired===r.templateWaived||r.templateRequired&&markers.length===0)throw new Error("Template policy is contradictory");
 return Object.freeze({...Object.fromEntries(requestKeys.map(k=>[k,r[k]])),host:b.host,owner:b.owner,repository:b.repository,issueNumber:number,issueState:r.issueState,issueTitle:text(r.issueTitle,"issue title"),issueLabels:Object.freeze(issueLabels),branchPattern:SUPPORTED_BRANCH_PATTERN,commitPattern:SUPPORTED_COMMIT_PATTERN,permittedTypeLabels:Object.freeze(types),protectedLabels:Object.freeze(protectedLabels),templateRequired:r.templateRequired,templateWaived:r.templateWaived,requiredTemplateMarkers:Object.freeze(markers),requiredChecks:Object.freeze(checks)}) as DeliveryPolicySnapshot;
}
export function prepareDeliveryInspection(input:DeliveryInspectionInput):DeliveryInspectionPlan{
 const r=record(input,["binding","baseBranch","approvedIssueUrl","expectedPolicySourceIdentity","policyUrl"],"inspection input"),b=binding(r.binding),repositoryUrl=`https://${b.host}/${b.owner}/${b.repository}`,request=Object.freeze({repositoryUrl,issueUrl:canonical(r.approvedIssueUrl,b,"issue"),policyUrl:canonical(r.policyUrl,b,"policy"),baseBranch:text(r.baseBranch,"base branch"),policySourceIdentity:text(r.expectedPolicySourceIdentity,"policy source identity")}),plan=Object.freeze({binding:b,request});plans.add(plan);return plan;
}
export async function executeDeliveryInspection(plan:DeliveryInspectionPlan,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,port:DeliveryInspectionPort):Promise<DeliveryInspectionResult>{
 if(!plain(plan)||!plans.has(plan))throw new Error("Inspection requires an opaque prepared plan");if(usedPlans.has(plan))throw new Error("Inspection plan already consumed");usedPlans.add(plan);const expected=binding(expectedBinding);if(!sameBinding(plan.binding,expected))throw new Error("Inspection authority binding mismatch");const raw=await executeAuthorizedRead(authority,expected,b=>port.read(b,plan.request));const result=exactSnapshot(raw,plan);results.set(result,result);return result;
}
export function prepareBranchDelivery(inspection:DeliveryInspectionResult,candidate:BranchDeliveryCandidate):BranchDeliveryPlan{
 const observed=typeof inspection==="object"&&inspection!==null?results.get(inspection):undefined;if(!observed)throw new Error("Branch preparation requires genuine inspection evidence");if(usedResults.has(inspection))throw new Error("Inspection evidence already used");usedResults.add(inspection);const c=record(candidate,["repositoryUrl","issueUrl","policySourceIdentity","baseBranch","branch","commits","prTitle","prBody","labels","protectedLabelMutations"],"branch candidate");
 for(const key of ["repositoryUrl","issueUrl","policySourceIdentity","baseBranch"] as const)if(c[key]!==observed[key])throw new Error("Candidate does not match inspected target");if(observed.issueState!=="open"||observed.issueLabels.filter(x=>fold(x)==="status:approved").length!==1)throw new Error("Issue is not unambiguously approved and open");
 const branch=text(c.branch,"branch"),commits=strings(c.commits,"commits",true),labels=strings(c.labels,"candidate labels"),mutations=strings(c.protectedLabelMutations,"protected label mutations");if(!new RegExp(SUPPORTED_BRANCH_PATTERN,"u").test(branch)||commits.some(x=>!new RegExp(SUPPORTED_COMMIT_PATTERN,"u").test(x)))throw new Error("Branch or commit does not match supported policy");const allowed=new Set(observed.permittedTypeLabels.map(fold)),typeLabels=labels.filter(x=>fold(x).startsWith("type:"));if(typeLabels.length!==1||!allowed.has(fold(typeLabels[0]!)))throw new Error("Candidate requires exactly one permitted type label");const protectedSet=new Set(observed.protectedLabels.map(fold));if(mutations.length||labels.some(x=>protectedSet.has(fold(x))))throw new Error("Protected label mutation requested");
 const title=text(c.prTitle,"PR title");if(typeof c.prBody!=="string"||!c.prBody||c.prBody.trim()!==c.prBody||/[\u0000-\u0009\u000b\u000c\u000e-\u001f\u007f-\u009f]/u.test(c.prBody))throw new Error("PR body is malformed");const body=c.prBody,link=`Closes ${observed.issueUrl}`;if(!body.split(/\r?\n/u).includes(link))throw new Error("PR closing linkage mismatch");if(observed.templateRequired&&(observed.requiredTemplateMarkers.some(m=>!body.includes(m))||/(?:^|\n)\s*- \[ \]/u.test(body)))throw new Error("PR template markers are missing or unchecked");const frozenCommits=Object.freeze(commits),frozenLabels=Object.freeze(labels),template=Object.freeze({required:observed.templateRequired,waived:observed.templateWaived,markers:observed.requiredTemplateMarkers}),approvedIssue=Object.freeze({number:observed.issueNumber,title:observed.issueTitle,labels:observed.issueLabels}),plan=Object.freeze({repositoryUrl:observed.repositoryUrl,issueUrl:observed.issueUrl,policyUrl:observed.policyUrl,policySourceIdentity:observed.policySourceIdentity,baseBranch:observed.baseBranch,approvedIssue,branch,commits:frozenCommits,prTitle:title,prBody:body,finalLabels:frozenLabels,template,requiredChecks:observed.requiredChecks});branchPlans.add(plan);return plan;
}

/** Claims genuine C1 evidence without exposing its private provenance state. */
export function claimBranchDeliveryPlan(plan:BranchDeliveryPlan):void{
 if(typeof plan!=="object"||plan===null||!branchPlans.has(plan))throw new Error("Local delivery requires genuine branch plan evidence");if(claimedBranchPlans.has(plan))throw new Error("Branch plan evidence already claimed");claimedBranchPlans.add(plan);
}
