import {claimBranchDeliveryPlan,type BranchDeliveryPlan} from "./branch-preparation.js";
import {executeOneAttempt,type OperationAttempt,type RepositoryOperationAuthority,type RepositoryOperationBinding} from "../repository/operation-policy.js";

export interface LocalDeliveryPreparation{readonly baseCommitIdentity:string;readonly candidateTrees:readonly string[];}
export interface LocalDeliveryPlan{readonly repositoryUrl:string;readonly baseBranch:string;readonly branch:string;readonly baseCommitIdentity:string;readonly commits:readonly string[];readonly candidateTrees:readonly string[];}
export interface BranchCreatePayload{readonly repositoryIdentity:string;readonly worktreeIdentity:string;readonly baseBranch:string;readonly branch:string;readonly baseCommitIdentity:string;}
export interface LocalCommitPayload{readonly repositoryIdentity:string;readonly worktreeIdentity:string;readonly branch:string;readonly message:string;readonly parentCommitIdentity:string;readonly treeIdentity:string;}
export interface LocalHeadSnapshot{readonly repositoryIdentity:string;readonly worktreeIdentity:string;readonly branch:string;readonly headCommitIdentity:string;}
export interface LocalCommitSnapshot{readonly repositoryIdentity:string;readonly worktreeIdentity:string;readonly branch:string;readonly commitIdentity:string;readonly message:string;readonly parentCommitIdentity:string;readonly treeIdentity:string;}
export interface LocalDeliveryPort{
 createBranch(binding:RepositoryOperationBinding,payload:BranchCreatePayload):OperationAttempt|Promise<OperationAttempt>;
 readBranch(binding:RepositoryOperationBinding,payload:BranchCreatePayload):LocalHeadSnapshot|null|Promise<LocalHeadSnapshot|null>;
 commit(binding:RepositoryOperationBinding,payload:LocalCommitPayload):OperationAttempt|Promise<OperationAttempt>;
 readCommit(binding:RepositoryOperationBinding,payload:LocalCommitPayload):LocalCommitSnapshot|LocalHeadSnapshot|null|Promise<LocalCommitSnapshot|LocalHeadSnapshot|null>;
}
export interface LocalDeliveryProgress{readonly classification:"confirmed";readonly stage:"branch"|"commit";readonly branch:string;readonly headCommitIdentity:string;readonly completedCommits:number;readonly totalCommits:number;}
export interface ConfirmedLocalDelivery{readonly classification:"confirmed";readonly branch:string;readonly headCommitIdentity:string;readonly commitIdentities:readonly string[];}
export type LocalDeliveryFailure=Readonly<{classification:"no_write"|"unknown";operationReason:string;readBackReason:string}>;
export type LocalBranchOutcome=LocalDeliveryProgress|LocalDeliveryFailure;
export type LocalCommitOutcome=LocalDeliveryProgress|ConfirmedLocalDelivery|LocalDeliveryFailure;

type ProgressState={plan:LocalDeliveryPlan;branchPlan:BranchDeliveryPlan;index:number;head:string;commits:readonly string[]};
export interface ConfirmedLocalDeliveryClaim{readonly branchPlan:BranchDeliveryPlan;readonly localPlan:LocalDeliveryPlan;}
const plans=new WeakMap<object,BranchDeliveryPlan>(),usedPlans=new WeakSet<object>(),progresses=new WeakMap<object,ProgressState>(),usedProgresses=new WeakSet<object>(),results=new WeakMap<object,ConfirmedLocalDeliveryClaim>(),usedResults=new WeakSet<object>();
const sha=(value:unknown):value is string=>typeof value==="string"&&/^sha256:[a-f0-9]{64}$/u.test(value);
function record(value:unknown,keys:readonly string[],_noun:string):Record<string,unknown>|null{
 try{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return null;const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k))||keys.some(k=>!Object.hasOwn(value,k)))return null;const out:Record<string,unknown>={};for(const key of keys){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))return null;out[key]=d.value;}return out;}catch{return null;}
}
function exactArray(value:unknown):unknown[]|null{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)return null;const keys=Reflect.ownKeys(value),indexes=Array.from({length:value.length},(_,i)=>String(i));if(keys.some(k=>typeof k!=="string"||(k!=="length"&&!indexes.includes(k)))||indexes.some(k=>!Object.hasOwn(value,k)))return null;const out:unknown[]=[];for(const key of indexes){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))return null;out.push(d.value);}return out;}
function exactPort(value:LocalDeliveryPort):LocalDeliveryPort{const r=record(value,["createBranch","readBranch","commit","readCommit"],"local delivery port");if(!r||Object.values(r).some(v=>typeof v!=="function"))throw new Error("Local delivery port must contain exact callbacks");return value;}
function target(plan:LocalDeliveryPlan,binding:RepositoryOperationBinding,action:"branch_create"|"commit"):BranchCreatePayload{
 const r=record(binding,["host","owner","repository","sessionId","actor","action"],"operation binding");if(!r||r.action!==action||plan.repositoryUrl!==`https://${r.host}/${r.owner}/${r.repository}`||typeof r.sessionId!=="string")throw new Error("Local delivery target binding mismatch");return Object.freeze({repositoryIdentity:plan.repositoryUrl,worktreeIdentity:r.sessionId,baseBranch:plan.baseBranch,branch:plan.branch,baseCommitIdentity:plan.baseCommitIdentity});
}
function head(value:unknown,payload:BranchCreatePayload):"intended"|"unchanged"|"drift"|"malformed"{
 if(value===null)return "unchanged";const r=record(value,["repositoryIdentity","worktreeIdentity","branch","headCommitIdentity"],"head snapshot");if(!r||!sha(r.headCommitIdentity))return "malformed";return r.repositoryIdentity===payload.repositoryIdentity&&r.worktreeIdentity===payload.worktreeIdentity&&r.branch===payload.branch&&r.headCommitIdentity===payload.baseCommitIdentity?"intended":"drift";
}
function commitSnapshot(value:unknown,payload:LocalCommitPayload):{kind:"intended";identity:string}|{kind:"unchanged"|"drift"|"malformed"}{
 const unchanged=record(value,["repositoryIdentity","worktreeIdentity","branch","headCommitIdentity"],"head snapshot");if(unchanged)return unchanged.repositoryIdentity===payload.repositoryIdentity&&unchanged.worktreeIdentity===payload.worktreeIdentity&&unchanged.branch===payload.branch&&unchanged.headCommitIdentity===payload.parentCommitIdentity?{kind:"unchanged"}:{kind:"drift"};
 const r=record(value,["repositoryIdentity","worktreeIdentity","branch","commitIdentity","message","parentCommitIdentity","treeIdentity"],"commit snapshot");if(!r||!sha(r.commitIdentity))return {kind:"malformed"};return r.repositoryIdentity===payload.repositoryIdentity&&r.worktreeIdentity===payload.worktreeIdentity&&r.branch===payload.branch&&r.message===payload.message&&r.parentCommitIdentity===payload.parentCommitIdentity&&r.treeIdentity===payload.treeIdentity?{kind:"intended",identity:r.commitIdentity}:{kind:"drift"};
}
function failure(classification:"no_write"|"unknown",operationReason:string,readBackReason:string):LocalDeliveryFailure{return Object.freeze({classification,operationReason,readBackReason});}
function progress(state:ProgressState,stage:"branch"|"commit"):LocalDeliveryProgress{const value=Object.freeze({classification:"confirmed" as const,stage,branch:state.plan.branch,headCommitIdentity:state.head,completedCommits:state.index,totalCommits:state.plan.commits.length});progresses.set(value,state);return value;}

export function prepareLocalDelivery(branchPlan:BranchDeliveryPlan,input:LocalDeliveryPreparation):LocalDeliveryPlan{
 claimBranchDeliveryPlan(branchPlan);const r=record(input,["baseCommitIdentity","candidateTrees"],"local delivery input"),trees=r&&exactArray(r.candidateTrees);if(!r||!sha(r.baseCommitIdentity)||!trees||trees.length!==branchPlan.commits.length||trees.some(x=>!sha(x)))throw new Error("Local delivery requires one exact SHA tree per commit");const plan=Object.freeze({repositoryUrl:branchPlan.repositoryUrl,baseBranch:branchPlan.baseBranch,branch:branchPlan.branch,baseCommitIdentity:r.baseCommitIdentity,commits:Object.freeze([...branchPlan.commits]),candidateTrees:Object.freeze(trees as string[])});plans.set(plan,branchPlan);return plan;
}
export async function executeLocalBranch(plan:LocalDeliveryPlan,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,port:LocalDeliveryPort):Promise<LocalBranchOutcome>{
 const branchPlan=typeof plan==="object"&&plan!==null?plans.get(plan):undefined;if(!branchPlan)throw new Error("Branch execution requires an opaque local plan");if(usedPlans.has(plan))throw new Error("Local plan already consumed");usedPlans.add(plan);const callbacks=exactPort(port),payload=target(plan,expectedBinding,"branch_create");let observed:"intended"|"unchanged"|"drift"|"malformed"="malformed";const outcome=await executeOneAttempt(authority,expectedBinding,b=>callbacks.createBranch(b,payload),async b=>{observed=head(await callbacks.readBranch(b,payload),payload);return observed==="intended"?{state:"intended",reasonCode:"exact_intended"}:observed==="unchanged"?{state:"unchanged",reasonCode:"verified_absence"}:observed==="drift"?{state:"drift",reasonCode:"branch_drift"}:{state:"unconfirmed",reasonCode:"malformed_readback"};});if(outcome.classification!=="confirmed")return failure(outcome.classification,outcome.operationReason,outcome.readBackReason);return progress({plan,branchPlan,index:0,head:plan.baseCommitIdentity,commits:Object.freeze([])},"branch");
}
export async function executeNextLocalCommit(current:LocalDeliveryProgress,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,port:LocalDeliveryPort):Promise<LocalCommitOutcome>{
 const state=typeof current==="object"&&current!==null?progresses.get(current):undefined;if(!state)throw new Error("Commit execution requires genuine confirmed progress");if(usedProgresses.has(current))throw new Error("Local progress already consumed");usedProgresses.add(current);if(state.index>=state.plan.commits.length)throw new Error("Local delivery has no remaining commit");const callbacks=exactPort(port),base=target(state.plan,expectedBinding,"commit"),payload=Object.freeze({repositoryIdentity:base.repositoryIdentity,worktreeIdentity:base.worktreeIdentity,branch:base.branch,message:state.plan.commits[state.index]!,parentCommitIdentity:state.head,treeIdentity:state.plan.candidateTrees[state.index]!});let identity:string|undefined;const outcome=await executeOneAttempt(authority,expectedBinding,b=>callbacks.commit(b,payload),async b=>{const observed=commitSnapshot(await callbacks.readCommit(b,payload),payload);if(observed.kind==="intended"){identity=observed.identity;return {state:"intended",reasonCode:"exact_intended"};}return observed.kind==="unchanged"?{state:"unchanged",reasonCode:"exact_unchanged"}:observed.kind==="drift"?{state:"drift",reasonCode:"commit_drift"}:{state:"unconfirmed",reasonCode:"malformed_readback"};});if(outcome.classification!=="confirmed"||!identity)return failure(outcome.classification==="no_write"?"no_write":"unknown",outcome.operationReason,outcome.readBackReason);const next:ProgressState={plan:state.plan,branchPlan:state.branchPlan,index:state.index+1,head:identity,commits:Object.freeze([...state.commits,identity])};if(next.index<state.plan.commits.length)return progress(next,"commit");const result=Object.freeze({classification:"confirmed" as const,branch:state.plan.branch,headCommitIdentity:identity,commitIdentities:next.commits}),claim=Object.freeze({branchPlan:state.branchPlan,localPlan:state.plan});results.set(result,claim);return result;
}

/** Claims genuine final C2 evidence once without exposing provenance storage. */
export function claimConfirmedLocalDelivery(result:ConfirmedLocalDelivery):ConfirmedLocalDeliveryClaim{
 const claim=typeof result==="object"&&result!==null?results.get(result):undefined;if(!claim)throw new Error("Remote delivery requires genuine confirmed local evidence");if(usedResults.has(result))throw new Error("Confirmed local evidence already claimed");usedResults.add(result);return claim;
}
