import {createHash} from "node:crypto";
import {claimConfirmedPrPublication,type ConfirmedPrPublication,type RemoteDeliveryPlan} from "./remote-delivery.js";
import {executeAuthorizedRead,executeOneAttempt,planProtectedLabelMutation,type OperationAttempt,type RepositoryOperationAuthority,type RepositoryOperationBinding,type RepositoryPermission} from "../repository/operation-policy.js";

export interface PrLabelPublicationInput{readonly protectedLabels:readonly string[];readonly actorPermission:RepositoryPermission;readonly sizeExceptionRationale?:string;}
export interface PrLabelSnapshot{readonly repositoryUrl:string;readonly prUrl:string;readonly number:number;readonly state:"open"|"closed";readonly baseBranch:string;readonly headBranch:string;readonly title:string;readonly body:string;readonly headCommitIdentity:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly labels:readonly string[];readonly requiredChecks:readonly string[];readonly successfulChecks:readonly string[];}
export interface PrLabelPublicationPlan{readonly host:string;readonly owner:string;readonly repository:string;readonly sessionId:string;readonly actor:string;readonly repositoryUrl:string;readonly prUrl:string;readonly number:number;readonly baseBranch:string;readonly headBranch:string;readonly title:string;readonly body:string;readonly headCommitIdentity:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly pendingLabels:readonly string[];readonly protectedLabels:readonly string[];readonly requiredChecks:readonly string[];readonly actorPermission:RepositoryPermission;readonly sizeExceptionRationale?:string;}
export interface PrLabelMutationPayload{readonly repositoryUrl:string;readonly prUrl:string;readonly number:number;readonly baselineSnapshotHash:string;readonly add:readonly string[];readonly remove:readonly string[];}
export interface PrLabelPublicationPort{read(binding:RepositoryOperationBinding,target:Readonly<{repositoryUrl:string;prUrl:string;number:number}>):PrLabelSnapshot|Promise<PrLabelSnapshot>;label(binding:RepositoryOperationBinding,payload:PrLabelMutationPayload):OperationAttempt|Promise<OperationAttempt>;}
export type PrLabelPublicationResult=Readonly<{classification:"confirmed";operationReason:string;readBackReason:string;repositoryUrl:string;prUrl:string;number:number;labels:readonly string[];requiredChecks:readonly string[];successfulChecks:readonly string[];missingChecks:readonly string[];mergeAuthority:"pending"}>|Readonly<{classification:"no_write"|"unknown";operationReason:string;readBackReason:string;mergeAuthority:"stopped"}>;

type State={plan:PrLabelPublicationPlan;binding:RepositoryOperationBinding};
const plans=new WeakMap<object,State>(),used=new WeakSet<object>(),fold=(value:string)=>value.normalize("NFC").toLocaleLowerCase("en-US"),permissions=new Set<RepositoryPermission>(["ADMIN","MAINTAIN","WRITE","TRIAGE","READ","UNVERIFIED"]);
function record(value:unknown,keys:readonly string[]):Record<string,unknown>|null{try{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return null;const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k))||keys.some(k=>!Object.hasOwn(value,k)))return null;const out:Record<string,unknown>={};for(const key of keys){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))return null;out[key]=d.value;}return out;}catch{return null;}}
function strings(value:unknown):string[]|null{try{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)return null;const keys=Reflect.ownKeys(value),indexes=Array.from({length:value.length},(_,i)=>String(i));if(keys.some(k=>typeof k!=="string"||(k!=="length"&&!indexes.includes(k)))||indexes.some(k=>!Object.hasOwn(value,k)))return null;const out:string[]=[];for(const key of indexes){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d)||typeof d.value!=="string"||!d.value||d.value.trim()!==d.value||d.value!==d.value.normalize("NFC"))return null;out.push(d.value);}return new Set(out.map(fold)).size===out.length?out:null;}catch{return null;}}
function exactInput(value:PrLabelPublicationInput):{protectedLabels:string[];actorPermission:RepositoryPermission;sizeExceptionRationale?:string}{const keys=value&&Object.hasOwn(value,"sizeExceptionRationale")?["protectedLabels","actorPermission","sizeExceptionRationale"]:["protectedLabels","actorPermission"],r=record(value,keys),protectedLabels=r&&strings(r.protectedLabels);if(!r||!protectedLabels||!permissions.has(r.actorPermission as RepositoryPermission)||r.sizeExceptionRationale!==undefined&&(typeof r.sizeExceptionRationale!=="string"||!r.sizeExceptionRationale.trim()))throw new Error("PR label publication input must be exact plain policy data");return {protectedLabels,actorPermission:r.actorPermission as RepositoryPermission,...(r.sizeExceptionRationale===undefined?{}:{sizeExceptionRationale:r.sizeExceptionRationale as string})};}
function sameIdentity(a:RepositoryOperationBinding,b:RepositoryOperationBinding):boolean{return a.host===b.host&&a.owner===b.owner&&a.repository===b.repository&&a.sessionId===b.sessionId&&a.actor===b.actor;}
function binding(value:RepositoryOperationBinding,action:"remote_read"|"label_mutate"):RepositoryOperationBinding{const r=record(value,["host","owner","repository","sessionId","actor","action"]);if(!r||r.action!==action||["host","owner","repository","sessionId","actor"].some(k=>typeof r[k]!=="string"))throw new Error("PR label publication binding mismatch");return value;}
function canonicalPr(value:unknown,repositoryUrl:string,number:unknown):value is string{if(typeof value!=="string"||typeof number!=="number"||!Number.isSafeInteger(number)||number<1)return false;let u:URL;try{u=new URL(value);}catch{return false;}return u.protocol==="https:"&&!u.username&&!u.password&&!u.port&&!u.search&&!u.hash&&value===`${repositoryUrl}/pull/${number}`;}
const snapshotKeys=["repositoryUrl","prUrl","number","state","baseBranch","headBranch","title","body","headCommitIdentity","issueUrl","policySourceIdentity","labels","requiredChecks","successfulChecks"] as const;
function sameSet(a:readonly string[],b:readonly string[]):boolean{const left=[...a].map(fold).sort(),right=[...b].map(fold).sort();return left.length===right.length&&left.every((v,i)=>v===right[i]);}
function sameExactSet(a:readonly string[],b:readonly string[]):boolean{const left=[...a].sort(),right=[...b].sort();return left.length===right.length&&left.every((v,i)=>v===right[i]);}
function snapshot(value:unknown,plan:PrLabelPublicationPlan):PrLabelSnapshot|null{const r=record(value,snapshotKeys),labels=r&&strings(r.labels),required=r&&strings(r.requiredChecks),successful=r&&strings(r.successfulChecks);if(!r||!labels||!required||!successful||r.repositoryUrl!==plan.repositoryUrl||!canonicalPr(r.prUrl,plan.repositoryUrl,r.number)||r.prUrl!==plan.prUrl||r.number!==plan.number||r.state!=="open"||r.baseBranch!==plan.baseBranch||r.headBranch!==plan.headBranch||r.title!==plan.title||r.body!==plan.body||r.headCommitIdentity!==plan.headCommitIdentity||r.issueUrl!==plan.issueUrl||r.policySourceIdentity!==plan.policySourceIdentity||!sameExactSet(required,plan.requiredChecks)||successful.some(x=>!required.includes(x)))return null;return {repositoryUrl:r.repositoryUrl as string,prUrl:r.prUrl as string,number:r.number as number,state:"open",baseBranch:r.baseBranch as string,headBranch:r.headBranch as string,title:r.title as string,body:r.body as string,headCommitIdentity:r.headCommitIdentity as string,issueUrl:r.issueUrl as string,policySourceIdentity:r.policySourceIdentity as string,labels:Object.freeze(labels),requiredChecks:Object.freeze(required),successfulChecks:Object.freeze(successful)};}
function digest(value:PrLabelSnapshot):string{return `sha256:${createHash("sha256").update(JSON.stringify({...value,labels:[...value.labels].sort(),requiredChecks:[...value.requiredChecks].sort(),successfulChecks:[...value.successfulChecks].sort()})).digest("hex")}`;}
function failure(classification:"no_write"|"unknown",operationReason:string,readBackReason:string):PrLabelPublicationResult{return Object.freeze({classification,operationReason,readBackReason,mergeAuthority:"stopped"});}
function callbacks(value:PrLabelPublicationPort):PrLabelPublicationPort{const r=record(value,["read","label"]);if(!r||typeof r.read!=="function"||typeof r.label!=="function")throw new Error("PR label publication port must contain exact callbacks");return value;}

export function preparePrLabelPublication(confirmedPr:ConfirmedPrPublication,input:PrLabelPublicationInput):PrLabelPublicationPlan{
 const provenance=claimConfirmedPrPublication(confirmedPr),policy=exactInput(input),remote=provenance.plan as RemoteDeliveryPlan,b=provenance.binding;if(remote.repositoryUrl!==confirmedPr.repositoryUrl||remote.baseBranch!==confirmedPr.baseBranch||remote.localBranch!==confirmedPr.headBranch||remote.headCommitIdentity!==confirmedPr.headCommitIdentity)throw new Error("Confirmed PR publication target mismatch");
 planProtectedLabelMutation({currentLabels:[],add:remote.pendingLabels,remove:[],protectedLabels:policy.protectedLabels,actorPermission:policy.actorPermission,...(policy.sizeExceptionRationale===undefined?{}:{rationale:policy.sizeExceptionRationale})});const plan=Object.freeze({host:b.host,owner:b.owner,repository:b.repository,sessionId:b.sessionId,actor:b.actor,repositoryUrl:remote.repositoryUrl,prUrl:confirmedPr.prUrl,number:confirmedPr.number,baseBranch:remote.baseBranch,headBranch:remote.localBranch,title:remote.prTitle,body:remote.prBody,headCommitIdentity:remote.headCommitIdentity,issueUrl:remote.issueUrl,policySourceIdentity:remote.policySourceIdentity,pendingLabels:Object.freeze([...remote.pendingLabels]),protectedLabels:Object.freeze([...policy.protectedLabels]),requiredChecks:Object.freeze([...remote.requiredChecks]),actorPermission:policy.actorPermission,...(policy.sizeExceptionRationale===undefined?{}:{sizeExceptionRationale:policy.sizeExceptionRationale})});plans.set(plan,{plan,binding:b});return plan;
}

export async function executePrLabelPublication(plan:PrLabelPublicationPlan,readAuthority:RepositoryOperationAuthority,labelAuthority:RepositoryOperationAuthority,bindings:Readonly<{read:RepositoryOperationBinding;label:RepositoryOperationBinding}>,port:PrLabelPublicationPort):Promise<PrLabelPublicationResult>{
 const state=typeof plan==="object"&&plan!==null?plans.get(plan):undefined;if(!state)throw new Error("PR label publication requires an opaque prepared plan");if(used.has(plan))throw new Error("PR label publication plan already consumed");used.add(plan);const pair=record(bindings,["read","label"]);if(!pair)throw new Error("PR label publication binding mismatch");const read=binding(pair.read as RepositoryOperationBinding,"remote_read"),label=binding(pair.label as RepositoryOperationBinding,"label_mutate");if(!sameIdentity(state.binding,read)||!sameIdentity(state.binding,label))throw new Error("PR label publication binding mismatch");const remote=callbacks(port),target=Object.freeze({repositoryUrl:plan.repositoryUrl,prUrl:plan.prUrl,number:plan.number});let baseline:PrLabelSnapshot;try{const raw=await executeAuthorizedRead(readAuthority,read,b=>remote.read(b,target)),exact=snapshot(raw,plan);if(!exact)return failure("unknown","not_attempted","baseline_mismatch");baseline=exact;}catch{return failure("unknown","not_attempted","pre_read_failed");}
 const pending=new Set(plan.pendingLabels.map(fold)),protectedSet=new Set(plan.protectedLabels.map(fold)),prefixes=new Set(plan.pendingLabels.map(x=>`${x.split(":",1)[0]}:`));const remove=baseline.labels.filter(x=>!pending.has(fold(x))&&(protectedSet.has(fold(x))||[...prefixes].some(prefix=>fold(x).startsWith(fold(prefix))))),add=plan.pendingLabels.filter(x=>!baseline.labels.some(y=>fold(y)===fold(x))),mutation=planProtectedLabelMutation({currentLabels:baseline.labels,add,remove,protectedLabels:plan.protectedLabels,actorPermission:plan.actorPermission,...(plan.sizeExceptionRationale===undefined?{}:{rationale:plan.sizeExceptionRationale})}),baselineSnapshotHash=digest(baseline),payload=Object.freeze({repositoryUrl:plan.repositoryUrl,prUrl:plan.prUrl,number:plan.number,baselineSnapshotHash,add:mutation.add,remove:mutation.remove});let final:PrLabelSnapshot|undefined;
 const outcome=await executeOneAttempt(labelAuthority,label,b=>remote.label(b,payload),async b=>{const observed=snapshot(await remote.read(b,target),plan);if(!observed)return {state:"unconfirmed",reasonCode:"malformed_readback"};if(digest(observed)===baselineSnapshotHash)return {state:"unchanged",reasonCode:"exact_unchanged"};if(!sameSet(observed.labels,mutation.expectedFinalLabels))return {state:"drift",reasonCode:"state_drift"};final=observed;return {state:"intended",reasonCode:"exact_intended"};});if(outcome.classification!=="confirmed"||!final||outcome.operationReason==="stale_baseline"||outcome.operationReason==="stale_conditional")return failure(outcome.classification==="no_write"&&outcome.operationReason!=="stale_baseline"&&outcome.operationReason!=="stale_conditional"?"no_write":"unknown",outcome.operationReason,outcome.readBackReason);
 const missing=plan.requiredChecks.filter(x=>!final!.successfulChecks.includes(x));return Object.freeze({classification:"confirmed",operationReason:outcome.operationReason,readBackReason:outcome.readBackReason,repositoryUrl:plan.repositoryUrl,prUrl:plan.prUrl,number:plan.number,labels:Object.freeze([...final.labels]),requiredChecks:plan.requiredChecks,successfulChecks:Object.freeze([...final.successfulChecks]),missingChecks:Object.freeze(missing),mergeAuthority:"pending"});
}
