import {claimConfirmedLocalDelivery,type ConfirmedLocalDelivery} from "./local-delivery.js";
import {executeOneAttempt,type OperationAttempt,type RepositoryOperationAuthority,type RepositoryOperationBinding} from "../repository/operation-policy.js";

export interface RemoteDeliveryPlan{readonly repositoryUrl:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly baseBranch:string;readonly localBranch:string;readonly headCommitIdentity:string;readonly prTitle:string;readonly prBody:string;readonly pendingLabels:readonly string[];readonly template:Readonly<{required:boolean;waived:boolean;markers:readonly string[]}>;readonly requiredChecks:readonly string[];}
export interface PushPayload{readonly repositoryUrl:string;readonly localBranch:string;readonly remoteRef:string;readonly headCommitIdentity:string;}
export interface PushSnapshot extends PushPayload{}
export interface PushPort{push(binding:RepositoryOperationBinding,payload:PushPayload):OperationAttempt|Promise<OperationAttempt>;readPush(binding:RepositoryOperationBinding,payload:PushPayload):PushSnapshot|null|Promise<PushSnapshot|null>;}
export interface ConfirmedPushProgress{readonly classification:"confirmed";readonly repositoryUrl:string;readonly localBranch:string;readonly remoteRef:string;readonly headCommitIdentity:string;}
export interface PrOpenPayload{readonly repositoryUrl:string;readonly baseBranch:string;readonly headBranch:string;readonly title:string;readonly body:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly expectedHeadCommitIdentity:string;readonly initialLabels:readonly string[];}
export interface PrSnapshot{readonly repositoryUrl:string;readonly prUrl:string;readonly number:number;readonly state:"open"|"closed";readonly baseBranch:string;readonly headBranch:string;readonly title:string;readonly body:string;readonly headCommitIdentity:string;readonly issueUrl:string;readonly policySourceIdentity:string;readonly labels:readonly string[];}
export interface PrOpenPort{openPr(binding:RepositoryOperationBinding,payload:PrOpenPayload):OperationAttempt|Promise<OperationAttempt>;readPr(binding:RepositoryOperationBinding,payload:PrOpenPayload):PrSnapshot|readonly PrSnapshot[]|null|Promise<PrSnapshot|readonly PrSnapshot[]|null>;}
export interface ConfirmedPrPublication{readonly classification:"confirmed";readonly repositoryUrl:string;readonly prUrl:string;readonly number:number;readonly state:"open";readonly baseBranch:string;readonly headBranch:string;readonly headCommitIdentity:string;readonly labels:readonly string[];}
export type RemoteDeliveryFailure=Readonly<{classification:"no_write"|"unknown";operationReason:string;readBackReason:string}>;
export type PushOutcome=ConfirmedPushProgress|RemoteDeliveryFailure;
export type PrOpenOutcome=ConfirmedPrPublication|RemoteDeliveryFailure;

type PushState={plan:RemoteDeliveryPlan};
const plans=new WeakSet<object>(),usedPlans=new WeakSet<object>(),pushes=new WeakMap<object,PushState>(),usedPushes=new WeakSet<object>(),publications=new WeakSet<object>();
function record(value:unknown,keys:readonly string[]):Record<string,unknown>|null{try{if(typeof value!=="object"||value===null||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)return null;const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k))||keys.some(k=>!Object.hasOwn(value,k)))return null;const out:Record<string,unknown>={};for(const key of keys){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))return null;out[key]=d.value;}return out;}catch{return null;}}
function array(value:unknown):unknown[]|null{if(!Array.isArray(value)||Object.getPrototypeOf(value)!==Array.prototype)return null;const keys=Reflect.ownKeys(value),indexes=Array.from({length:value.length},(_,i)=>String(i));if(keys.some(k=>typeof k!=="string"||(k!=="length"&&!indexes.includes(k)))||indexes.some(k=>!Object.hasOwn(value,k)))return null;const out:unknown[]=[];for(const key of indexes){const d=Object.getOwnPropertyDescriptor(value,key);if(!d?.enumerable||!("value" in d))return null;out.push(d.value);}return out;}
function port<T>(value:T,keys:readonly string[]):T{const r=record(value,keys);if(!r||Object.values(r).some(v=>typeof v!=="function"))throw new Error("Remote delivery port must contain exact callbacks");return value;}
function binding(plan:RemoteDeliveryPlan,value:RepositoryOperationBinding,action:"push"|"pr_open"):void{const r=record(value,["host","owner","repository","sessionId","actor","action"]);if(!r||r.action!==action||typeof r.sessionId!=="string"||plan.repositoryUrl!==`https://${r.host}/${r.owner}/${r.repository}`)throw new Error("Remote delivery target binding mismatch");}
function failure(classification:"no_write"|"unknown",operationReason:string,readBackReason:string):RemoteDeliveryFailure{return Object.freeze({classification,operationReason,readBackReason});}
function exactStrings(value:unknown):readonly string[]|null{const out=array(value);return out&&out.every(x=>typeof x==="string")?out as string[]:null;}
function sameArray(left:readonly string[],right:readonly string[]):boolean{return left.length===right.length&&left.every((x,i)=>x===right[i]);}
function canonicalPrUrl(value:unknown,repositoryUrl:string,number:unknown):value is string{if(typeof value!=="string"||typeof number!=="number")return false;let url:URL;try{url=new URL(value);}catch{return false;}return Number.isSafeInteger(number)&&number>0&&url.protocol==="https:"&&!url.username&&!url.password&&!url.port&&!url.search&&!url.hash&&value===`${repositoryUrl}/pull/${number}`;}

export function prepareRemoteDelivery(confirmedLocal:ConfirmedLocalDelivery):RemoteDeliveryPlan{
 const {branchPlan,localPlan}=claimConfirmedLocalDelivery(confirmedLocal);if(localPlan.repositoryUrl!==branchPlan.repositoryUrl||localPlan.baseBranch!==branchPlan.baseBranch||localPlan.branch!==branchPlan.branch||confirmedLocal.branch!==localPlan.branch||confirmedLocal.headCommitIdentity!==confirmedLocal.commitIdentities.at(-1))throw new Error("Confirmed local evidence target mismatch");
 const plan=Object.freeze({repositoryUrl:branchPlan.repositoryUrl,issueUrl:branchPlan.issueUrl,policySourceIdentity:branchPlan.policySourceIdentity,baseBranch:branchPlan.baseBranch,localBranch:localPlan.branch,headCommitIdentity:confirmedLocal.headCommitIdentity,prTitle:branchPlan.prTitle,prBody:branchPlan.prBody,pendingLabels:Object.freeze([...branchPlan.finalLabels]),template:Object.freeze({required:branchPlan.template.required,waived:branchPlan.template.waived,markers:Object.freeze([...branchPlan.template.markers])}),requiredChecks:Object.freeze([...branchPlan.requiredChecks])});plans.add(plan);return plan;
}
export async function executePush(plan:RemoteDeliveryPlan,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,remote:PushPort):Promise<PushOutcome>{
 if(typeof plan!=="object"||plan===null||!plans.has(plan))throw new Error("Push requires an opaque remote plan");if(usedPlans.has(plan))throw new Error("Remote plan already consumed");usedPlans.add(plan);const callbacks=port(remote,["push","readPush"]),remoteRef=`refs/heads/${plan.localBranch}`;binding(plan,expectedBinding,"push");const payload=Object.freeze({repositoryUrl:plan.repositoryUrl,localBranch:plan.localBranch,remoteRef,headCommitIdentity:plan.headCommitIdentity});let exact=false;const outcome=await executeOneAttempt(authority,expectedBinding,b=>callbacks.push(b,payload),async b=>{const raw=await callbacks.readPush(b,payload);if(raw===null)return {state:"unchanged",reasonCode:"verified_absence"};const r=record(raw,["repositoryUrl","localBranch","remoteRef","headCommitIdentity"]);if(!r)return {state:"unconfirmed",reasonCode:"malformed_readback"};if(r.repositoryUrl===payload.repositoryUrl&&r.localBranch===payload.localBranch&&r.remoteRef===payload.remoteRef&&r.headCommitIdentity===payload.headCommitIdentity){exact=true;return {state:"intended",reasonCode:"exact_push"};}return {state:"drift",reasonCode:"push_drift"};});if(outcome.classification!=="confirmed"||!exact)return failure(outcome.classification==="no_write"?"no_write":"unknown",outcome.operationReason,outcome.readBackReason);const progress=Object.freeze({classification:"confirmed" as const,...payload});pushes.set(progress,{plan});return progress;
}
export async function executePrOpen(progress:ConfirmedPushProgress,authority:RepositoryOperationAuthority,expectedBinding:RepositoryOperationBinding,remote:PrOpenPort):Promise<PrOpenOutcome>{
 const state=typeof progress==="object"&&progress!==null?pushes.get(progress):undefined;if(!state)throw new Error("PR publication requires genuine confirmed push progress");if(usedPushes.has(progress))throw new Error("Push progress already consumed");usedPushes.add(progress);const callbacks=port(remote,["openPr","readPr"]),plan=state.plan;binding(plan,expectedBinding,"pr_open");const initialLabels=Object.freeze([] as string[]),payload=Object.freeze({repositoryUrl:plan.repositoryUrl,baseBranch:plan.baseBranch,headBranch:plan.localBranch,title:plan.prTitle,body:plan.prBody,issueUrl:plan.issueUrl,policySourceIdentity:plan.policySourceIdentity,expectedHeadCommitIdentity:plan.headCommitIdentity,initialLabels});let snapshot:Record<string,unknown>|undefined;const outcome=await executeOneAttempt(authority,expectedBinding,b=>callbacks.openPr(b,payload),async b=>{const raw=await callbacks.readPr(b,payload),items=raw===null?[]:Array.isArray(raw)?array(raw):[raw];if(!items)return {state:"unconfirmed",reasonCode:"malformed_readback"};if(items.length===0)return {state:"unchanged",reasonCode:"verified_absence"};if(items.length!==1)return {state:"unconfirmed",reasonCode:"multiple_prs"};const r=record(items[0],["repositoryUrl","prUrl","number","state","baseBranch","headBranch","title","body","headCommitIdentity","issueUrl","policySourceIdentity","labels"]),labels=r&&exactStrings(r.labels);if(!r||!labels||!canonicalPrUrl(r.prUrl,plan.repositoryUrl,r.number))return {state:"unconfirmed",reasonCode:"malformed_readback"};const exact=r.repositoryUrl===payload.repositoryUrl&&r.state==="open"&&r.baseBranch===payload.baseBranch&&r.headBranch===payload.headBranch&&r.title===payload.title&&r.body===payload.body&&r.headCommitIdentity===payload.expectedHeadCommitIdentity&&r.issueUrl===payload.issueUrl&&r.policySourceIdentity===payload.policySourceIdentity&&sameArray(labels,payload.initialLabels);if(!exact)return {state:"drift",reasonCode:"pr_drift"};snapshot=r;return {state:"intended",reasonCode:"exact_pr"};});if(outcome.classification!=="confirmed"||!snapshot)return failure(outcome.classification==="no_write"?"no_write":"unknown",outcome.operationReason,outcome.readBackReason);const result=Object.freeze({classification:"confirmed" as const,repositoryUrl:plan.repositoryUrl,prUrl:snapshot.prUrl as string,number:snapshot.number as number,state:"open" as const,baseBranch:plan.baseBranch,headBranch:plan.localBranch,headCommitIdentity:plan.headCommitIdentity,labels:Object.freeze([...payload.initialLabels])});publications.add(result);return result;
}
