import {createHash} from "node:crypto";

export type MarkdownControl={readonly type:"markdown";readonly body:string};
export type InputControl={readonly type:"input"|"textarea";readonly id:string;readonly label:string;readonly required?:boolean;readonly render?:string};
export type DropdownControl={readonly type:"dropdown";readonly id:string;readonly label:string;readonly options:readonly string[];readonly multiple?:boolean;readonly required?:boolean};
export type CheckboxOption={readonly id:string;readonly label:string;readonly required?:boolean;readonly firstPerson?:boolean};
export type CheckboxesControl={readonly type:"checkboxes";readonly id:string;readonly label:string;readonly options:readonly CheckboxOption[]};
export type IssueControl=MarkdownControl|InputControl|DropdownControl|CheckboxesControl;
export interface IssueForm{readonly id:string;readonly titlePrefix:string;readonly titleTemplate:string;readonly labels:readonly string[];readonly controls:readonly IssueControl[];}
export type IssueAnswers=Readonly<Record<string,unknown>>;
export interface ReviewedRedaction{readonly before:string;readonly after:string;readonly reviewed:true;}
export interface PrivacyPolicy{readonly redactions:readonly ReviewedRedaction[];}
export interface MaterializedIssue{readonly formId:string;readonly title:string;readonly body:string;readonly labels:readonly string[];readonly candidateIdentity:string;}
export type DuplicateClassification="duplicate"|"not_duplicate"|"uncertain";
export interface DuplicateSearchResult{readonly issue:string;readonly repository:string;readonly query:string;readonly candidateIdentity:string;readonly classification?:DuplicateClassification;}
export interface DuplicateSearchInput{readonly repository:string;readonly query:string;readonly candidateIdentity:string;readonly current:boolean;readonly coversOpen:boolean;readonly coversClosed:boolean;readonly complete:boolean;readonly truncated:boolean;readonly saturated:boolean;readonly results:readonly DuplicateSearchResult[];}
export interface DuplicateDecision{readonly status:"proceed"|"block";readonly reason:"all_not_duplicate"|"duplicate"|"uncertain";readonly duplicateIssue:string|null;}

const own=(value:unknown,allowed:readonly string[],required:readonly string[],message:string):Record<string,unknown>=>{
 if(value===null||typeof value!=="object"||Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype)throw new Error(message);
 const keys=Reflect.ownKeys(value);if(keys.some(key=>typeof key!=="string"||!allowed.includes(key))||required.some(key=>!Object.hasOwn(value,key)))throw new Error(message);
 for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key)!;if(!descriptor.enumerable||!("value" in descriptor))throw new Error(message);}
 return value as Record<string,unknown>;
};
const text=(value:unknown,name:string):string=>{if(typeof value!=="string"||!value.trim()||value.trim()!==value)throw new Error(`${name} is malformed`);return value;};
const id=(value:unknown,name:string):string=>{const result=text(value,name);if(!/^[A-Za-z0-9][A-Za-z0-9_-]*$/u.test(result))throw new Error(`${name} is malformed`);return result;};
const bool=(value:unknown,message:string):boolean|undefined=>value===undefined?undefined:typeof value==="boolean"?value:(()=>{throw new Error(message);})();
const uniqueStrings=(value:unknown,name:string,allowEmpty=false):string[]=>{
 if(!Array.isArray(value)||(!allowEmpty&&!value.length)||value.some(item=>typeof item!=="string"||!item.trim()||item.trim()!==item))throw new Error(`${name} are malformed`);
 const result=[...value] as string[],folded=result.map(item=>item.normalize("NFC").toLocaleLowerCase("und"));if(new Set(folded).size!==folded.length)throw new Error(`${name} are malformed`);return result;
};
const safeTitle=(value:unknown,name:string,template=false):string=>{
 if(typeof value!=="string"||(template&&!value.trim())||/[\u0000-\u001f\u007f-\u009f\u2028\u2029]/u.test(value))throw new Error(`${name} is malformed`);
 const remainder=template?value.replace(/\{\{[A-Za-z0-9][A-Za-z0-9_-]*\}\}/gu,""):value;if(/[{}]/u.test(remainder))throw new Error(`${name} is malformed`);return value;
};
const firstPerson=(label:string):boolean=>/^[^\p{L}\p{N}]*i(?:\b|['’](?:m|ve|d|ll|re)\b)/iu.test(label);
function controls(value:unknown):IssueControl[]{
 if(!Array.isArray(value))throw new Error("YAML Issue Form controls are malformed");const ids=new Set<string>(),labels=new Set<string>();
 return value.map(raw=>{
  const hinted=own(raw,["type","body","id","label","required","render","options","multiple"],["type"],"Issue Form control is malformed"),type=hinted.type;
  if(type==="markdown"){const item=own(raw,["type","body"],["type","body"],"Markdown control is malformed");if(typeof item.body!=="string")throw new Error("Markdown control is malformed");return Object.freeze({type,body:item.body});}
  if(type!=="input"&&type!=="textarea"&&type!=="dropdown"&&type!=="checkboxes")throw new Error("Issue Form contains unsupported control type");
  const allowed=type==="input"?["type","id","label","required"]:type==="textarea"?["type","id","label","required","render"]:type==="dropdown"?["type","id","label","options","multiple","required"]:["type","id","label","options"];
  const item=own(raw,allowed,["type","id","label",...(type==="dropdown"||type==="checkboxes"?["options"]:[])],`${type} control is malformed`),controlId=id(item.id,"control ID"),label=text(item.label,"control label"),folded=label.normalize("NFC").toLocaleLowerCase("und");
  if(ids.has(controlId))throw new Error("Issue Form has duplicate control IDs");if(labels.has(folded))throw new Error("Issue Form has duplicate control labels");ids.add(controlId);labels.add(folded);
  if(type==="input"||type==="textarea"){const required=bool(item.required,"Text control is malformed"),render=item.render===undefined?undefined:text(item.render,"render fence language");if(render!==undefined&&!/^[A-Za-z0-9][A-Za-z0-9_+.-]{0,31}$/u.test(render))throw new Error("render fence language is malformed");return Object.freeze({type,id:controlId,label,...(required===undefined?{}:{required}),...(render===undefined?{}:{render})});}
  if(type==="dropdown"){const options=uniqueStrings(item.options,"Dropdown options"),multiple=bool(item.multiple,"Dropdown control is malformed"),required=bool(item.required,"Dropdown control is malformed");return Object.freeze({type,id:controlId,label,options:Object.freeze(options),...(multiple===undefined?{}:{multiple}),...(required===undefined?{}:{required})});}
  if(!Array.isArray(item.options)||!item.options.length)throw new Error("Checkbox options are malformed");const optionIds=new Set<string>(),optionLabels=new Set<string>(),options=item.options.map(rawOption=>{const option=own(rawOption,["id","label","required","firstPerson"],["id","label"],"Checkbox option is malformed"),optionId=id(option.id,"checkbox option ID"),optionLabel=text(option.label,"checkbox label"),optionFolded=optionLabel.normalize("NFC").toLocaleLowerCase("und");if(optionIds.has(optionId)||optionLabels.has(optionFolded))throw new Error("Checkbox options contain duplicates");optionIds.add(optionId);optionLabels.add(optionFolded);const required=bool(option.required,"Checkbox option is malformed"),explicit=bool(option.firstPerson,"Checkbox option is malformed");return Object.freeze({id:optionId,label:optionLabel,...(required===undefined?{}:{required}),...(explicit===undefined?{}:{firstPerson:explicit})});});
  return Object.freeze({type:"checkboxes",id:controlId,label,options:Object.freeze(options)});
 });
}
function normalizeForm(raw:unknown):IssueForm{
 const form=own(raw,["id","titlePrefix","titleTemplate","labels","controls"],["id","titlePrefix","titleTemplate","labels","controls"],"Configuration is not a YAML Issue Form"),normalized={id:id(form.id,"form ID"),titlePrefix:safeTitle(form.titlePrefix,"Issue Form title prefix"),titleTemplate:safeTitle(form.titleTemplate,"title template",true),labels:uniqueStrings(form.labels,"Declared labels",true),controls:controls(form.controls)};
 return Object.freeze({...normalized,labels:Object.freeze(normalized.labels),controls:Object.freeze(normalized.controls)});
}
export function selectIssueForm(forms:readonly unknown[],requestedId?:string):IssueForm{
 if(!Array.isArray(forms)||!forms.length)throw new Error("exactly one authoritative YAML Issue Form is required");const normalized=forms.map(normalizeForm),ids=normalized.map(form=>form.id);if(new Set(ids).size!==ids.length)throw new Error("Issue Forms contain duplicate IDs");if(normalized.length===1){if(requestedId!==undefined&&normalized[0]!.id!==requestedId)throw new Error("Requested exact ID does not match the Issue Form");return normalized[0]!;}if(requestedId===undefined)throw new Error("Multiple Issue Forms require an exact ID");const selected=normalized.find(form=>form.id===requestedId);if(!selected)throw new Error("Requested exact ID does not match any Issue Form");return selected;
}
const sensitive=(value:string):boolean=>/(?:gh[pousr]_[\p{L}\p{N}_]{20,}|github_pat_[\p{L}\p{N}_]{20,}|\bsk-[A-Za-z0-9_-]{8,}|\bBearer\s+\S+|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+|\b(?:api[-_ ]?key|access[-_ ]?token|auth[-_ ]?token|token|secret|password|private[-_ ]?key)\s*[:=]\s*[^\s]{8,}|\b(?:AKIA|ASIA)[A-Z0-9]{16}\b|[\p{L}\p{N}._%+-]+@[\p{L}\p{N}-]+(?:\.[\p{L}\p{N}-]+)+|~\/\.[^\s]+|\/(?:root|home|Users)(?:\/[^\s]+)+|\$HOME(?:\/|\b)|\$\{HOME\}|%USERPROFILE%|[A-Za-z]:\\Users\\[^\s\\]+(?:\\|$))/iu.test(value);
function applyRedactions(title:string,body:string,labels:string[],policy:PrivacyPolicy):[string,string,string[]]{
 const record=own(policy,["redactions"],["redactions"],"Privacy policy is malformed");if(!Array.isArray(record.redactions))throw new Error("Privacy policy is malformed");const rules=record.redactions.map(raw=>{const rule=own(raw,["before","after","reviewed"],["before","after","reviewed"],"Reviewed redaction is malformed"),before=typeof rule.before==="string"?rule.before.normalize("NFC"):rule.before,after=typeof rule.after==="string"?rule.after.normalize("NFC"):rule.after;if(rule.reviewed!==true||typeof before!=="string"||!before.trim()||/[\u0000-\u001f\u007f-\u009f]/u.test(before)||typeof after!=="string"||!after.trim()||before===after)throw new Error("Reviewed redaction is malformed");return {before,after};});
 const overlaps=(left:string,right:string):boolean=>left.includes(right)||right.includes(left)||Array.from({length:Math.min(left.length,right.length)-1},(_,index)=>index+1).some(length=>left.endsWith(right.slice(0,length))||right.endsWith(left.slice(0,length)));
 for(let left=0;left<rules.length;left++)for(let right=left+1;right<rules.length;right++)if(overlaps(rules[left]!.before,rules[right]!.before))throw new Error("Reviewed redactions overlap");
 if(rules.some(rule=>rules.some(candidate=>rule.after.includes(candidate.before))))throw new Error("Reviewed redaction replacement is order-dependent");const fields=[title,body,...labels];
 const spans=rules.flatMap((rule,index)=>{const found:{field:number;start:number;end:number;index:number}[]=[];fields.forEach((field,fieldIndex)=>{for(let at=field.indexOf(rule.before);at>=0;at=field.indexOf(rule.before,at+1))found.push({field:fieldIndex,start:at,end:at+rule.before.length,index});});if(!found.length)throw new Error("Reviewed redaction before value was not present");return found;}).sort((a,b)=>a.field-b.field||a.start-b.start||a.end-b.end);if(spans.some((span,index)=>index>0&&span.field===spans[index-1]!.field&&span.start<spans[index-1]!.end&&span.index!==spans[index-1]!.index))throw new Error("Reviewed redactions overlap");
 for(const rule of rules){title=title.split(rule.before).join(rule.after).normalize("NFC");body=body.split(rule.before).join(rule.after).normalize("NFC");labels=labels.map(label=>label.split(rule.before).join(rule.after).normalize("NFC"));}if(rules.some(rule=>title.includes(rule.before)||body.includes(rule.before)||labels.some(label=>label.includes(rule.before))))throw new Error("Reviewed redaction postcondition failed");return [title.normalize("NFC"),body.normalize("NFC"),labels.map(label=>label.normalize("NFC"))];
}
const fence=(value:string):string=>"`".repeat(Math.max(3,...Array.from(value.matchAll(/`+/gu),match=>match[0].length+1)));
export function materializeIssue(formInput:IssueForm,answers:IssueAnswers,privacy:PrivacyPolicy):MaterializedIssue{
 const form=normalizeForm(formInput),bearing=form.controls.filter((control):control is Exclude<IssueControl,MarkdownControl>=>control.type!=="markdown"),expected=bearing.map(control=>control.id);own(answers,expected,expected,"Answers must exactly match answer-bearing control IDs");const values=new Map<string,string>(),parts:string[]=[];
 for(const control of form.controls){if(control.type==="markdown"){parts.push(control.body);continue;}const answer=answers[control.id];let rendered="";if(control.type==="input"||control.type==="textarea"){if(typeof answer!=="string")throw new Error("Text answer is malformed");if(control.required&&!answer.trim())throw new Error("Required text answer must be nonblank");values.set(control.id,answer);if(control.type==="textarea"&&control.render!==undefined){const marker=fence(answer);rendered=`${marker}${control.render}\n${answer}\n${marker}`;}else rendered=answer;}else if(control.type==="dropdown"){if(control.multiple){if(!Array.isArray(answer)||answer.some(value=>typeof value!=="string")||new Set(answer).size!==answer.length)throw new Error("Dropdown answer contains duplicate or malformed selections");if(control.required&&!answer.length)throw new Error("Required dropdown answer is missing");if(answer.some(value=>!control.options.includes(value)))throw new Error("Dropdown answer contains an unknown exact option");values.set(control.id,answer.join(", "));rendered=answer.map(value=>`- ${value}`).join("\n");}else{if(typeof answer!=="string"||!control.options.includes(answer))throw new Error("Single-select dropdown requires one exact option");values.set(control.id,answer);rendered=`- ${answer}`;}}else if(control.type==="checkboxes"){const optionIds=control.options.map(option=>option.id),record=own(answer,optionIds,optionIds,"Checkbox answer must exactly match option IDs");rendered=control.options.map(option=>{const checked=record[option.id];if(typeof checked!=="boolean")throw new Error("Checkbox affirmation must be explicit");if((option.required||option.firstPerson||firstPerson(option.label))&&!checked)throw new Error("Required or first-person checkbox must be explicitly affirmed");return `- [${checked?"x":" "}] ${option.label}`;}).join("\n");}else throw new Error("Issue Form control is malformed");parts.push(`### ${control.label}\n${rendered}`);}
 let title=form.titleTemplate.replace(/\{\{([A-Za-z0-9][A-Za-z0-9_-]*)\}\}/gu,(_,key:string)=>values.get(key)??`{{${key}}}`);if(/[{}]/u.test(title))throw new Error("Title template references an unresolved answer");let body=parts.join("\n\n"),labels=[...form.labels];title=(form.titlePrefix+title).normalize("NFC");body=body.normalize("NFC");labels=labels.map(label=>label.normalize("NFC"));[title,body,labels]=applyRedactions(title,body,labels,privacy);title=safeTitle(title,"Materialized issue title");labels=uniqueStrings(labels,"Materialized labels",true);if(labels.some(label=>/[\u0000-\u001f\u007f-\u009f]/u.test(label)))throw new Error("Materialized labels are malformed");if(sensitive(title)||sensitive(body)||labels.some(sensitive))throw new Error("Materialized issue contains unresolved sensitive material");const frozenLabels=Object.freeze(labels),candidateIdentity=`sha256:${createHash("sha256").update(JSON.stringify({formId:form.id,title,body,labels:frozenLabels})).digest("hex")}`;return Object.freeze({formId:form.id,title,body,labels:frozenLabels,candidateIdentity});
}
const uncertain=():DuplicateDecision=>Object.freeze({status:"block",reason:"uncertain",duplicateIssue:null});
const DEFAULT_ISSUE_HOST="github.com"; // The owner/repository shorthand is defined to target GitHub.com.
type RepositoryBinding={readonly host:string;readonly owner:string;readonly repository:string};
type IssueBinding=RepositoryBinding&{readonly canonical:string};
const repository=(value:unknown):RepositoryBinding|null=>{if(typeof value!=="string"||value.length>255||value.trim()!==value)return null;const parts=value.split("/");if(parts.length!==2&&parts.length!==3)return null;const [host,owner,name]=parts.length===2?[DEFAULT_ISSUE_HOST,...parts]:parts;if(!/^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$/u.test(host!)||!owner||!name||![owner,name].every(part=>/^[A-Za-z0-9_.-]+$/u.test(part)))return null;return {host:host!.toLowerCase(),owner:owner.toLowerCase(),repository:name.toLowerCase()};};
const query=(value:unknown):value is string=>typeof value==="string"&&value.length<=512&&!!value.trim()&&value.trim()===value&&!/[\u0000-\u001f\u007f-\u009f]/u.test(value);
const identity=(value:unknown):value is string=>typeof value==="string"&&/^sha256:[a-f0-9]{64}$/u.test(value);
const issue=(value:unknown):IssueBinding|null=>{if(typeof value!=="string")return null;let parsed:URL;try{parsed=new URL(value);}catch{return null;}if(parsed.protocol!=="https:"||parsed.username||parsed.password||parsed.port||parsed.search||parsed.hash||!/^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?$/u.test(parsed.hostname))return null;const match=/^\/([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)\/issues\/([1-9][0-9]*)$/u.exec(parsed.pathname);if(!match)return null;const host=parsed.hostname.toLowerCase(),owner=match[1]!.toLowerCase(),repository=match[2]!.toLowerCase(),number=match[3]!;return {host,owner,repository,canonical:`https://${host}/${owner}/${repository}/issues/${number}`};};
const sameRepository=(left:RepositoryBinding,right:RepositoryBinding):boolean=>left.host===right.host&&left.owner===right.owner&&left.repository===right.repository;
export function evaluateDuplicateSearch(value:DuplicateSearchInput):DuplicateDecision{
 let input:Record<string,unknown>;try{input=own(value,["repository","query","candidateIdentity","current","coversOpen","coversClosed","complete","truncated","saturated","results"],["repository","query","candidateIdentity","current","coversOpen","coversClosed","complete","truncated","saturated","results"],"Duplicate search is malformed");}catch{return uncertain();}const searchedRepository=repository(input.repository);if(!searchedRepository||!query(input.query)||!identity(input.candidateIdentity)||typeof input.current!=="boolean"||typeof input.coversOpen!=="boolean"||typeof input.coversClosed!=="boolean"||typeof input.complete!=="boolean"||typeof input.truncated!=="boolean"||typeof input.saturated!=="boolean"||!Array.isArray(input.results))return uncertain();const classifications:DuplicateClassification[]=[],canonicalIssues:string[]=[],issues=new Set<string>();for(const raw of input.results){let result:Record<string,unknown>;try{result=own(raw,["issue","repository","query","candidateIdentity","classification"],["issue","repository","query","candidateIdentity"],"Duplicate result is malformed");}catch{return uncertain();}const issueRepository=issue(result.issue);if(!issueRepository||!sameRepository(issueRepository,searchedRepository)||issues.has(issueRepository.canonical)||result.repository!==input.repository||result.query!==input.query||result.candidateIdentity!==input.candidateIdentity||result.classification!=="duplicate"&&result.classification!=="not_duplicate"&&result.classification!=="uncertain")return uncertain();issues.add(issueRepository.canonical);canonicalIssues.push(issueRepository.canonical);classifications.push(result.classification);}if(!input.current||!input.coversOpen||!input.coversClosed||!input.complete||input.truncated||input.saturated||classifications.includes("uncertain"))return uncertain();const duplicates=classifications.reduce<number[]>((found,classification,index)=>classification==="duplicate"?[...found,index]:found,[]);if(duplicates.length!==1)return duplicates.length?uncertain():Object.freeze({status:"proceed",reason:"all_not_duplicate",duplicateIssue:null});return Object.freeze({status:"block",reason:"duplicate",duplicateIssue:canonicalIssues[duplicates[0]!]!});
}
